### ISSUE TITLE
Error in Lubuntu 20.04

### ISSUE THREAD

**Issue by tellts** [mu-editor/mu#1093]
```
root @ PC: / home / ia # apt-get install libpng-dev
Reading package lists ... Done
Building a dependency tree
Reading status information ... Done
The latest libpng-dev package (1.6.37-2) is already installed.
Updated 0 packages, 0 new packages installed, 0 packages marked for removal, and 0 packages not updated.`

```

```
root@PC:/home/ia# mu-editor
Traceback (most recent call last):
  File "/usr/local/bin/mu-editor", line 5, in <module>
    from mu.app import run
  File "/usr/local/lib/python3.6/dist-packages/mu/app.py", line 29, in <module>
    from PyQt5.QtCore import QTimer, Qt
ModuleNotFoundError: No module named 'PyQt5.QtCore'
`
[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[

`Requirement already satisfied: pyqt5==5.14.1 in /usr/lib/python3/dist-packages (from mu-editor) (5.14.1)`
```

The full log:
```
root@PC:/home/ia# python3.6 -m pip install mu-editor
Collecting mu-editor
  Using cached mu_editor-1.0.3-py3-none-any.whl (2.0 MB)
Collecting pyflakes==2.0.0
  Using cached pyflakes-2.0.0-py2.py3-none-any.whl (53 kB)
Collecting appdirs>=1.4.3
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: pyqt5==5.14.1 in /usr/lib/python3/dist-packages (from mu-editor) (5.14.1)
Collecting gpiozero>=1.4.1
  Using cached gpiozero-1.5.1-py2.py3-none-any.whl (138 kB)
Collecting guizero>=1.1.0
  Using cached guizero-1.1.0-py3-none-any.whl (41 kB)
Collecting pyserial==3.4
  Using cached pyserial-3.4-py2.py3-none-any.whl (193 kB)
Collecting nudatus>=0.0.3
  Using cached nudatus-0.0.4.tar.gz (4.5 kB)
Collecting qtconsole==4.3.1
  Using cached qtconsole-4.3.1-py2.py3-none-any.whl (108 kB)
Collecting qscintilla==2.11.4
  Using cached QScintilla-2.11.4-1-cp35.cp36.cp37.cp38-abi3-manylinux2014_x86_64.whl (1.9 MB)
Requirement already satisfied: Pillow>=5.2.0 in /usr/lib/python3/dist-packages (from mu-editor) (7.0.0)
Collecting pycodestyle==2.4.0
  Using cached pycodestyle-2.4.0-py2.py3-none-any.whl (62 kB)
Requirement already satisfied: requests>=2.19.1 in /usr/lib/python3/dist-packages (from mu-editor) (2.22.0)
Collecting matplotlib==2.2.2
  Downloading matplotlib-2.2.2-cp36-cp36m-manylinux1_x86_64.whl (12.6 MB)
     |████████████████████████████████| 12.6 MB 94 kB/s 
Collecting pigpio>=1.40.post1
  Using cached pigpio-1.46-py2.py3-none-any.whl (39 kB)
Collecting pgzero==1.2
  Using cached pgzero-1.2-py3-none-any.whl (69 kB)
Collecting PyQtChart==5.14.0
  Using cached PyQtChart-5.14.0-5.14.2-cp35.cp36.cp37.cp38-abi3-manylinux2014_x86_64.whl (1.2 MB)
Collecting semver>=2.8.0
  Using cached semver-2.10.2-py2.py3-none-any.whl (12 kB)
Collecting colorzero
  Using cached colorzero-1.1-py2.py3-none-any.whl (33 kB)
Collecting traitlets
  Downloading traitlets-4.3.3-py2.py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 173 kB/s 
Collecting ipykernel>=4.1
  Using cached ipykernel-5.3.4-py3-none-any.whl (120 kB)
Collecting pygments
  Using cached Pygments-2.6.1-py3-none-any.whl (914 kB)
Collecting jupyter-core
  Using cached jupyter_core-4.6.3-py2.py3-none-any.whl (83 kB)
Collecting jupyter-client>=4.1
  Using cached jupyter_client-6.1.7-py3-none-any.whl (108 kB)
Collecting ipython-genutils
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting PyQt5-sip<13,>=12.7
  Downloading PyQt5_sip-12.8.1-cp36-cp36m-manylinux1_x86_64.whl (278 kB)
     |████████████████████████████████| 278 kB 924 kB/s 
Collecting pytz
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Requirement already satisfied: six>=1.10 in /usr/lib/python3/dist-packages (from matplotlib==2.2.2->mu-editor) (1.14.0)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.2.0-cp36-cp36m-manylinux1_x86_64.whl (88 kB)
     |████████████████████████████████| 88 kB 507 kB/s 
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting numpy>=1.7.1
  Downloading numpy-1.19.1-cp36-cp36m-manylinux2010_x86_64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 74 kB/s 
Collecting pygame<2.0,>=1.9.2
  Downloading pygame-1.9.6-cp36-cp36m-manylinux1_x86_64.whl (11.4 MB)
     |████████████████████████████████| 11.4 MB 1.4 MB/s 
Collecting decorator
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting tornado>=4.2
  Using cached tornado-6.0.4.tar.gz (496 kB)
Collecting ipython>=5.0.0
  Downloading ipython-7.16.1-py3-none-any.whl (785 kB)
     |████████████████████████████████| 785 kB 847 kB/s 
Collecting pyzmq>=13
  Downloading pyzmq-19.0.2-cp36-cp36m-manylinux1_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 924 kB/s 
Collecting backcall
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Using cached prompt_toolkit-3.0.7-py3-none-any.whl (355 kB)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/lib/python3/dist-packages (from ipython>=5.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor) (4.6.0)
Requirement already satisfied: setuptools>=18.5 in /usr/lib/python3/dist-packages (from ipython>=5.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor) (45.2.0)
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting jedi>=0.10
  Using cached jedi-0.17.2-py2.py3-none-any.whl (1.4 MB)
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting parso<0.8.0,>=0.7.0
  Using cached parso-0.7.1-py2.py3-none-any.whl (109 kB)
Building wheels for collected packages: nudatus, tornado
  Building wheel for nudatus (setup.py) ... done
  Created wheel for nudatus: filename=nudatus-0.0.4-py3-none-any.whl size=4983 sha256=639a295622d90616f22f190cd00c5f348adcf97310e04053c89abbb61cf5485e
  Stored in directory: /root/.cache/pip/wheels/96/8b/dc/4095ab0a92c8ee4baf30f59f1b07958a784e96f93feebc5ab1
  Building wheel for tornado (setup.py) ... done
  Created wheel for tornado: filename=tornado-6.0.4-cp36-cp36m-linux_x86_64.whl size=415151 sha256=fd3c0679a850d0e4383d85525fba086f318cb3fae357a57784eaba3ad4bdbb4a
  Stored in directory: /root/.cache/pip/wheels/37/a7/db/2d592e44029ef817f3ef63ea991db34191cebaef087a96f505
Successfully built nudatus tornado
Installing collected packages: pyflakes, appdirs, colorzero, gpiozero, guizero, pyserial, nudatus, decorator, ipython-genutils, traitlets, tornado, backcall, wcwidth, prompt-toolkit, pygments, pickleshare, parso, jedi, ipython, python-dateutil, pyzmq, jupyter-core, jupyter-client, ipykernel, qtconsole, PyQt5-sip, qscintilla, pycodestyle, pytz, pyparsing, kiwisolver, cycler, numpy, matplotlib, pigpio, pygame, pgzero, PyQtChart, semver, mu-editor
Successfully installed PyQt5-sip-12.8.1 PyQtChart-5.14.0 appdirs-1.4.4 backcall-0.2.0 colorzero-1.1 cycler-0.10.0 decorator-4.4.2 gpiozero-1.5.1 guizero-1.1.0 ipykernel-5.3.4 ipython-7.16.1 ipython-genutils-0.2.0 jedi-0.17.2 jupyter-client-6.1.7 jupyter-core-4.6.3 kiwisolver-1.2.0 matplotlib-2.2.2 mu-editor-1.0.3 nudatus-0.0.4 numpy-1.19.1 parso-0.7.1 pgzero-1.2 pickleshare-0.7.5 pigpio-1.46 prompt-toolkit-3.0.7 pycodestyle-2.4.0 pyflakes-2.0.0 pygame-1.9.6 pygments-2.6.1 pyparsing-2.4.7 pyserial-3.4 python-dateutil-2.8.1 pytz-2020.1 pyzmq-19.0.2 qscintilla-2.11.4 qtconsole-4.3.1 semver-2.10.2 tornado-6.0.4 traitlets-4.3.3 wcwidth-0.2.5
root@PC:/home/ia# mu-editor
Traceback (most recent call last):
  File "/usr/local/bin/mu-editor", line 5, in <module>
    from mu.app import run
  File "/usr/local/lib/python3.6/dist-packages/mu/app.py", line 29, in <module>
    from PyQt5.QtCore import QTimer, Qt
ModuleNotFoundError: No module named 'PyQt5.QtCore'
root@PC:/home/ia#

```

-----

Edit by @carlosperate: Updating formatting for readability.

**Comment by tellts** [comment]
Hello. It turned out to run.
https://www.cyberforum.ru/python/thread2694570.html

**Comment by carlosperate** [comment]
Hi @tellts,

Could you give us more information about your environment? OS, architecture, Python version, virtualenv, other python  packages installed, etc?

**Comment by tellts** [comment]
```
`OS, architecture`
Lubuntu 20.04 64 bits

I have pytons installed:
3.6
3.7
3.8.2
The last time I tried to install the editor with the command (after which it also did not work):
python3.7 -m pip install mu-editor

If I remember correctly, I tried installing the editor via Python 3.6 earlier before.

Then I installed the version of PyQt, about which it was written in the console that it was not correct, but this led to the editor working:
ERROR: mu-editor 1.0.3 has requirement pyqt5==5.14.1, but you'll have pyqt5 5.15.0 which is incompatible.

I used the following commands for this:
python3.6 -m pip install https://files.pythonhosted.org/packages/8e/24/ede6428359f913ed9cd1643dd5533aefeb5a2699cc95bea089de50ead586/pygame-1.9.6-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: pygame==1.9.6 from https://files.pythonhosted.org/packages/8e/24/ede6428359f913ed9cd1643dd5533aefeb5a2699cc95bea089de50ead586/pygame-1.9.6-cp36-cp36m-manylinux1_x86_64.whl in /usr/local/lib/python3.6/dist-packages (1.9.6)
root@PC:/home/ia# python3.6 -m pip install https://files.pythonhosted.org/packages/45/32/341fa5b9fc010ff4e520efe7cdbad24e61890230cf4eb12c871f512ee456/PyQt5-5.15.0-5.15.0-cp35.cp36.cp37.cp38-abi3-manylinux2014_x86_64.whl
Collecting PyQt5==5.15.0
```

**Comment by carlosperate** [comment]
v1.0.3 depends on PyQt5 v5.14.1: https://github.com/mu-editor/mu/blob/1.0.3/setup.py#L15

Could you try `python3.6 -m pip install PyQt5==5.14.1`?

**Comment by tellts** [comment]
Should this command be executed with administrator rights?

**Comment by carlosperate** [comment]
Not sure, but if you create a virtual environment you should be able to install all dependencies there with only user rights.

**Comment by tellts** [comment]
I did it with administrator rights.

**Comment by carlosperate** [comment]
If you install it in a virtual environment, do you get all the dependencies installed with the right versions?
It sounds like maybe you already had PyQt 5.15.0 installed and that's why it was failing?

**Comment by carlosperate** [comment]
Okay, as it sounds the issue has been resolved I'll close this ticket. But please, feel free to reopen if you still have any questions.
