### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by rodrigomologni** [mu-editor/mu#1378]
Version: 1.1.0.beta.2
Locale: pt_BR
Platform: Windows 10 10.0.18362 AMD64

```
Traceback (most recent call last):
  File "C:\Users\Rodrigo Mologni\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 162, in run
    raise ex
  File "C:\Users\Rodrigo Mologni\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 149, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\Rodrigo Mologni\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 441, in ensure_and_create
    self.ensure()
  File "C:\Users\Rodrigo Mologni\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 469, in ensure
    self.ensure_interpreter_version()
  File "C:\Users\Rodrigo Mologni\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 522, in ensure_interpreter_version
    process = subprocess.run(
  File "C:\Users\Rodrigo Mologni\AppData\Local\Programs\Mu Editor\Python\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\Rodrigo Mologni\\AppData\\Local\\python\\mu\\mu_venv-38-20210317-125442\\scripts\\python.exe', '-c', 'import sys; print("%s%s" % sys.version_info[:2])']' returned non-zero exit status 101.

```

**Comment by rodrigomologni** [comment]
Hi @tjguk! You're right! I created a new user without spaces. Mu editor is working now! Thank you!
