### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by nahallmansouri** [mu-editor/mu#1382]
Version: 1.1.0.beta.2
Locale: en_US
Platform: Windows 10 10.0.19041 AMD64

```
Traceback (most recent call last):
  File "C:\Users\Nahall Mansouri\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 162, in run
    raise ex
  File "C:\Users\Nahall Mansouri\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 149, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\Nahall Mansouri\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 441, in ensure_and_create
    self.ensure()
  File "C:\Users\Nahall Mansouri\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 469, in ensure
    self.ensure_interpreter_version()
  File "C:\Users\Nahall Mansouri\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 522, in ensure_interpreter_version
    process = subprocess.run(
  File "C:\Users\Nahall Mansouri\AppData\Local\Programs\Mu Editor\Python\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\Nahall Mansouri\\AppData\\Local\\python\\mu\\mu_venv-38-20210317-155003\\scripts\\python.exe', '-c', 'import sys; print("%s%s" % sys.version_info[:2])']' returned non-zero exit status 101.

```

**Comment by tjguk** [comment]
Thanks for the crash report, @nahallmansouri  -- this looks like https://github.com/mu-editor/mu/issues/1372. If you are able to, please try running Mu under a user whose username (eg "Nahall Mansouri") does not include a space. In any case we hope to have this fixed for the next beta.
