### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by wes4545** [mu-editor/mu#1418]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.2
Locale: en_US
Platform: Windows 10 10.0.15063 AMD64

```
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 162, in run
    raise ex
  File "C:\Users\hp\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 149, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\hp\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 459, in ensure_and_create
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Unable to create a working virtual environment.

```

**Comment by carlosperate** [comment]
Hi @wes4545, would you be able to attach the log file to this ticket, it will help us diagnose the issue.
The log file can be found in: `%LOCALAPPDATA%\python\mu\Logs`

**Comment by carlosperate** [comment]
Closing due to lack of activity, but please feel free to reopen if you are still encountering this issue.
Thanks for sending the crash report!
