### ISSUE TITLE
Since Apple update Mu is not loading and crashes at the access to volumes circuit pi files

### ISSUE THREAD

**Issue by brucebaranski** [mu-editor/mu#1429]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.2
Locale: en_US
Platform: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64

```
Traceback (most recent call last):
  File "/Applications/Mu Editor 2.app/Contents/Resources/Python/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Mu Editor 2.app/Contents/Resources/Python/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Applications/Mu Editor 2.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/__main__.py", line 9, in <module>
    main()
  File "/Applications/Mu Editor 2.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/__main__.py", line 5, in main
    run()
  File "/Applications/Mu Editor 2.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/app.py", line 339, in run
    editor.setup(setup_modes(editor, editor_window))
  File "/Applications/Mu Editor 2.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/logic.py", line 829, in setup
    shutil.copytree(path("templates", "web/"), template_path)
  File "/Applications/Mu Editor 2.app/Contents/Resources/Python/lib/python3.8/shutil.py", line 554, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Applications/Mu Editor 2.app/Contents/Resources/Python/lib/python3.8/shutil.py", line 455, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/Applications/Mu Editor 2.app/Contents/MacOS/../Resources/Python/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 1] Operation not permitted: '/Volumes/CIRCUITPY/templates'

```

**Comment by carlosperate** [comment]
Thanks for the report @brucebaranski!
As we have https://github.com/mu-editor/mu/issues/1410 already open and it looks like the same issue, let's try to resolve it over there to avoid duplicates.
I'll close this issue, but if you think these are separate problem please do feel free to reopen it.
