### ISSUE TITLE
does not match

### ISSUE THREAD

**Issue by newsgrep** [mu-editor/mu#1522]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.4
Locale: de_DE
Platform: Linux 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mu/logic.py", line 711, in check_usb
    detected = mode.find_devices(with_logging=False)
  File "/usr/local/lib/python3.8/dist-packages/mu/modes/base.py", line 420, in find_devices
    available_ports = QSerialPortInfo.availablePorts()
KeyboardInterrupt

```

**Comment by newsgrep** [comment]
opend by mistake. 
Seems to be the default "err" msg when it gets killed through ctrl+c in a termnal.
