### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by zuna-boop** [mu-editor/mu#1533]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.4
Locale: es_BO
Platform: Windows 10 10.0.19041 AMD64

```
Traceback (most recent call last):
  File "C:\Users\Geff\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\interface\panes.py", line 754, in on_ls_fail
    self.disable()
  File "C:\Users\Geff\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\interface\panes.py", line 693, in disable
    self.microbit_fs.setDisabled(True)
RuntimeError: wrapped C/C++ object of type MicroPythonDeviceFileList has been deleted

```

**Comment by carlosperate** [comment]
Thank you very much for the crash report @zuna-boop!

I believe this is the same issue from https://github.com/mu-editor/mu/issues/1428, so to try to keep things tidy I will merge this report there to track the progress in a single place.

If you could attach your log to that ticket it would be quite useful too, as that will help us gather more information on the issue. The log file should be located in: `%LOCALAPPDATA%\python\mu\Logs`
