### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by gabriel4569** [mu-editor/mu#1534]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.4
Locale: pt_BR
Platform: Windows 10 10.0.19041 AMD64

```
Traceback (most recent call last):
  File "C:\Users\FamÃ­lia Santos\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 161, in run
    raise ex
  File "C:\Users\FamÃ­lia Santos\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 148, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\FamÃ­lia Santos\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 494, in ensure_and_create
    self.create()
  File "C:\Users\FamÃ­lia Santos\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 624, in create
    self.upgrade_pip()
  File "C:\Users\FamÃ­lia Santos\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 665, in upgrade_pip
    ok, output = self.run_subprocess(
  File "C:\Users\FamÃ­lia Santos\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 382, in run_subprocess
    compact(process.stdout.decode("utf-8")),
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 50: invalid continuation byte

```

**Comment by carlosperate** [comment]
Thank you very much for the crash report @gabriel4569!

I believe this is the same issue from https://github.com/mu-editor/mu/issues/1512, so to try to keep things tidy I will merge this report there to track the progress in a single place.

If you could attach your log to that ticket it would be quite useful too, as that will help us gather more information on the issue.
The log file should be located in: `%LOCALAPPDATA%\python\mu\Logs`
