### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by TreintaTreinta** [mu-editor/mu#1537]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.4
Locale: en_GB
Platform: Windows 10 10.0.19041 AMD64

```
Traceback (most recent call last):
  File "C:\Users\IvÃ¡n\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 161, in run
    raise ex
  File "C:\Users\IvÃ¡n\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 148, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\IvÃ¡n\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 494, in ensure_and_create
    self.create()
  File "C:\Users\IvÃ¡n\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 624, in create
    self.upgrade_pip()
  File "C:\Users\IvÃ¡n\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 665, in upgrade_pip
    ok, output = self.run_subprocess(
  File "C:\Users\IvÃ¡n\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 382, in run_subprocess
    compact(process.stdout.decode("utf-8")),
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 49: invalid continuation byte

```

**Comment by carlosperate** [comment]
Thank you very much for the crash report @TreintaTreinta!

I believe this is the same issue from #1512, so to try to keep things tidy I will merge this report there to track the progress in a single place.
