### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by hugodahl** [mu-editor/mu#1548]
[mu.log](https://github.com/mu-editor/mu/files/6445959/mu.log)
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.4
Locale: en_US
Platform: Windows 10 10.0.19041 AMD64

```
Traceback (most recent call last):
  File "C:\Users\hugo\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 161, in run
    raise ex
  File "C:\Users\hugo\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 148, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\hugo\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 495, in ensure_and_create
    self.ensure()
  File "C:\Users\hugo\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 524, in ensure
    self.ensure_key_modules()
  File "C:\Users\hugo\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 602, in ensure_key_modules
    raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Failed to import: pgzero

```

**Comment by tjguk** [comment]
Thanks for the report, @hugodahl, and especially for attaching the logs. Was this an upgrade from a previous beta? If so, then we're tracking a change over at https://github.com/mu-editor/mu/pull/1530 which should fix this and we hope to get the next beta out shortly.

If it wasn't then let me know and we'll investigate further

**Comment by hugodahl** [comment]
It was indeed an upgrade. However, I'm about 97% certain that the 1.1.0b4 had run at least once before the crash, although that 3% of uncertainty is a rather big 3%! :)

**Comment by hugodahl** [comment]
Meant to add, I uninstalled and deleted the installation and virtual environment in `%LOCALAPPDATA%` and was able to use Mu

**Comment by tjguk** [comment]
Ok; thanks for confirming. I'll close this one and hope that our in-flight fix prevents the problem for others
