### ISSUE TITLE
Crash Report - unable to download esptool

### ISSUE THREAD

**Issue by sixty-nine** [mu-editor/mu#1549]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.4
Locale: en_US
Platform: Linux 4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64

```
Traceback (most recent call last):
  File "/home/dan/.local/lib/python3.6/site-packages/mu/virtual_environment.py", line 730, in install_baseline_packages
    wheels.download(interpreter=self.interpreter, logger=logger)
  File "/home/dan/.local/lib/python3.6/site-packages/mu/wheels/__init__.py", line 138, in download
    "Pip was unable to download %s" % pip_identifier
mu.wheels.WheelsDownloadError: Pip was unable to download esptool==3.*

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dan/.local/lib/python3.6/site-packages/mu/app.py", line 161, in run
    raise ex
  File "/home/dan/.local/lib/python3.6/site-packages/mu/app.py", line 148, in run
    venv.ensure_and_create(self.display_text)
  File "/home/dan/.local/lib/python3.6/site-packages/mu/virtual_environment.py", line 494, in ensure_and_create
    self.create()
  File "/home/dan/.local/lib/python3.6/site-packages/mu/virtual_environment.py", line 625, in create
    self.install_baseline_packages()
  File "/home/dan/.local/lib/python3.6/site-packages/mu/virtual_environment.py", line 732, in install_baseline_packages
    raise VirtualEnvironmentCreateError(exc.message)
mu.virtual_environment.VirtualEnvironmentCreateError: Pip was unable to download esptool==3.*

```

**Comment by sixty-nine** [comment]
I'm sorry, I fixed that with a pip3 update.

```
sudo -H pip3 install --upgrade pip
```
