### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by luchskeudenn** [mu-editor/mu#1555]
Hi,
I tried to run the newly installed *mu* but got this crash report. If you can help, that would be great.
Thank and regards,
Mikaël

**REMEMBER TO ATTACH YOUR LOG FILE**
[mu.log](https://github.com/mu-editor/mu/files/6451057/mu.log)

Version: 1.1.0.beta.4
Locale: fr_CH
Platform: Windows 10 10.0.19041 AMD64

```
Traceback (most recent call last):
  File "C:\Users\ENVY 17-r185\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 161, in run
    raise ex
  File "C:\Users\ENVY 17-r185\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 148, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\ENVY 17-r185\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 494, in ensure_and_create
    self.create()
  File "C:\Users\ENVY 17-r185\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 624, in create
    self.upgrade_pip()
  File "C:\Users\ENVY 17-r185\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 671, in upgrade_pip
    raise VirtualEnvironmentCreateError("Unable to upgrade pip")
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to upgrade pip

```

**Comment by carlosperate** [comment]
The first issue was problem upgrading pip:

```
2021-05-10 11:21:17,987 - mu.virtual_environment:660(upgrade_pip) DEBUG: About to upgrade pip; interpreter C:\Users\ENVY 17-r185\AppData\Local\python\mu\mu_venv-38-20210510-112116\scripts\python.exe exists
2021-05-10 11:21:18,262 - mu.virtual_environment:379(run_subprocess) DEBUG: Process returned 101; output: Unable to create process using 'C:\Users\ENVY 17-r185\AppData\Local\Programs\Mu Editor\Python\python.exe -m pip install --upgrade pip'
2021-05-10 11:21:18,267 - mu.virtual_environment:468(quarantine_failed_venv) INFO: Quarantined C:\Users\ENVY 17-r185\AppData\Local\python\mu\mu_venv-38-20210510-112116 as C:\Users\ENVY 17-r185\AppData\Local\python\mu\mu_venv-38-20210510-112116.FAILED
2021-05-10 11:21:18,267 - mu.virtual_environment:509(ensure_and_create) DEBUG: Emitter: <bound PYQT_SIGNAL display_text of StartupWorker object at 0x000001DC26D80EE0>; Splash Handler; <SplashLogHandler (INFO)>
2021-05-10 11:21:25,275 - root:173(excepthook) ERROR: Unrecoverable error
Traceback (most recent call last):
  File "C:\Users\ENVY 17-r185\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 161, in run
    raise ex
  File "C:\Users\ENVY 17-r185\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 148, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\ENVY 17-r185\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 494, in ensure_and_create
    self.create()
  File "C:\Users\ENVY 17-r185\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 624, in create
    self.upgrade_pip()
  File "C:\Users\ENVY 17-r185\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 671, in upgrade_pip
    raise VirtualEnvironmentCreateError("Unable to upgrade pip")
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to upgrade pip
```
https://github.com/mu-editor/mu/blob/38f905a2fcb57b5438a39862b8823c31e74e0290/mu/virtual_environment.py#L660-L671


Then on the second launch we encounter the same issue, although this time it tries to quarantine the venv and try again? Not sure why that didn't happen the first time.

So in this case it tries to quarantine the venv and then it fails with the `FileExistsError` as tracked in  

```
2021-05-10 11:22:09,182 - mu.virtual_environment:660(upgrade_pip) DEBUG: About to upgrade pip; interpreter C:\Users\ENVY 17-r185\AppData\Local\python\mu\mu_venv-38-20210510-112116\scripts\python.exe exists
2021-05-10 11:22:09,351 - mu.virtual_environment:379(run_subprocess) DEBUG: Process returned 101; output: Unable to create process using 'C:\Users\ENVY 17-r185\AppData\Local\Programs\Mu Editor\Python\python.exe -m pip install --upgrade pip'
2021-05-10 11:22:09,374 - mu.virtual_environment:464(quarantine_failed_venv) ERROR: Unable to quarantine C:\Users\ENVY 17-r185\AppData\Local\python\mu\mu_venv-38-20210510-112116 as C:\Users\ENVY 17-r185\AppData\Local\python\mu\mu_venv-38-20210510-112116.FAILED
Traceback (most recent call last):
  File "C:\Users\ENVY 17-r185\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 494, in ensure_and_create
    self.create()
  File "C:\Users\ENVY 17-r185\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 624, in create
    self.upgrade_pip()
  File "C:\Users\ENVY 17-r185\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 671, in upgrade_pip
    raise VirtualEnvironmentCreateError("Unable to upgrade pip")
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to upgrade pip

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ENVY 17-r185\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 462, in quarantine_failed_venv
    os.rename(self.path, error_dirpath)
FileExistsError: [WinError 183] Impossible de créer un fichier déjà existant: 'C:\\Users\\ENVY 17-r185\\AppData\\Local\\python\\mu\\mu_venv-38-20210510-112116' -> 'C:\\Users\\ENVY 17-r185\\AppData\\Local\\python\\mu\\mu_venv-38-20210510-112116.FAILED'
```
https://github.com/mu-editor/mu/blob/38f905a2fcb57b5438a39862b8823c31e74e0290/mu/virtual_environment.py#L459-L468

-----

The first part about failing to upgrade pip will be tracked as part of https://github.com/mu-editor/mu/issues/1532#issuecomment-838767600.

The second as issue trying to quarantine the venv will be tracked as part of https://github.com/mu-editor/mu/issues/1556#issuecomment-838773107.

So to keep things tidy I will close this issue here as we'll track the issues in different tickets. Thank you again for the crash report @luchskeudenn it has been really useful to analyse these problems!
