### ISSUE TITLE
Collection of FileExistsError and/or PermissionError crashes during venv creation

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#1556]
Creating this issue to collect the cases where we encounter an error like this:

```
Traceback (most recent call last):
  File "C:\Users\idea\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 462, in quarantine_failed_venv
    os.rename(self.path, error_dirpath)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\idea\\AppData\\Local\\python\\mu\\mu_venv-38-20210509-222823' -> 'C:\\Users\\idea\\AppData\\Local\\python\\mu\\mu_venv-38-20210509-222823.FAILED'
```

In many cases this seems to be a "secondary" error, where something else has failed beforehand, and then quen trying to rename the venv we get a different error.

For this reason is better to keep these individual issues open, as the first problem might be different. There is a chance that they all have similar problems manifesting in different ways, but as that is not clear yet let's look at them individually.

**Comment by carlosperate** [comment]
From https://github.com/mu-editor/mu/issues/1500:

> [mu.log](https://github.com/mu-editor/mu/files/6360982/mu.log)
> 
> Version: 1.1.0.beta.4
> Locale: en_GB
> Platform: Windows 10 10.0.19041 AMD64

First it errors when trying to upgrade pip, and then we a `FileExistsError` trying to rename the `venv` to `venv.FAILED'`:
```
2021-04-22 21:09:00,315 - mu.virtual_environment:379(run_subprocess) DEBUG: Process returned 101; output: Unable to create process using 'C:\Users\jason hart\AppData\Local\Programs\Mu Editor\Python\python.exe -m pip install --upgrade pip'
2021-04-22 21:09:00,315 - mu.virtual_environment:464(quarantine_failed_venv) ERROR: Unable to quarantine C:\Users\jason hart\AppData\Local\python\mu\mu_venv-38-20210422-210256 as C:\Users\jason hart\AppData\Local\python\mu\mu_venv-38-20210422-210256.FAILED
Traceback (most recent call last):
  File "C:\Users\jason hart\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 494, in ensure_and_create
    self.create()
  File "C:\Users\jason hart\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 624, in create
    self.upgrade_pip()
  File "C:\Users\jason hart\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 671, in upgrade_pip
    raise VirtualEnvironmentCreateError("Unable to upgrade pip")
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to upgrade pip

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jason hart\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 462, in quarantine_failed_venv
    os.rename(self.path, error_dirpath)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\jason hart\\AppData\\Local\\python\\mu\\mu_venv-38-20210422-210256' -> 'C:\\Users\\jason hart\\AppData\\Local\\python\\mu\\mu_venv-38-20210422-210256.FAILED'
```

**Comment by carlosperate** [comment]
From https://github.com/mu-editor/mu/issues/1523:

> Log pasted in https://github.com/mu-editor/mu/issues/1523#issue-873612363
> Version: 1.1.0.beta.4
> Locale: pl_PL
> Platform: Windows 10 10.0.19041 AMD64

There are some issue installing the dependencies, so then when it tries to verify if they are present it fails, and then at the quarantining step it fails with a `FileExistsError`.
```
2021-05-01 09:48:32,140 - mu.virtual_environment:379(run_subprocess) DEBUG: Process returned 1; output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pgzero'
2021-05-01 09:48:32,144 - mu.virtual_environment:464(quarantine_failed_venv) ERROR: Unable to quarantine C:\Users\soare\AppData\Local\python\mu\mu_venv-38-20210430-083410 as C:\Users\soare\AppData\Local\python\mu\mu_venv-38-20210430-083410.FAILED
Traceback (most recent call last):
  File "C:\Users\soare\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 495, in ensure_and_create
    self.ensure()
  File "C:\Users\soare\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 524, in ensure
    self.ensure_key_modules()
  File "C:\Users\soare\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 602, in ensure_key_modules
    raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Failed to import: pgzero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\soare\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 462, in quarantine_failed_venv
    os.rename(self.path, error_dirpath)
FileExistsError: [WinError 183] Nie można utworzyć pliku, który już istnieje: 'C:\\Users\\soare\\AppData\\Local\\python\\mu\\mu_venv-38-20210430-083410' -> 'C:\\Users\\soare\\AppData\\Local\\python\\mu\\mu_venv-38-20210430-083410.FAILED'
```

https://github.com/mu-editor/mu/blob/38f905a2fcb57b5438a39862b8823c31e74e0290/mu/virtual_environment.py#L459-L468

**Comment by carlosperate** [comment]
From #1553:

> [mu.txt](https://github.com/mu-editor/mu/files/6449643/mu.txt)
> **REMEMBER TO ATTACH YOUR LOG FILE**
> 
> Version: 1.1.0.beta.4
> Locale: en_IN
> Platform: Windows 10 10.0.18362 AMD64

Interestingly in this case we hit both the `FileExistsError` and `PermissionError `.

First we get a `FileExistsError` while creating the venv and then a `PermissionError` when trying to rename it to `x.FAILED`:
```
2021-05-10 10:24:05,789 - mu.virtual_environment:491(ensure_and_create) DEBUG: Checking virtual environment; attempt #1.
2021-05-10 10:24:12,257 - mu.virtual_environment:633(create_venv) INFO: Creating virtualenv: C:\Users\idea\AppData\Local\python\mu\mu_venv-38-20210509-222823
2021-05-10 10:24:12,318 - mu.virtual_environment:634(create_venv) INFO: Virtualenv name: mu_venv-38-20210509-222823
2021-05-10 10:24:12,318 - mu.virtual_environment:634(create_venv) INFO: Virtualenv name: mu_venv-38-20210509-222823
2021-05-10 10:24:16,036 - mu.virtual_environment:379(run_subprocess) DEBUG: Process returned 1; output: FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\idea\\AppData\\Local\\python\\mu\\mu_venv-38-20210509-222823\\Lib\\site-packages'
2021-05-10 10:24:16,239 - mu.virtual_environment:464(quarantine_failed_venv) ERROR: Unable to quarantine C:\Users\idea\AppData\Local\python\mu\mu_venv-38-20210509-222823 as C:\Users\idea\AppData\Local\python\mu\mu_venv-38-20210509-222823.FAILED
Traceback (most recent call last):
  File "C:\Users\idea\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 494, in ensure_and_create
    self.create()
  File "C:\Users\idea\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 623, in create
    self.create_venv()
  File "C:\Users\idea\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 654, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using C:\Users\idea\AppData\Local\Programs\Mu Editor\Python\pythonw.exe at C:\Users\idea\AppData\Local\python\mu\mu_venv-38-20210509-222823

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\idea\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 462, in quarantine_failed_venv
    os.rename(self.path, error_dirpath)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\idea\\AppData\\Local\\python\\mu\\mu_venv-38-20210509-222823' -> 'C:\\Users\\idea\\AppData\\Local\\python\\mu\\mu_venv-38-20210509-222823.FAILED'
2021-05-10 10:24:16,474 - mu.virtual_environment:410(relocate) DEBUG: Virtual environment set up mu_venv-38-20210510-102416 at C:\Users\idea\AppData\Local\python\mu\mu_venv-38-20210510-102416
```

Then after other errors we get a `FileExistsError` when trying to rename it to `x.FAILED` (before we got a `PermissionError`):

021-05-10 10:29:02,189 - mu.virtual_environment:379(run_subprocess) DEBUG: Process returned 1; output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pgzero'
2021-05-10 10:29:02,189 - mu.virtual_environment:464(quarantine_failed_venv) ERROR: Unable to quarantine C:\Users\idea\AppData\Local\python\mu\mu_venv-38-20210509-222823 as C:\Users\idea\AppData\Local\python\mu\mu_venv-38-20210509-222823.FAILED
Traceback (most recent call last):
  File "C:\Users\idea\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 495, in ensure_and_create
    self.ensure()
  File "C:\Users\idea\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 524, in ensure
    self.ensure_key_modules()
  File "C:\Users\idea\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 602, in ensure_key_modules
    raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Failed to import: pgzero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\idea\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 462, in quarantine_failed_venv
    os.rename(self.path, error_dirpath)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\idea\\AppData\\Local\\python\\mu\\mu_venv-38-20210509-222823' -> 'C:\\Users\\idea\\AppData\\Local\\python\\mu\\mu_venv-38-20210509-222823.FAILED'
2021-05-10 10:29:02,267 - mu.virtual_environment:410(relocate) DEBUG: Virtual environment set up mu_venv-38-20210510-102902 at C:\Users\idea\AppData\Local\python\mu\mu_venv-38-20210510-102902
```

**Comment by carlosperate** [comment]
From https://github.com/mu-editor/mu/issues/1559:

> [mu.log](https://github.com/mu-editor/mu/files/6464533/mu.log)
> Version: 1.1.0.beta.4
> Locale: en_GB
> Platform: Windows 10 10.0.18362 AMD64


In this case it looks like the way it fails to quarantine a venv changes between the first time the Mu editor was launched, to the second. More info in https://github.com/mu-editor/mu/issues/1559#issuecomment-839650490

By the end it fails install and then verify one of the packaged wheels:

```
2021-05-12 10:00:25,111 - mu.virtual_environment:379(run_subprocess) DEBUG: Process returned 1; output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pgzero'
2021-05-12 10:00:25,111 - mu.virtual_environment:464(quarantine_failed_venv) ERROR: Unable to quarantine C:\Users\alice\AppData\Local\python\mu\mu_venv-38-20210512-084040 as C:\Users\alice\AppData\Local\python\mu\mu_venv-38-20210512-084040.FAILED
Traceback (most recent call last):
  File "C:\Users\alice\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 495, in ensure_and_create
    self.ensure()
  File "C:\Users\alice\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 524, in ensure
    self.ensure_key_modules()
  File "C:\Users\alice\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 602, in ensure_key_modules
    raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Failed to import: pgzero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alice\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 462, in quarantine_failed_venv
    os.rename(self.path, error_dirpath)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\alice\\AppData\\Local\\python\\mu\\mu_venv-38-20210512-084040' -> 'C:\\Users\\alice\\AppData\\Local\\python\\mu\\mu_venv-38-20210512-084040.FAILED'
```

**Comment by tjguk** [comment]
First thank you so much @carlosperate  for doing all this spadework.

**Quarantine Errors**

First, if an attempt to quarantine fails, that won't cause any problem in the future: it's a housekeeping exercise to make it easier to spot the current venv folder. As far as I can see from the tracebacks above, the `quarantine` code correctly logs any `OSError` exception and then carries on: it doesn't cause the remainder of the venv creation to fail. All the exceptions we've seen are instances of subclasses of `OSError` (`FileNotFoundError`, `PermissionError` etc.).

However I am concerned by the `FileExistsError` where we appear to be renaming to an existing `.FAILED` folder. It still won't cause a problem, and I'm assuming it's a race condition of sorts, where we manage to make two attempts in a single second. But still it feels fragile.

In short, while we could add some kind of collision detection logic to the quarantine mechanism, I don't really want to do so as it's not really solving a problem

**Permission / Access Errors when creating**

I can only assume that these are attempts to run in a restricted environment. We're already doing what we can to catch those and output the error message (and try again). The fallback plan is basically https://github.com/mu-editor/mu/issues/693 where we allow users to specify one or more directories via the command line as an option for school admins etc.

As a workaround, now I think about it, the user ought to be able to overwrite the `dirpath` entry in `venv.json` (eg to be `c:/temp/myvenv` and on the next time round, we'll attempt to create a new venv at that position.

**Upgrading Pip**

This is probably where I'm least sure what to do -- or, rather, where to do it. I *think* we probably want to patch the installer build mechanism to specify a version of `virtualenv` which will vendor the version of `pip` which we need (whichever that is). I'll see if I can come to a quick conclusion on which that is.

**Comment by carlosperate** [comment]
> This is probably where I'm least sure what to do -- or, rather, where to do it. I think we probably want to patch the installer build mechanism to specify a version of virtualenv which will vendor the version of pip which we need (whichever that is). I'll see if I can come to a quick conclusion on which that is.

The current issues are related to the user venv pip installations, so figuring out the smallest version of `virtualenv` packing pip v19.0 or v19.3 (https://github.com/mu-editor/mu/issues/1441#issuecomment-814790143) should do the trick.

Looking at the wheels included in the virtualenv (multiple links needed due to the wheels moving around between versions):
- virtualenv 20.0.24: pip v20.1.1
    - https://github.com/gaborbernat/virtualenv/blob/20.0.24/src/virtualenv/seed/wheels/embed/__init__.py#L7
- virtualenv 20.0.0: pip v20.0.2
    - https://github.com/gaborbernat/virtualenv/blob/20.0.0/src/virtualenv/seed/embed/wheels/__init__.py#L3
- virtualenv 16.7.6: pip v19.3
    - https://github.com/gaborbernat/virtualenv/tree/16.7.6/virtualenv_support

The current minimum version virtualenv currently specified in `setup.py` is v16, which pack pip v10:
- https://github.com/mu-editor/mu/commit/73521e159bfeea3e6289beada39f3f703b717a8a#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7
- https://github.com/gaborbernat/virtualenv/tree/16.0.0/virtualenv_support


I think this PR will be enough for this? Or do you need we need something else?

**Comment by carlosperate** [comment]
From https://github.com/mu-editor/mu/issues/1642:

> ```
> Traceback (most recent call last):
>   File "C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 161, in run
>     raise ex
>   File "C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 148, in run
>     venv.ensure_and_create(self.display_text)
>   File "C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 494, in ensure_and_create
>     self.create()
>   File "C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 624, in create
>     self.upgrade_pip()
>   File "C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 671, in upgrade_pip
>     raise VirtualEnvironmentCreateError("Unable to upgrade pip")
> mu.virtual_environment.VirtualEnvironmentCreateError: Unable to upgrade pip
> ```
> 
> log file: [mu.log](https://github.com/mu-editor/mu-editor.github.io/files/6470001/mu.log)


First a `Unable to upgrade pip` followed by a `Cannot create a file when that file already exists` for a `.FAILED` folder:
```
2021-05-12 21:10:17,719 - mu.virtual_environment:379(run_subprocess) DEBUG: Process returned 101; output: Unable to create process using 'C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\python.exe -m pip install --upgrade pip'
2021-05-12 21:10:17,719 - mu.virtual_environment:464(quarantine_failed_venv) ERROR: Unable to quarantine C:\Users\Pieter Viljoen\AppData\Local\python\mu\mu_venv-38-20210512-205841 as C:\Users\Pieter Viljoen\AppData\Local\python\mu\mu_venv-38-20210512-205841.FAILED
Traceback (most recent call last):
  File "C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 494, in ensure_and_create
    self.create()
  File "C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 624, in create
    self.upgrade_pip()
  File "C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 671, in upgrade_pip
    raise VirtualEnvironmentCreateError("Unable to upgrade pip")
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to upgrade pip

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Pieter Viljoen\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 462, in quarantine_failed_venv
    os.rename(self.path, error_dirpath)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Pieter Viljoen\\AppData\\Local\\python\\mu\\mu_venv-38-20210512-205841' -> 'C:\\Users\\Pieter Viljoen\\AppData\\Local\\python\\mu\\mu_venv-38-20210512-205841.FAILED'
```
