### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by wagonis** [mu-editor/mu#1579]
[mu.log](https://github.com/mu-editor/mu/files/6510379/mu.log)
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.4
Locale: en_US
Platform: Windows 10 10.0.19041 AMD64

```
Traceback (most recent call last):
  File "C:\Users\nissim.tushiah\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 161, in run
    raise ex
  File "C:\Users\nissim.tushiah\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 148, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\nissim.tushiah\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 495, in ensure_and_create
    self.ensure()
  File "C:\Users\nissim.tushiah\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 524, in ensure
    self.ensure_key_modules()
  File "C:\Users\nissim.tushiah\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 602, in ensure_key_modules
    raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Failed to import: pgzero

```

**Comment by carlosperate** [comment]
Thank you very much for the repot @wagonis !

I think we might have several crash reports with this similar issue, so I'll merge all of them into #1600.

Your crash is merged in this specific comment and we can continue the conversation over there: https://github.com/mu-editor/mu/issues/1600#issuecomment-849812878

Thanks again!
