### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by muttstang** [mu-editor/mu#1628]
[mu.log](https://github.com/mu-editor/mu/files/6624547/mu.log)

**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.4
Locale: en_US
Platform: Windows 10 10.0.18362 AMD64

```
Traceback (most recent call last):
  File "C:\Users\Eric\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 161, in run
    raise ex
  File "C:\Users\Eric\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 148, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\Eric\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 495, in ensure_and_create
    self.ensure()
  File "C:\Users\Eric\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 524, in ensure
    self.ensure_key_modules()
  File "C:\Users\Eric\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 602, in ensure_key_modules
    raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Failed to import: pgzero

```

**Comment by carlosperate** [comment]
Thanks for the report and the log @muttstang! 

The interesting bit from the log:
```
Installing collected packages: ipython-genutils, wcwidth, traitlets, six, pywin32, parso, tornado, setuptools, pyzmq, python-dateutil, Pygments, pycparser, prompt-toolkit, pickleshare, jupyter-core, jedi, decorator, colorama, backcall, MarkupSafe, jupyter-client, ipython, cffi, Werkzeug, reedsolo, QtPy, pyserial, pygame, numpy, Jinja2, itsdangerous, ipykernel, ecdsa, cryptography, click, bitstring, qtconsole, pgzero, Flask, esptool, adafruit-board-toolkit
  Attempting uninstall: setuptools
    Found existing installation: setuptools 54.1.2
    Uninstalling setuptools-54.1.2:
      Successfully uninstalled setuptools-54.1.2
2021-06-09 06:51:04,872 - mu.virtual_environment:193(run) DEBUG: Process output: Package          Version
---------------- -------
backcall         0.2.0
colorama         0.4.4
decorator        5.0.7
ipython          7.22.0
ipython-genutils 0.2.0
jedi             0.18.0
jupyter-client   6.1.12
jupyter-core     4.7.1
MarkupSafe       1.1.1
parso            0.8.2
pickleshare      0.7.5
pip              21.1.2
prompt-toolkit   3.0.18
pycparser        2.20
Pygments         2.8.1
python-dateutil  2.8.1
pywin32          300
pyzmq            22.0.3
setuptools       56.0.0
six              1.15.0
tornado          6.1
traitlets        5.0.5
wcwidth          0.2.5
wheel            0.36.2
2021-06-09 06:51:04,872 - mu.virtual_environment:680(install_jupyter_kernel) INFO: Installing Jupyter Kernel: mu_venv-38-20210609-064430
```

It looks like this might be the same issue as https://github.com/mu-editor/mu/issues/1600, so I'll merge this ticket over there t keep things tidy: https://github.com/mu-editor/mu/issues/1600#issuecomment-857854055

This issue has already been fixed in the code, and should be working in the next release.

Thanks @muttstang!
