### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ChopOMatic** [mu-editor/mu#1637]
[mu.log](https://github.com/mu-editor/mu/files/6643322/mu.log)
[mu.log](https://github.com/mu-editor/mu/files/6643324/mu.log)

**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.4
Locale: en_US
Platform: Windows 10 10.0.19041 AMD64

```
Traceback (most recent call last):
  File "C:\Users\Jerry Hatchett\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 161, in run
    raise ex
  File "C:\Users\Jerry Hatchett\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 148, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\Jerry Hatchett\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 494, in ensure_and_create
    self.create()
  File "C:\Users\Jerry Hatchett\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 624, in create
    self.upgrade_pip()
  File "C:\Users\Jerry Hatchett\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 671, in upgrade_pip
    raise VirtualEnvironmentCreateError("Unable to upgrade pip")
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to upgrade pip

```

**Comment by carlosperate** [comment]
Thank you very much for the report and the logs @ChopOMatic!

I think this problem is already captured in issue https://github.com/mu-editor/mu/issues/1532, so to keep things tidy I'll merge this over there: https://github.com/mu-editor/mu/issues/1532#issuecomment-860609171
