### ISSUE TITLE
Mu-Editor-Win64-1.1.0b4.msi

### ISSUE THREAD

**Issue by Bobbyg338** [mu-editor/mu#1673]
### What were you trying to do?

install and run

### What steps did you take to trigger the issue?

reinstall

### What did you expect to happen?

to install and run

### What actually happened?

Traceback (most recent call last):
  File "C:\Users\Bob\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 161, in run
    raise ex
  File "C:\Users\Bob\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 148, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\Bob\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 495, in ensure_and_create
    self.ensure()
  File "C:\Users\Bob\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 524, in ensure
    self.ensure_key_modules()
  File "C:\Users\Bob\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 602, in ensure_key_modules
    raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Failed to import: pgzero

### Operating System Version

Windows 10

### Mu Version

Mu-Editor-Win64-1.1.0b4.msi

**Comment by Bobbyg338** [comment]
Try again later
