### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Tasm-Devil** [mu-editor/mu#1740]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.5
Locale: de_DE
Platform: Linux 4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021 x86_64

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mu/app.py", line 161, in run
    raise ex
  File "/usr/local/lib/python3.6/dist-packages/mu/app.py", line 148, in run
    venv.ensure_and_create(self.display_text)
  File "/usr/local/lib/python3.6/dist-packages/mu/virtual_environment.py", line 621, in ensure_and_create
    self.recreate()
  File "/usr/local/lib/python3.6/dist-packages/mu/virtual_environment.py", line 566, in recreate
    self.create()
  File "/usr/local/lib/python3.6/dist-packages/mu/virtual_environment.py", line 768, in create
    self.install_baseline_packages()
  File "/usr/local/lib/python3.6/dist-packages/mu/virtual_environment.py", line 878, in install_baseline_packages
    wheels.download(zipped_wheels_filepath)
  File "/usr/local/lib/python3.6/dist-packages/mu/wheels/__init__.py", line 185, in download
    zip_wheels(zip_filepath, temp_dirpath, logger)
  File "/usr/local/lib/python3.6/dist-packages/mu/wheels/__init__.py", line 156, in zip_wheels
    with zipfile.ZipFile(zip_filepath, "w") as z:
  File "/usr/lib/python3.6/zipfile.py", line 1113, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Keine Berechtigung: '/usr/local/lib/python3.6/dist-packages/mu/wheels/1.1.0.beta.5.zip'

```

**Comment by carlosperate** [comment]
Thanks for the report @Tasm-Devil!
Would you be able to attach the Mu log to this GitHub Issue as well? It'll be really useful to us for debugging. File should be located in: `~/.cache/mu/`

Is it possible mu was pip installed using sudo and now you are trying to run it without it?
