### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by MechaDave** [mu-editor/mu#1852]
Additional Information: I'm running on a Seeed Studio reTerminal, which is a Raspberry Pi Compute 4 based unit.
Despite updating everything, it wants to install and run mu 1.0.2.
```
pi@raspberrypi:~ $ sudo apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done
pi@raspberrypi:~ $ sudo apt-get dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ sudo apt-get install mu-editor
Reading package lists... Done
Building dependency tree       
Reading state information... Done
mu-editor is already the newest version (1.0.2+dfsg-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

```

So I ran the beta pip installer, which gave the error below.
-dave

**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.6
Locale: en_US
Platform: Linux 5.10.63-v7l+ #1457 SMP Tue Sep 28 11:26:14 BST 2021 armv7l

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mu/app.py", line 159, in run
    raise ex
  File "/usr/local/lib/python3.7/dist-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 768, in create
    self.install_baseline_packages()
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 878, in install_baseline_packages
    wheels.download(zipped_wheels_filepath, logger)
  File "/usr/local/lib/python3.7/dist-packages/mu/wheels/__init__.py", line 192, in download
    pip_download(temp_dirpath, logger)
  File "/usr/local/lib/python3.7/dist-packages/mu/wheels/__init__.py", line 130, in pip_download
    "Pip was unable to download %s" % pip_identifier
mu.wheels.WheelsDownloadError: Pip was unable to download pgzero>=1.2.1

```
[mu.log](https://github.com/mu-editor/mu/files/7339442/mu.log)

**Comment by carlosperate** [comment]
Hi @MechaDave,
I was wondering if you were able to resolve this issue? Did you have to use `sudo` to get it running?

**Comment by carlosperate** [comment]
Close due to lack of activity.
