### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Jin-mo** [mu-editor/mu#1855]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.6
Locale: en_US
Platform: Windows 10 10.0.19042 AMD64

```
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 159, in run
    raise ex
  File "C:\Users\DELL\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\DELL\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "C:\Users\DELL\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 767, in create
    self.create_venv()
  File "C:\Users\DELL\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 798, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using C:\Users\DELL\AppData\Local\Programs\Mu Editor\Python\pythonw.exe at C:\Users\DELL\AppData\Local\python\mu\mu_venv-38-20211014-220231
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\DELL\\AppData\\Local\\python\\mu\\mu_venv-38-20211014-220231\\Lib\\site-packages'

Log file: C:\Users\DELL\AppData\Local\python\mu\Logs\mu.log
```

**Comment by carlosperate** [comment]
Thanks for the report @Jin-mo!
Would you be able to attach the Mu log to this GitHub Issue as well? I think you've attached the path to the file, but not the file itself.
You should be able to drag and drop the file to a response to this thread: `C:\Users\DELL\AppData\Local\python\mu\Logs\mu.log`

**Comment by carlosperate** [comment]
Hi @Jin-mo, I suspect this problem might have been caused by #1755.

If you are still experiencing this error, are you able to find the logs and send them to us? File should be located in: `C:\Users\DELL\AppData\Local\python\mu\Logs\mu.log`

**Comment by carlosperate** [comment]
Closing due to a lack of activity and issue likely being already tracked in https://github.com/mu-editor/mu/issues/1755.
