### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by kurtkuhn55** [mu-editor/mu#1858]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.6
Locale: de_DE
Platform: Linux 5.4.0-87-generic #98~18.04.1-Ubuntu SMP Wed Sep 22 10:45:04 UTC 2021 x86_64

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mu/app.py", line 159, in run
    raise ex
  File "/usr/local/lib/python3.6/dist-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/usr/local/lib/python3.6/dist-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/usr/local/lib/python3.6/dist-packages/mu/virtual_environment.py", line 768, in create
    self.install_baseline_packages()
  File "/usr/local/lib/python3.6/dist-packages/mu/virtual_environment.py", line 878, in install_baseline_packages
    wheels.download(zipped_wheels_filepath, logger)
  File "/usr/local/lib/python3.6/dist-packages/mu/wheels/__init__.py", line 192, in download
    pip_download(temp_dirpath, logger)
  File "/usr/local/lib/python3.6/dist-packages/mu/wheels/__init__.py", line 130, in pip_download
    "Pip was unable to download %s" % pip_identifier
mu.wheels.WheelsDownloadError: Pip was unable to download esptool==3.*

```
[mu.log](https://github.com/mu-editor/mu/files/7365657/mu.log)

**Comment by kurtkuhn55** [comment]
Thank you. Issue solved.
