### ISSUE TITLE
Crash Report: unable to download `esptool==3.*`

### ISSUE THREAD

**Issue by cst0** [mu-editor/mu#1859]
Version: 1.1.0.beta.6
Locale: en_US
Platform: Linux 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64

```
Traceback (most recent call last):
  File "/home/cst/ws_micro_ros/venv/lib/python3.6/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/cst/ws_micro_ros/venv/lib/python3.6/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/cst/ws_micro_ros/venv/lib/python3.6/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/cst/ws_micro_ros/venv/lib/python3.6/site-packages/mu/virtual_environment.py", line 768, in create
    self.install_baseline_packages()
  File "/home/cst/ws_micro_ros/venv/lib/python3.6/site-packages/mu/virtual_environment.py", line 878, in install_baseline_packages
    wheels.download(zipped_wheels_filepath, logger)
  File "/home/cst/ws_micro_ros/venv/lib/python3.6/site-packages/mu/wheels/__init__.py", line 192, in download
    pip_download(temp_dirpath, logger)
  File "/home/cst/ws_micro_ros/venv/lib/python3.6/site-packages/mu/wheels/__init__.py", line 130, in pip_download
    "Pip was unable to download %s" % pip_identifier
mu.wheels.WheelsDownloadError: Pip was unable to download esptool==3.*

```

I was able to resolve this by running `pip install esptool==3.*`, which failed because of a
`ModuleNotFoundError: No module named 'setuptools_rust'`. Oddly enough, I could run `pip install setuptools_rust`, then the esptool install worked, and then Mu worked.

So, this is now working for me but I thought I'd drop the info here.

**Comment by carlosperate** [comment]
Thanks for the report and the workaround @cst0!

I think this issue originated because the pip version trying to install Mu was a bit old: https://github.com/mu-editor/mu/issues/1441
