### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by hazelbooth** [mu-editor/mu#1868]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.6
Locale: en_US
Platform: Windows 10 10.0.18362 AMD64

```
d\via_app_data\pip_install\base.py", line 115, in _dist_info
    raise RuntimeError(msg)  # pragma: no cover
RuntimeError: no .dist-info at D:\Users\24819\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\setuptools-58.1.0-py3-none-any, has distutils-precedence.pth, pkg_resources, setuptools, _distutils_hack
Traceback (most recent call last):
  File "C:\Users\24819\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 57, in _install
    installer.install(creator.interpreter.version_info)
  File "C:\Users\24819\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 35, in install
    self._uninstall_previous_version()
  File "C:\Users\24819\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 151, in _uninstall_previous_version
    dist_name = self._dist_info.stem.split("-")[0]
  File "C:\Users\24819\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 115, in _dist_info
    raise RuntimeError(msg)  # pragma: no cover
RuntimeError: no .dist-info at D:\Users\24819\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\pip-21.2.4-py3-none-any, has pip

```

**Comment by tjguk** [comment]
Thanks for reporting, @hazelbooth. Would you be able to attach the log files, please, to see if we've got anything else to go on. (I've got to admit that I've never seen that error before either using Mu or anything else!).

You should be able to find the logs at: `%LOCALAPPDATA%\python\mu\Logs`

Please don't attach them via email: Github seems to drop attachments. Instead, drop them onto the Github web interface and they should get added to this GH Issue. Thanks

**Comment by carlosperate** [comment]
The log has been added in https://github.com/mu-editor/mu/issues/1871, so we can move the conversation over there.
