### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ColumbusG** [mu-editor/mu#1896]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.6
Locale: de_DE
Platform: Windows 10 10.0.22000 AMD64

```
: failed to build image pip because:
Traceback (most recent call last):
  File "C:\Users\Christoph\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 57, in _install
    installer.install(creator.interpreter.version_info)
  File "C:\Users\Christoph\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 39, in install
    self._sync(filename, into)
  File "C:\Users\Christoph\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\copy.py", line 13, in _sync
    copy(src, dst)
  File "C:\Users\Christoph\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\util\path\_sync.py", line 53, in copy
    method(norm(src), norm(dest))
  File "C:\Users\Christoph\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\util\path\_sync.py", line 60, in copytree
    os.makedirs(dest_dir)
  File "C:\Users\Christoph\AppData\Local\Programs\Mu Editor\Python\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'C:\\Users\\Christoph\\AppData\\Local\\python\\mu\\mu_venv-38-20211129-140838\\Lib\\site-packages\\pip\\_vendor\\distlib\\_backport'

```

**Comment by carlosperate** [comment]
Thanks for the report @ColumbusG!
Would you be able to attach the Mu log to this GitHub Issue as well? It'll be really useful to us for debugging. File should be located in: `C:\Users\Christoph\AppData\Local\python\mu\Logs\mu.log`

**Comment by carlosperate** [comment]
Hi @ColumbusG, I suspect this problem might have been caused by #1755.

If you are still experiencing this error, are you able to find the logs and send them to us? File should be located in: C:\Users\Christoph\AppData\Local\python\mu\Logs\mu.log

**Comment by carlosperate** [comment]
Hi @ColumbusG, are you still encountering this error?
