### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by yasenstar** [mu-editor/mu#1905]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.6
Locale: en_US
Platform: Linux 5.4.139-16311-g330b3df0010b #1 SMP PREEMPT Tue Oct 26 20:44:34 PDT 2021 x86_64

```
Traceback (most recent call last):
  File "/home/shadoedragon/.local/lib/python3.7/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/shadoedragon/.local/lib/python3.7/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/shadoedragon/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 621, in ensure_and_create
    self.recreate()
  File "/home/shadoedragon/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 566, in recreate
    self.create()
  File "/home/shadoedragon/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 768, in create
    self.install_baseline_packages()
  File "/home/shadoedragon/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 878, in install_baseline_packages
    wheels.download(zipped_wheels_filepath, logger)
  File "/home/shadoedragon/.local/lib/python3.7/site-packages/mu/wheels/__init__.py", line 192, in download
    pip_download(temp_dirpath, logger)
  File "/home/shadoedragon/.local/lib/python3.7/site-packages/mu/wheels/__init__.py", line 130, in pip_download
    "Pip was unable to download %s" % pip_identifier
mu.wheels.WheelsDownloadError: Pip was unable to download esptool==3.*

```

**Comment by carlosperate** [comment]
Thanks for the report, I'm closing this one in favour of https://github.com/mu-editor/mu/issues/1906 and we can continue the conversation over there.
