### ISSUE TITLE
Issue collection: First pip install fails with exit code 101

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#1926]
Linking here several Crash Reports with the same issue. When it's about to install the first wheel (`backcall` in this case) it encounters an error.

Things they all have in common:
- Fails on the first wheel installation (`backcall`)
- Exit error is 101
- **All user names have a space in it**
    - So this is directly related to https://github.com/mu-editor/mu/issues/1372

With beta.5 and newer the 101 error code is returned at the time it tries to install wheels. In earlier versions there are some other crash reports with the same exit code, more info in: https://github.com/mu-editor/mu/issues/1926#issuecomment-994687363

**Comment by carlosperate** [comment]
- https://github.com/mu-editor/mu/issues/1920

Version: 1.1.0.beta.6
Locale: de_DE
Platform: Windows 10 10.0.19044 AMD64
Log: [mu.log](https://github.com/mu-editor/mu/files/7705029/mu.log)

```
2021-12-13 16:45:15,532 - mu.virtual_environment:868(install_baseline_packages) INFO: Installing baseline packages.
2021-12-13 16:45:15,532 - mu.virtual_environment:875(install_baseline_packages) INFO: Expecting zipped wheels at C:\Users\AMD SYSTEM\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\wheels\1.1.0.beta.6.zip
2021-12-13 16:45:15,610 - mu.virtual_environment:850(install_from_zipped_wheels) INFO: About to install from wheel: backcall-0.2.0-py2.py3-none-any.whl
2021-12-13 16:45:15,610 - mu.virtual_environment:114(run_blocking) INFO: About to run blocking C:\Users\AMD SYSTEM\AppData\Local\python\mu\mu_venv-38-20211213-164514\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\AMDSYS~1\\AppData\\Local\\Temp\\tmptk3x_tdz\\backcall-0.2.0-py2.py3-none-any.whl'] and envvars {}
2021-12-13 16:45:27,940 - mu.virtual_environment:164(wait) DEBUG: Finished: True; exitStatus 0; exitCode 101
2021-12-13 16:45:27,940 - mu.virtual_environment:185(wait) ERROR: Unable to create process using 'C:\Users\AMD SYSTEM\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\AMD SYSTEM\AppData\Local\python\mu\mu_venv-38-20211213-164514\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\AMDSYS~1\AppData\Local\Temp\tmptk3x_tdz\backcall-0.2.0-py2.py3-none-any.whl'
2021-12-13 16:45:27,956 - mu.virtual_environment:643(ensure_and_create) ERROR: Process finished but with error code 101:
Unable to create process using 'C:\Users\AMD SYSTEM\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\AMD SYSTEM\AppData\Local\python\mu\mu_venv-38-20211213-164514\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\AMDSYS~1\AppData\Local\Temp\tmptk3x_tdz\backcall-0.2.0-py2.py3-none-any.whl'
2021-12-13 16:45:27,956 - mu.virtual_environment:540(quarantine_venv) INFO: Quarantined C:\Users\AMD SYSTEM\AppData\Local\python\mu\mu_venv-38-20211213-164514 as C:\Users\AMD SYSTEM\AppData\Local\python\mu\mu_venv-38-20211213-164514.FAILED
2021-12-13 16:45:34,972 - root:171(excepthook) ERROR: Unrecoverable error
Traceback (most recent call last):
  File "C:\Users\AMD SYSTEM\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 159, in run
    raise ex
  File "C:\Users\AMD SYSTEM\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\AMD SYSTEM\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "C:\Users\AMD SYSTEM\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 768, in create
    self.install_baseline_packages()
  File "C:\Users\AMD SYSTEM\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 880, in install_baseline_packages
    self.install_from_zipped_wheels(zipped_wheels_filepath)
  File "C:\Users\AMD SYSTEM\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 855, in install_from_zipped_wheels
    self.pip.install(wheel, deps=False, index=False)
  File "C:\Users\AMD SYSTEM\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 270, in install
    return self.run(
  File "C:\Users\AMD SYSTEM\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 246, in run
    result = self.process.run_blocking(
  File "C:\Users\AMD SYSTEM\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 122, in run_blocking
    return self.wait(wait_for_s=wait_for_s)
  File "C:\Users\AMD SYSTEM\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 186, in wait
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Process finished but with error code 101:
Unable to create process using 'C:\Users\AMD SYSTEM\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\AMD SYSTEM\AppData\Local\python\mu\mu_venv-38-20211213-164514\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\AMDSYS~1\AppData\Local\Temp\tmptk3x_tdz\backcall-0.2.0-py2.py3-none-any.whl'
```

**Comment by carlosperate** [comment]
- https://github.com/mu-editor/mu/issues/1915

Version: 1.1.0.beta.6
Locale: sv_SE
Platform: Windows 10 10.0.19043 AMD64
Log: https://github.com/mu-editor/mu/issues/1915#issue-1076563421

```
2021-12-10 08:56:46,093 - mu.virtual_environment:868(install_baseline_packages) INFO: Installing baseline packages.
2021-12-10 08:56:46,093 - mu.virtual_environment:875(install_baseline_packages) INFO: Expecting zipped wheels at C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\wheels\1.1.0.beta.6.zip
2021-12-10 08:56:46,256 - mu.virtual_environment:850(install_from_zipped_wheels) INFO: About to install from wheel: backcall-0.2.0-py2.py3-none-any.whl
2021-12-10 08:56:46,256 - mu.virtual_environment:114(run_blocking) INFO: About to run blocking C:\Users\Sören Jonsson\AppData\Local\python\mu\mu_venv-38-20211210-085643\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\SRENJO~1\\AppData\\Local\\Temp\\tmp_s76gil0\\backcall-0.2.0-py2.py3-none-any.whl'] and envvars {}
2021-12-10 08:56:59,270 - mu.virtual_environment:164(wait) DEBUG: Finished: True; exitStatus 0; exitCode 101
2021-12-10 08:56:59,271 - mu.virtual_environment:185(wait) ERROR: Unable to create process using 'C:\Users\S�ren Jonsson\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\S�ren Jonsson\AppData\Local\python\mu\mu_venv-38-20211210-085640\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\SRENJO~1\AppData\Local\Temp\tmpe49qhk4g\backcall-0.2.0-py2.py3-none-any.whl'
2021-12-10 08:56:59,341 - mu.virtual_environment:643(ensure_and_create) ERROR: Process finished but with error code 101:
Unable to create process using 'C:\Users\S�ren Jonsson\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\S�ren Jonsson\AppData\Local\python\mu\mu_venv-38-20211210-085640\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\SRENJO~1\AppData\Local\Temp\tmpe49qhk4g\backcall-0.2.0-py2.py3-none-any.whl'
2021-12-10 08:56:59,343 - mu.virtual_environment:540(quarantine_venv) INFO: Quarantined C:\Users\Sören Jonsson\AppData\Local\python\mu\mu_venv-38-20211210-085640 as C:\Users\Sören Jonsson\AppData\Local\python\mu\mu_venv-38-20211210-085640.FAILED
2021-12-10 08:57:06,356 - root:171(excepthook) ERROR: Unrecoverable error
Traceback (most recent call last):
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 159, in run
    raise ex
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 768, in create
    self.install_baseline_packages()
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 880, in install_baseline_packages
    self.install_from_zipped_wheels(zipped_wheels_filepath)
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 855, in install_from_zipped_wheels
    self.pip.install(wheel, deps=False, index=False)
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 270, in install
    return self.run(
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 246, in run
    result = self.process.run_blocking(
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 122, in run_blocking
    return self.wait(wait_for_s=wait_for_s)
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 186, in wait
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Process finished but with error code 101:
Unable to create process using 'C:\Users\S�ren Jonsson\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\S�ren Jonsson\AppData\Local\python\mu\mu_venv-38-20211210-085640\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\SRENJO~1\AppData\Local\Temp\tmpe49qhk4g\backcall-0.2.0-py2.py3-none-any.whl'
2021-12-10 08:57:06,773 - mu.settings:169(save) DEBUG: Saving to C:\Users\Sören Jonsson\AppData\Local\python\mu\session.json
2021-12-10 08:57:06,774 - mu.settings:169(save) DEBUG: Saving to C:\Users\Sören Jonsson\AppData\Local\python\mu\venv.json
2021-12-10 08:57:09,405 - mu.virtual_environment:164(wait) DEBUG: Finished: True; exitStatus 0; exitCode 101
2021-12-10 08:57:09,406 - mu.virtual_environment:185(wait) ERROR: Unable to create process using 'C:\Users\S�ren Jonsson\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\S�ren Jonsson\AppData\Local\python\mu\mu_venv-38-20211210-085643\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\SRENJO~1\AppData\Local\Temp\tmp_s76gil0\backcall-0.2.0-py2.py3-none-any.whl'
2021-12-10 08:57:09,512 - mu.virtual_environment:643(ensure_and_create) ERROR: Process finished but with error code 101:
Unable to create process using 'C:\Users\S�ren Jonsson\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\S�ren Jonsson\AppData\Local\python\mu\mu_venv-38-20211210-085643\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\SRENJO~1\AppData\Local\Temp\tmp_s76gil0\backcall-0.2.0-py2.py3-none-any.whl'
2021-12-10 08:57:09,514 - mu.virtual_environment:540(quarantine_venv) INFO: Quarantined C:\Users\Sören Jonsson\AppData\Local\python\mu\mu_venv-38-20211210-085643 as C:\Users\Sören Jonsson\AppData\Local\python\mu\mu_venv-38-20211210-085643.FAILED
2021-12-10 08:57:16,523 - root:171(excepthook) ERROR: Unrecoverable error
Traceback (most recent call last):
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 159, in run
    raise ex
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 768, in create
    self.install_baseline_packages()
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 880, in install_baseline_packages
    self.install_from_zipped_wheels(zipped_wheels_filepath)
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 855, in install_from_zipped_wheels
    self.pip.install(wheel, deps=False, index=False)
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 270, in install
    return self.run(
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 246, in run
    result = self.process.run_blocking(
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 122, in run_blocking
    return self.wait(wait_for_s=wait_for_s)
  File "C:\Users\Sören Jonsson\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 186, in wait
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Process finished but with error code 101:
Unable to create process using 'C:\Users\S�ren Jonsson\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\S�ren Jonsson\AppData\Local\python\mu\mu_venv-38-20211210-085643\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\SRENJO~1\AppData\Local\Temp\tmp_s76gil0\backcall-0.2.0-py2.py3-none-any.whl'
```

**Comment by carlosperate** [comment]
- https://github.com/mu-editor/mu/issues/1914

Version: 1.1.0.beta.6
Locale: en_GB
Platform: Windows 10 10.0.19044 AMD64
Log: Not available

```

    self.install_from_zipped_wheels(zipped_wheels_filepath)
  File "C:\Users\Gamer 1\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 855, in install_from_zipped_wheels
    self.pip.install(wheel, deps=False, index=False)
  File "C:\Users\Gamer 1\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 270, in install
    return self.run(
  File "C:\Users\Gamer 1\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 246, in run
    result = self.process.run_blocking(
  File "C:\Users\Gamer 1\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 122, in run_blocking
    return self.wait(wait_for_s=wait_for_s)
  File "C:\Users\Gamer 1\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 186, in wait
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Process finished but with error code 101:
Unable to create process using 'C:\Users\Gamer 1\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Gamer 1\AppData\Local\python\mu\mu_venv-38-20211209-201349\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\GAMER1~1\AppData\Local\Temp\tmpoadvgbwf\backcall-0.2.0-py2.py3-none-any.whl'
```

**Comment by carlosperate** [comment]
- https://github.com/mu-editor/mu/issues/1902

Version: 1.1.0.beta.6
Locale: en_US
Platform: Windows 10 10.0.22000 AMD64
Log: Not available

```
File "C:\Users\Suck My Toes Hoe\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 855, in install_from_zipped_wheels
    self.pip.install(wheel, deps=False, index=False)
  File "C:\Users\Suck My Toes Hoe\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 270, in install
    return self.run(
  File "C:\Users\Suck My Toes Hoe\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 246, in run
    result = self.process.run_blocking(
  File "C:\Users\Suck My Toes Hoe\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 122, in run_blocking
    return self.wait(wait_for_s=wait_for_s)
  File "C:\Users\Suck My Toes Hoe\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 186, in wait
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Process finished but with error code 101:
Unable to create process using 'C:\Users\Suck My Toes Hoe\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Suck My Toes Hoe\AppData\Local\python\mu\mu_venv-38-20211203-203209\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\SUCKMY~1\AppData\Local\Temp\tmptwyctmc8\backcall-0.2.0-py2.py3-none-any.whl'
```

**Comment by carlosperate** [comment]
- https://github.com/mu-editor/mu/issues/1895

Version: 1.1.0.beta.6
Locale: en_IN
Platform: Windows 10 10.0.19042 AMD64
Log: [mu.log](https://github.com/mu-editor/mu/files/7592955/mu.log)

```
2021-11-24 10:51:43,611 - mu.virtual_environment:868(install_baseline_packages) INFO: Installing baseline packages.
2021-11-24 10:51:43,611 - mu.virtual_environment:875(install_baseline_packages) INFO: Expecting zipped wheels at C:\Users\Praveen Khot\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\wheels\1.1.0.beta.6.zip
2021-11-24 10:51:43,823 - mu.virtual_environment:850(install_from_zipped_wheels) INFO: About to install from wheel: backcall-0.2.0-py2.py3-none-any.whl
2021-11-24 10:51:43,823 - mu.virtual_environment:114(run_blocking) INFO: About to run blocking C:\Users\Praveen Khot\AppData\Local\python\mu\mu_venv-38-20211124-105142\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\PRAVEE~1\\AppData\\Local\\Temp\\tmp3zm9dhvb\\backcall-0.2.0-py2.py3-none-any.whl'] and envvars {}
2021-11-24 10:51:44,810 - mu.virtual_environment:164(wait) DEBUG: Finished: True; exitStatus 0; exitCode 101
2021-11-24 10:51:44,810 - mu.virtual_environment:185(wait) ERROR: Unable to create process using 'C:\Users\Praveen Khot\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Praveen Khot\AppData\Local\python\mu\mu_venv-38-20211124-105142\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\PRAVEE~1\AppData\Local\Temp\tmp3zm9dhvb\backcall-0.2.0-py2.py3-none-any.whl'
2021-11-24 10:51:44,844 - mu.virtual_environment:643(ensure_and_create) ERROR: Process finished but with error code 101:
Unable to create process using 'C:\Users\Praveen Khot\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Praveen Khot\AppData\Local\python\mu\mu_venv-38-20211124-105142\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\PRAVEE~1\AppData\Local\Temp\tmp3zm9dhvb\backcall-0.2.0-py2.py3-none-any.whl'
2021-11-24 10:51:44,847 - mu.virtual_environment:540(quarantine_venv) INFO: Quarantined C:\Users\Praveen Khot\AppData\Local\python\mu\mu_venv-38-20211124-105142 as C:\Users\Praveen Khot\AppData\Local\python\mu\mu_venv-38-20211124-105142.FAILED
2021-11-24 10:51:51,858 - root:171(excepthook) ERROR: Unrecoverable error
Traceback (most recent call last):
  File "C:\Users\Praveen Khot\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 159, in run
    raise ex
  File "C:\Users\Praveen Khot\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\Praveen Khot\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "C:\Users\Praveen Khot\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 768, in create
    self.install_baseline_packages()
  File "C:\Users\Praveen Khot\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 880, in install_baseline_packages
    self.install_from_zipped_wheels(zipped_wheels_filepath)
  File "C:\Users\Praveen Khot\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 855, in install_from_zipped_wheels
    self.pip.install(wheel, deps=False, index=False)
  File "C:\Users\Praveen Khot\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 270, in install
    return self.run(
  File "C:\Users\Praveen Khot\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 246, in run
    result = self.process.run_blocking(
  File "C:\Users\Praveen Khot\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 122, in run_blocking
    return self.wait(wait_for_s=wait_for_s)
  File "C:\Users\Praveen Khot\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 186, in wait
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Process finished but with error code 101:
Unable to create process using 'C:\Users\Praveen Khot\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Praveen Khot\AppData\Local\python\mu\mu_venv-38-20211124-105142\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\PRAVEE~1\AppData\Local\Temp\tmp3zm9dhvb\backcall-0.2.0-py2.py3-none-any.whl'
```

**Comment by carlosperate** [comment]
- https://github.com/mu-editor/mu/issues/1891

Version: 1.1.0.beta.6
Locale: en_US
Platform: Windows 10 10.0.22000 AMD64
Log: Not available

```
rs\Theophalus Moore\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 855, in install_from_zipped_wheels
    self.pip.install(wheel, deps=False, index=False)
  File "C:\Users\Theophalus Moore\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 270, in install
    return self.run(
  File "C:\Users\Theophalus Moore\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 246, in run
    result = self.process.run_blocking(
  File "C:\Users\Theophalus Moore\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 122, in run_blocking
    return self.wait(wait_for_s=wait_for_s)
  File "C:\Users\Theophalus Moore\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 186, in wait
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Process finished but with error code 101:
Unable to create process using 'C:\Users\Theophalus Moore\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Theophalus Moore\AppData\Local\python\mu\mu_venv-38-20211119-214514\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index "C:\Users\Theophalus Moore\AppData\Local\Temp\tmpk45_eh24\backcall-0.2.0-py2.py3-none-any.whl"'
```

**Comment by carlosperate** [comment]
- https://github.com/mu-editor/mu/issues/1889

Version: 1.1.0.beta.6
Locale: en_US
Platform: Windows 10 10.0.22000 AMD64
Log: [mu.log](https://github.com/mu-editor/mu/files/7551030/mu.log)

```
2021-11-16 17:32:33,472 - mu.virtual_environment:868(install_baseline_packages) INFO: Installing baseline packages.
2021-11-16 17:32:33,472 - mu.virtual_environment:875(install_baseline_packages) INFO: Expecting zipped wheels at C:\Users\Glen Hoshizaki\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\wheels\1.1.0.beta.6.zip
2021-11-16 17:32:33,674 - mu.virtual_environment:850(install_from_zipped_wheels) INFO: About to install from wheel: backcall-0.2.0-py2.py3-none-any.whl
2021-11-16 17:32:33,674 - mu.virtual_environment:114(run_blocking) INFO: About to run blocking C:\Users\Glen Hoshizaki\AppData\Local\python\mu\mu_venv-38-20211116-173231\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\Glen Hoshizaki\\AppData\\Local\\Temp\\tmptkrgbaxr\\backcall-0.2.0-py2.py3-none-any.whl'] and envvars {}
2021-11-16 17:32:34,302 - mu.virtual_environment:164(wait) DEBUG: Finished: True; exitStatus 0; exitCode 101
2021-11-16 17:32:34,303 - mu.virtual_environment:185(wait) ERROR: Unable to create process using 'C:\Users\Glen Hoshizaki\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Glen Hoshizaki\AppData\Local\python\mu\mu_venv-38-20211116-173231\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index "C:\Users\Glen Hoshizaki\AppData\Local\Temp\tmptkrgbaxr\backcall-0.2.0-py2.py3-none-any.whl"'
2021-11-16 17:32:34,337 - mu.virtual_environment:643(ensure_and_create) ERROR: Process finished but with error code 101:
Unable to create process using 'C:\Users\Glen Hoshizaki\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Glen Hoshizaki\AppData\Local\python\mu\mu_venv-38-20211116-173231\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index "C:\Users\Glen Hoshizaki\AppData\Local\Temp\tmptkrgbaxr\backcall-0.2.0-py2.py3-none-any.whl"'
2021-11-16 17:32:34,340 - mu.virtual_environment:540(quarantine_venv) INFO: Quarantined C:\Users\Glen Hoshizaki\AppData\Local\python\mu\mu_venv-38-20211116-173231 as C:\Users\Glen Hoshizaki\AppData\Local\python\mu\mu_venv-38-20211116-173231.FAILED
2021-11-16 17:32:41,360 - root:171(excepthook) ERROR: Unrecoverable error
Traceback (most recent call last):
  File "C:\Users\Glen Hoshizaki\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 159, in run
    raise ex
  File "C:\Users\Glen Hoshizaki\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\Glen Hoshizaki\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "C:\Users\Glen Hoshizaki\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 768, in create
    self.install_baseline_packages()
  File "C:\Users\Glen Hoshizaki\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 880, in install_baseline_packages
    self.install_from_zipped_wheels(zipped_wheels_filepath)
  File "C:\Users\Glen Hoshizaki\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 855, in install_from_zipped_wheels
    self.pip.install(wheel, deps=False, index=False)
  File "C:\Users\Glen Hoshizaki\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 270, in install
    return self.run(
  File "C:\Users\Glen Hoshizaki\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 246, in run
    result = self.process.run_blocking(
  File "C:\Users\Glen Hoshizaki\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 122, in run_blocking
    return self.wait(wait_for_s=wait_for_s)
  File "C:\Users\Glen Hoshizaki\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 186, in wait
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Process finished but with error code 101:
Unable to create process using 'C:\Users\Glen Hoshizaki\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Glen Hoshizaki\AppData\Local\python\mu\mu_venv-38-20211116-173231\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index "C:\Users\Glen Hoshizaki\AppData\Local\Temp\tmptkrgbaxr\backcall-0.2.0-py2.py3-none-any.whl"'
```

**Comment by carlosperate** [comment]
There were more than I realised, so there is not much point to list all of them as above since they all look very similar. I'll just add the rest in a list here:

Captured in the previous responses above:
- https://github.com/mu-editor/mu/issues/1920
- https://github.com/mu-editor/mu/issues/1915
- https://github.com/mu-editor/mu/issues/1914
- https://github.com/mu-editor/mu/issues/1902
- https://github.com/mu-editor/mu/issues/1895
- https://github.com/mu-editor/mu/issues/1891
- https://github.com/mu-editor/mu/issues/1889


The rest:
- https://github.com/mu-editor/mu/issues/1869 
- https://github.com/mu-editor/mu/issues/1857
- https://github.com/mu-editor/mu/issues/1822
- https://github.com/mu-editor/mu/issues/1821
- https://github.com/mu-editor/mu/issues/1819
- https://github.com/mu-editor/mu/issues/1791
- https://github.com/mu-editor/mu/issues/1760
- https://github.com/mu-editor/mu/issues/1737
- https://github.com/mu-editor/mu/issues/1732
- https://github.com/mu-editor/mu/issues/1726
- https://github.com/mu-editor/mu/issues/1724
- https://github.com/mu-editor/mu/issues/1723
- https://github.com/mu-editor/mu/issues/1720
- https://github.com/mu-editor/mu/issues/1719
- https://github.com/mu-editor/mu/issues/1705

**Comment by carlosperate** [comment]
Relate issues or threads online (not an exhaustive search at all):
- https://stackoverflow.com/questions/61641280/python3-8-venv-returned-exit-status-101/62207756
- https://stackoverflow.com/questions/55433197/error-create-python-virtual-environment-win-10
- https://intellij-support.jetbrains.com/hc/en-us/community/posts/360008351699-Scripts-python-exe-Im-ensurepip-upgrade-default-pip-returned-non-zero-exit-status-101-

**Comment by carlosperate** [comment]
@tjguk found this issue in the Python bug tracker: https://bugs.python.org/issue46686

We've been able to replicate these 101 exceptions with Mu in Windows user accounts with a space in it by adding a file with the first word of the username in the `C:\Users\` directory.

For example, for a `test user` account with a `C:\Users\test user\` user folder, creating a `C:\Users\test` file triggers the problem.

**Comment by carlosperate** [comment]
WIP PR: https://github.com/mu-editor/mu/pull/2216

**Comment by carlosperate** [comment]
PR https://github.com/mu-editor/mu/pull/2259 has been merged and the fix will be present in the next Mu release 🎉
