### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#1951]
_Originally posted by @lujo6911 in https://github.com/mu-editor/mu/issues/1949#issuecomment-1000429914_

-----

Same error, my logfile:

```
[fedora-laptop mu-1.1.0-beta.7]$ ./run.py 
QSocketNotifier: Can only be used with threads started with QThread
Traceback (most recent call last):
  File "/home/lujo/Mu/mu-1.1.0-beta.7/mu/app.py", line 159, in run
    raise ex
  File "/home/lujo/Mu/mu-1.1.0-beta.7/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/lujo/Mu/mu-1.1.0-beta.7/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/lujo/Mu/mu-1.1.0-beta.7/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/lujo/Mu/mu-1.1.0-beta.7/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/lujo/.local/share/mu/mu_venv-39-20211223-180215
STDERR: /usr/bin/python3: No module named virtualenv

(python3:16455): GLib-CRITICAL **: 18:02:22.963: g_main_context_pop_thread_default: assertion 'g_queue_peek_head (stack) == context' failed
QObject::~QObject: Timers cannot be stopped from another thread
Opening in existing browser session.
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[16561:16561:0100/000000.276521:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
```
```
[fedora-laptop log]$ cat mu.log 
2021-12-23 18:02:15,379 - root:269(run) INFO: 

-----------------

Starting Mu 1.1.0b7
2021-12-23 18:02:15,379 - root:270(run) INFO: uname_result(system='Linux', node='fedora-laptop', release='5.15.5-100.fc34.x86_64', version='#1 SMP Fri Nov 26 00:52:21 UTC 2021', machine='x86_64')
2021-12-23 18:02:15,382 - root:271(run) INFO: Platform: Linux-5.15.5-100.fc34.x86_64-x86_64-with-glibc2.33
2021-12-23 18:02:15,382 - root:272(run) INFO: Python path: ['/home/lujo/Mu/mu-1.1.0-beta.7', '/usr/lib64/python39.zip', '/usr/lib64/python3.9', '/usr/lib64/python3.9/lib-dynload', '/home/lujo/.local/lib/python3.9/site-packages', '/usr/local/lib/python3.9/site-packages', '/usr/lib64/python3.9/site-packages', '/usr/lib/python3.9/site-packages', '/usr/lib/python3.9/site-packages/IPython/extensions']
2021-12-23 18:02:15,382 - root:273(run) INFO: Language code: en_US
2021-12-23 18:02:15,511 - mu.virtual_environment:585(ensure_and_create) INFO: Added log handler.
2021-12-23 18:02:15,511 - mu.virtual_environment:596(ensure_and_create) DEBUG: Checking virtual environment; attempt #1.
2021-12-23 18:02:15,512 - mu.virtual_environment:616(ensure_and_create) WARNING: Venv created by Mu version 1.1.0.beta.6; Current Mu is version 1.1.0b7
2021-12-23 18:02:15,512 - mu.virtual_environment:922(installed_packages) INFO: Discovering installed third party modules in venv.
2021-12-23 18:02:15,512 - mu.virtual_environment:114(run_blocking) INFO: About to run blocking /home/lujo/.local/share/mu/mu_venv-39-20211223-174821/bin/pip with args ['list', '--disable-pip-version-check'] and envvars {}
2021-12-23 18:02:15,844 - mu.virtual_environment:164(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2021-12-23 18:02:15,845 - mu.virtual_environment:249(run) DEBUG: Process output: Package           Version
----------------- -------
backcall          0.2.0
bitstring         3.1.9
cffi              1.15.0
click             8.0.3
cryptography      35.0.0
decorator         5.1.0
ecdsa             0.17.0
entrypoints       0.3
esptool           3.1
Flask             1.1.2
ipykernel         5.5.6
ipython           7.28.0
ipython-genutils  0.2.0
itsdangerous      2.0.1
jedi              0.18.0
Jinja2            3.0.2
jupyter-client    7.0.6
jupyter-core      4.8.1
MarkupSafe        2.0.1
matplotlib-inline 0.1.3
nest-asyncio      1.5.1
numpy             1.21.2
parso             0.8.2
pexpect           4.8.0
pgzero            1.2.1
pickleshare       0.7.5
pip               21.3
prompt-toolkit    3.0.20
ptyprocess        0.7.0
pycparser         2.20
pygame            2.0.2
Pygments          2.10.0
pyserial          3.5
python-dateutil   2.8.2
pyzmq             22.3.0
setuptools        58.2.0
six               1.16.0
tornado           6.1
traitlets         5.1.0
wcwidth           0.2.5
Werkzeug          2.0.2
wheel             0.37.0
2021-12-23 18:02:15,845 - mu.virtual_environment:931(installed_packages) INFO: []
2021-12-23 18:02:15,847 - mu.virtual_environment:540(quarantine_venv) INFO: Quarantined /home/lujo/.local/share/mu/mu_venv-39-20211223-174821 as /home/lujo/.local/share/mu/mu_venv-39-20211223-174821.SUPERSEDED
2021-12-23 18:02:15,847 - mu.virtual_environment:460(relocate) DEBUG: Relocating to /home/lujo/.local/share/mu/mu_venv-39-20211223-180215
2021-12-23 18:02:15,849 - mu.virtual_environment:476(relocate) DEBUG: Virtual environment set up mu_venv-39-20211223-180215 at /home/lujo/.local/share/mu/mu_venv-39-20211223-180215
2021-12-23 18:02:15,849 - mu.virtual_environment:781(create_venv) INFO: Creating virtualenv: /home/lujo/.local/share/mu/mu_venv-39-20211223-180215
2021-12-23 18:02:15,849 - mu.virtual_environment:782(create_venv) INFO: Virtualenv name: mu_venv-39-20211223-180215
2021-12-23 18:02:15,851 - mu.virtual_environment:429(run_subprocess) INFO: Running ('/usr/bin/python3', '-I', '-m', 'virtualenv', '-p', '/usr/bin/python3', '-q', '/home/lujo/.local/share/mu/mu_venv-39-20211223-180215') with kwargs {'env': {'SHELL': '/bin/bash', 'SESSION_MANAGER': 'local/unix:@/tmp/.ICE-unix/1871,unix/unix:/tmp/.ICE-unix/1871', 'COLORTERM': 'truecolor', 'HISTCONTROL': 'ignoredups', 'XDG_MENU_PREFIX': 'gnome-', 'HOSTNAME': 'fedora-laptop', 'HISTSIZE': '1000', 'JAVA_HOME': '/usr/lib/jvm/java-11-openjdk-11.0.13.0.8-2.fc34.x86_64', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'XMODIFIERS': '@im=ibus', 'DESKTOP_SESSION': 'gnome', 'LC_MONETARY': 'nl_BE.UTF-8', 'EDITOR': '/usr/bin/nano', 'PWD': '/home/lujo/Mu/mu-1.1.0-beta.7', 'LOGNAME': 'lujo', 'XDG_SESSION_DESKTOP': 'gnome', 'XDG_SESSION_TYPE': 'wayland', 'SYSTEMD_EXEC_PID': '1871', 'XAUTHORITY': '/run/user/1000/.mutter-Xwaylandauth.PE56E1', 'GDM_LANG': 'en_US.UTF-8', 'HOME': '/home/lujo', 'USERNAME': 'lujo', 'LC_PAPER': 'nl_BE.UTF-8', 'LANG': 'en_US.UTF-8', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:', 'XDG_CURRENT_DESKTOP': 'GNOME', 'VTE_VERSION': '6402', 'WAYLAND_DISPLAY': 'wayland-0', 'GNOME_TERMINAL_SCREEN': '/org/gnome/Terminal/screen/4d393ddc_42d4_40b8_82c7_9bb369fb821b', 'MOZ_GMP_PATH': '/usr/lib64/mozilla/plugins/gmp-gmpopenh264/system-installed', 'GNOME_SETUP_DISPLAY': ':1', 'XDG_SESSION_CLASS': 'user', 'TERM': 'xterm-256color', 'LESSOPEN': '||/usr/bin/lesspipe.sh %s', 'USER': 'lujo', 'GNOME_TERMINAL_SERVICE': ':1.79', 'DISPLAY': ':0', 'SHLVL': '1', 'QT_IM_MODULE': 'ibus', 'LC_MEASUREMENT': 'nl_BE.UTF-8', 'DESKTOP_AUTOSTART_ID': '105ea5ed071497473b164027598390121100000018710018', 'CLASSPATH': '.:/usr/lib/jvm/java-11-openjdk-11.0.13.0.8-2.fc34.x86_64/lib', 'XDG_RUNTIME_DIR': '/run/user/1000', 'LC_TIME': 'nl_BE.UTF-8', 'which_declare': 'declare -f', 'XDG_DATA_DIRS': '/home/lujo/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/', 'PATH': '/home/lujo/.local/bin:/home/lujo/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/usr/lib/jvm/java-11-openjdk-11.0.13.0.8-2.fc34.x86_64/bin:/usr/lib/jvm/java-11-openjdk-11.0.13.0.8-2.fc34.x86_64/bin:/usr/lib/jvm/java-11-openjdk-11.0.13.0.8-2.fc34.x86_64/bin', 'GDMSESSION': 'gnome', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'MAIL': '/var/spool/mail/lujo', 'LC_NUMERIC': 'nl_BE.UTF-8', 'OLDPWD': '/home/lujo/Mu', 'BASH_FUNC_which%%': '() {  ( alias;\n eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot "$@"\n}', '_': './run.py', 'QT_API': 'pyqt5', 'QT_AUTO_SCREEN_SCALE_FACTOR': '1', 'QT_MAC_WANTS_LAYER': '1'}}
2021-12-23 18:02:15,885 - mu.virtual_environment:441(run_subprocess) DEBUG: Process returned 1; output: STDERR: /usr/bin/python3: No module named virtualenv
2021-12-23 18:02:15,886 - mu.virtual_environment:643(ensure_and_create) ERROR: Unable to create a virtual environment using /usr/bin/python3 at /home/lujo/.local/share/mu/mu_venv-39-20211223-180215
STDERR: /usr/bin/python3: No module named virtualenv
2021-12-23 18:02:15,890 - mu.virtual_environment:536(quarantine_venv) ERROR: Unable to quarantine /home/lujo/.local/share/mu/mu_venv-39-20211223-180215 as /home/lujo/.local/share/mu/mu_venv-39-20211223-180215.FAILED
Traceback (most recent call last):
  File "/home/lujo/Mu/mu-1.1.0-beta.7/mu/virtual_environment.py", line 621, in ensure_and_create
    self.recreate()
  File "/home/lujo/Mu/mu-1.1.0-beta.7/mu/virtual_environment.py", line 566, in recreate
    self.create()
  File "/home/lujo/Mu/mu-1.1.0-beta.7/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/lujo/Mu/mu-1.1.0-beta.7/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/lujo/.local/share/mu/mu_venv-39-20211223-180215
STDERR: /usr/bin/python3: No module named virtualenv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lujo/Mu/mu-1.1.0-beta.7/mu/virtual_environment.py", line 534, in quarantine_venv
    os.rename(self.path, error_dirpath)
FileNotFoundError: [Errno 2] No such file or directory: '/home/lujo/.local/share/mu/mu_venv-39-20211223-180215' -> '/home/lujo/.local/share/mu/mu_venv-39-20211223-180215.FAILED'
2021-12-23 18:02:15,893 - mu.virtual_environment:460(relocate) DEBUG: Relocating to /home/lujo/.local/share/mu/mu_venv-39-20211223-180215
2021-12-23 18:02:15,894 - mu.virtual_environment:476(relocate) DEBUG: Virtual environment set up mu_venv-39-20211223-180215 at /home/lujo/.local/share/mu/mu_venv-39-20211223-180215
2021-12-23 18:02:15,894 - mu.virtual_environment:596(ensure_and_create) DEBUG: Checking virtual environment; attempt #2.
2021-12-23 18:02:15,894 - mu.virtual_environment:781(create_venv) INFO: Creating virtualenv: /home/lujo/.local/share/mu/mu_venv-39-20211223-180215
2021-12-23 18:02:15,894 - mu.virtual_environment:782(create_venv) INFO: Virtualenv name: mu_venv-39-20211223-180215
2021-12-23 18:02:15,894 - mu.virtual_environment:429(run_subprocess) INFO: Running ('/usr/bin/python3', '-I', '-m', 'virtualenv', '-p', '/usr/bin/python3', '-q', '/home/lujo/.local/share/mu/mu_venv-39-20211223-180215') with kwargs {'env': {'SHELL': '/bin/bash', 'SESSION_MANAGER': 'local/unix:@/tmp/.ICE-unix/1871,unix/unix:/tmp/.ICE-unix/1871', 'COLORTERM': 'truecolor', 'HISTCONTROL': 'ignoredups', 'XDG_MENU_PREFIX': 'gnome-', 'HOSTNAME': 'fedora-laptop', 'HISTSIZE': '1000', 'JAVA_HOME': '/usr/lib/jvm/java-11-openjdk-11.0.13.0.8-2.fc34.x86_64', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'XMODIFIERS': '@im=ibus', 'DESKTOP_SESSION': 'gnome', 'LC_MONETARY': 'nl_BE.UTF-8', 'EDITOR': '/usr/bin/nano', 'PWD': '/home/lujo/Mu/mu-1.1.0-beta.7', 'LOGNAME': 'lujo', 'XDG_SESSION_DESKTOP': 'gnome', 'XDG_SESSION_TYPE': 'wayland', 'SYSTEMD_EXEC_PID': '1871', 'XAUTHORITY': '/run/user/1000/.mutter-Xwaylandauth.PE56E1', 'GDM_LANG': 'en_US.UTF-8', 'HOME': '/home/lujo', 'USERNAME': 'lujo', 'LC_PAPER': 'nl_BE.UTF-8', 'LANG': 'en_US.UTF-8', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:', 'XDG_CURRENT_DESKTOP': 'GNOME', 'VTE_VERSION': '6402', 'WAYLAND_DISPLAY': 'wayland-0', 'GNOME_TERMINAL_SCREEN': '/org/gnome/Terminal/screen/4d393ddc_42d4_40b8_82c7_9bb369fb821b', 'MOZ_GMP_PATH': '/usr/lib64/mozilla/plugins/gmp-gmpopenh264/system-installed', 'GNOME_SETUP_DISPLAY': ':1', 'XDG_SESSION_CLASS': 'user', 'TERM': 'xterm-256color', 'LESSOPEN': '||/usr/bin/lesspipe.sh %s', 'USER': 'lujo', 'GNOME_TERMINAL_SERVICE': ':1.79', 'DISPLAY': ':0', 'SHLVL': '1', 'QT_IM_MODULE': 'ibus', 'LC_MEASUREMENT': 'nl_BE.UTF-8', 'DESKTOP_AUTOSTART_ID': '105ea5ed071497473b164027598390121100000018710018', 'CLASSPATH': '.:/usr/lib/jvm/java-11-openjdk-11.0.13.0.8-2.fc34.x86_64/lib', 'XDG_RUNTIME_DIR': '/run/user/1000', 'LC_TIME': 'nl_BE.UTF-8', 'which_declare': 'declare -f', 'XDG_DATA_DIRS': '/home/lujo/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/', 'PATH': '/home/lujo/.local/bin:/home/lujo/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/usr/lib/jvm/java-11-openjdk-11.0.13.0.8-2.fc34.x86_64/bin:/usr/lib/jvm/java-11-openjdk-11.0.13.0.8-2.fc34.x86_64/bin:/usr/lib/jvm/java-11-openjdk-11.0.13.0.8-2.fc34.x86_64/bin', 'GDMSESSION': 'gnome', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'MAIL': '/var/spool/mail/lujo', 'LC_NUMERIC': 'nl_BE.UTF-8', 'OLDPWD': '/home/lujo/Mu', 'BASH_FUNC_which%%': '() {  ( alias;\n eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot "$@"\n}', '_': './run.py', 'QT_API': 'pyqt5', 'QT_AUTO_SCREEN_SCALE_FACTOR': '1', 'QT_MAC_WANTS_LAYER': '1'}}
2021-12-23 18:02:15,922 - mu.virtual_environment:441(run_subprocess) DEBUG: Process returned 1; output: STDERR: /usr/bin/python3: No module named virtualenv
2021-12-23 18:02:15,922 - mu.virtual_environment:643(ensure_and_create) ERROR: Unable to create a virtual environment using /usr/bin/python3 at /home/lujo/.local/share/mu/mu_venv-39-20211223-180215
STDERR: /usr/bin/python3: No module named virtualenv
2021-12-23 18:02:15,922 - mu.virtual_environment:536(quarantine_venv) ERROR: Unable to quarantine /home/lujo/.local/share/mu/mu_venv-39-20211223-180215 as /home/lujo/.local/share/mu/mu_venv-39-20211223-180215.FAILED
Traceback (most recent call last):
  File "/home/lujo/Mu/mu-1.1.0-beta.7/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/lujo/Mu/mu-1.1.0-beta.7/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/lujo/Mu/mu-1.1.0-beta.7/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/lujo/.local/share/mu/mu_venv-39-20211223-180215
STDERR: /usr/bin/python3: No module named virtualenv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lujo/Mu/mu-1.1.0-beta.7/mu/virtual_environment.py", line 534, in quarantine_venv
    os.rename(self.path, error_dirpath)
FileNotFoundError: [Errno 2] No such file or directory: '/home/lujo/.local/share/mu/mu_venv-39-20211223-180215' -> '/home/lujo/.local/share/mu/mu_venv-39-20211223-180215.FAILED'
2021-12-23 18:02:22,928 - root:171(excepthook) ERROR: Unrecoverable error
Traceback (most recent call last):
  File "/home/lujo/Mu/mu-1.1.0-beta.7/mu/app.py", line 159, in run
    raise ex
  File "/home/lujo/Mu/mu-1.1.0-beta.7/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/lujo/Mu/mu-1.1.0-beta.7/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/lujo/Mu/mu-1.1.0-beta.7/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/lujo/Mu/mu-1.1.0-beta.7/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/lujo/.local/share/mu/mu_venv-39-20211223-180215
STDERR: /usr/bin/python3: No module named virtualenv
2021-12-23 18:02:22,961 - mu.settings:169(save) DEBUG: Saving to /home/lujo/.local/share/mu/session.json
2021-12-23 18:02:22,961 - mu.settings:169(save) DEBUG: Saving to /home/lujo/.local/share/mu/venv.json
[lujo@fedora-laptop log]$
```
-----

_Originally posted by @lujo6911 in https://github.com/mu-editor/mu/issues/1949#issuecomment-1000429914_

**Comment by carlosperate** [comment]
Then I asked:

**Comment by carlosperate** [comment]
_Originally posted by @lujo in https://github.com/mu-editor/mu/issues/1949#issuecomment-1000532424_

----

No, tried to install with pip on dnf upgraded Fedora 33 and Fedora 34:

[ocalhost ~]$ python3 -m pip install mu-editor==1.1.0b7
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement mu-editor==1.1.0b7 (from versions: 1.0.0b12, 1.0.0b13, 1.0.0b14, 1.0.0b15, 1.0.0b16, 1.0.0b17, 1.0.0rc1, 1.0.0, 1.0.1, 1.0.2, 1.0.3)
ERROR: No matching distribution found for mu-editor==1.1.0b7
[ocalhost ~]$ 

So downloaded tar file from github:
https://github.com/mu-editor/mu/archive/refs/tags/1.1.0-beta.7.tar.gz
Did gunzip, tar xvf, cd to mu-1.1.0-beta.7, ran ./run.py. With the log file
I posted as result. Did not run setup.py.

Because, this worked for 1.1.0-beta.6.

virtualenv already was installed (for beta.6):
[localhost]$ pip3 list | grep virtualenv
virtualenv                        20.10.0

Reinstalled  virtualenv
[localhost]$ sudo python3 -m pip uninstall virtualenv
[localhost]$ sudo python3 -m pip install virtualenv

Same virtualenv version.
Same error log file when ./run.py.

----

_Originally posted by @lujo in https://github.com/mu-editor/mu/issues/1949#issuecomment-1000532424_

**Comment by carlosperate** [comment]
Thanks @lujo @lujo6911! I assume both account belong to the same person?

I've separated the threads to avoid parallel conversations getting hard to follow.


> No, tried to install with pip on dnf upgraded Fedora 33 and Fedora 34:
> 
> ```
> [ocalhost ~]$ python3 -m pip install mu-editor==1.1.0b7
> Defaulting to user installation because normal site-packages is not writeable
> ERROR: Could not find a version that satisfies the requirement mu-editor==1.1.0b7 (from versions: 1.0.0b12, 1.0.0b13, 1.0.0b14, 1.0.0b15, 1.0.0b16, 1.0.0b17, 1.0.0rc1, 1.0.0, 1.0.1, 1.0.2, 1.0.3)
> ERROR: No matching distribution found for mu-editor==1.1.0b7
> [ocalhost ~]$ 
> ```

I think the problem in this case is that maybe you are using Python 3.9? Mu at the moment only works with versions 3.5 to 3.8.




> So downloaded tar file from github: https://github.com/mu-editor/mu/archive/refs/tags/1.1.0-beta.7.tar.gz Did gunzip, tar xvf, cd to mu-1.1.0-beta.7, ran ./run.py. With the log file I posted as result. Did not run setup.py.
> 
> Because, this worked for 1.1.0-beta.6.

To do this you would still need to install Mu as a package (or at the very least the Mu dependencies).

The instructions to install from source can be found here: https://mu.readthedocs.io/en/latest/setup.html
