### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Omni-K** [mu-editor/mu#1963]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: ru_RU
Platform: Linux 5.8.0-63-generic #71-Ubuntu SMP Tue Jul 13 15:59:12 UTC 2021 x86_64

```
Traceback (most recent call last):
  File "/home/nikolay/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/nikolay/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/nikolay/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/nikolay/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/nikolay/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/nikolay/.local/share/mu/mu_venv-38-20211229-193958
STDERR: /usr/bin/python3: No module named virtualenv

```

**Comment by carlosperate** [comment]
Thanks for the report @Omni-K, I believe this is the issue you are encountering: https://github.com/mu-editor/mu/issues/1954

The easiest workaround at the moment might be to install `python3-virtualenv` (assuming you are on Debian/Ubuntu) from your package manager.

Another way would be to install Mu in a virtual environment, as that is always highly encouraged. Alternatively I would personally recommend to use pipx, as it's great for installing Python-based applications like Mu: https://pypa.github.io/pipx/
pipx will automatically install Python applications in their own isolated virtual environment, and add the executable to the PATH so that it can be easily launched like any other app.
