### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by poste01** [mu-editor/mu#1971]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: en_US
Platform: Linux 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64

```
Traceback (most recent call last):
  File "/home/gkp/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/gkp/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/gkp/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/gkp/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/gkp/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/gkp/.local/share/mu/mu_venv-38-20220104-170140
STDERR: /usr/bin/python3: No module named virtualenv

```

**Comment by carlosperate** [comment]
Hi @poste01, I believe this issue you might be experiencing is this one: #1954

If you still have this problem, could you install the python3-virtualenv apt package (assuming Debina/Ubuntu) and try again? Hopefully that should work.
