### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by jstrother** [mu-editor/mu#1981]
Version: 1.1.0b7
Locale: en_US
[mu.log](https://github.com/mu-editor/mu/files/7885699/mu.log)

Platform: Linux 5.13.0-25-generic #26~20.04.1-Ubuntu SMP Fri Jan 7 16:27:40 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/home/jim/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/jim/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/jim/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/jim/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/jim/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/jim/.local/share/mu/mu_venv-38-20220117-200748
STDERR: /usr/bin/python3: No module named virtualenv

```

Further info:
First time downloading and using. Attempted to open using `python3 -m mu`

**Comment by carlosperate** [comment]
Hi @jstrother,

Thanks for the report and the log!
I believe this might be the issue you are encountering: #1954

The main workaround at the moment would be to install the python3-virtualenv package using apt and hopefully that should fix it.
