### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Ottokarder** [mu-editor/mu#1987]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: de_DE
Platform: Windows 10 10.0.19043 AMD64

```
-20220118-202411\\Lib\\site-packages\\pip\\_internal\\commands\\uninstall.py'
Traceback (most recent call last):
  File "C:\Users\miche\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 57, in _install
    installer.install(creator.interpreter.version_info)
  File "C:\Users\miche\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 39, in install
    self._sync(filename, into)
  File "C:\Users\miche\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\copy.py", line 13, in _sync
    copy(src, dst)
  File "C:\Users\miche\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\util\path\_sync.py", line 53, in copy
    method(norm(src), norm(dest))
  File "C:\Users\miche\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\util\path\_sync.py", line 60, in copytree
    os.makedirs(dest_dir)
  File "C:\Users\miche\AppData\Local\Programs\Mu Editor\Python\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'C:\\Users\\miche\\AppData\\Local\\python\\mu\\mu_venv-38-20220118-202411\\Lib\\site-pa
[mu.log](https://github.com/mu-editor/mu/files/7891846/mu.log)
ckages\\setuptools\\command'

``
[mu.log](https://github.com/mu-editor/mu/files/7891849/mu.log)
`

**Comment by carlosperate** [comment]
Hi @Ottokarder, thanks for the report and the log!

I believe the issue you've encountered is this one: #1755

Could you try opening Mu again, but ensuring it is only executed once?
I believe the problem arises when the Mu application is opened more than once when running for the first time. It might take a some time for the first launch to complete, but after that it should be much quicker.
