### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by 7s26** [mu-editor/mu#1989]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: en_GB
Platform: Linux 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/home/art/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/art/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/art/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/art/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/art/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/art/.local/share/mu/mu_venv-38-20220119-122714
STDERR: /usr/bin/python3: No module named virtualenv

```

**Comment by carlosperate** [comment]
Hi @7s26,

Thanks for the report!
I believe this might be the issue you are encountering: #1954

The easiest workaround at the moment would be to install the python3-virtualenv package using apt, and hopefully that should fix it.

You can also install Mu in a virtual environment and that should work much better.
Alternatively I would personally would recommend to use pipx, as it's great for installing Python-based applications: https://pypa.github.io/pipx/
pipx will automatically install Python applications in their own isolated virtual environment, and add the executable to the PATH so that it can be easily launched like any other app.
