### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Jrboss653** [mu-editor/mu#1992]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: en_US
Platform: Linux 5.10.17-v7l+ #1414 SMP Fri Apr 30 13:20:47 BST 2021 armv7l

```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/pi/.local/lib/python3.7/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/pi/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/pi/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/pi/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 805, in create_venv
    % (sys.executable, self.path, compact(output))
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/pi/.local/share/mu/mu_venv-37-20220116-152258
STDERR: /usr/bin/python3: No module named virtualenv

```

**Comment by carlosperate** [comment]
Hi @Jrboss653 

Thanks for the report!
I believe this might be the issue you are encountering: #1954

The easiest workaround at the moment would be to install the python3-virtualenv package using apt, and hopefully that should fix it.

You can also install Mu in a virtual environment and that should work much better.
Alternatively I would personally recommend to use pipx, as it's great for installing Python-based applications: https://pypa.github.io/pipx/
pipx will automatically install Python applications in their own isolated virtual environment, and add the executable to the PATH so that it can be easily launched like any other app.
