### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by rob0621** [mu-editor/mu#2001]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: en_US
Platform: Linux 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l

```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/pi/.local/lib/python3.7/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/pi/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/pi/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/pi/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 805, in create_venv
    % (sys.executable, self.path, compact(output))
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/pi/.local/share/mu/mu_venv-37-20220122-151225
STDERR: /usr/bin/python3: No module named virtualenv

```

**Comment by carlosperate** [comment]
Thanks for the report!
I'll closing this one in favour of https://github.com/mu-editor/mu/issues/2002, which has a log.
