### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by rob0621** [mu-editor/mu#2002]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: en_US
Platform: Linux 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l

```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/pi/.local/lib/python3.7/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/pi/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/pi/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/pi/.local/lib/python3.7/site-packages/mu/virtual_environment.py", line 805, in create_venv
    % (sys.executable, self.path, compact(output))
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/pi/.local/share/mu/mu_venv-37-20220122-152701
STDERR: /usr/bin/python3: No module named virtualenv

``
[mu.log](https://github.com/mu-editor/mu/files/7919233/mu.log)
`

**Comment by carlosperate** [comment]
Thanks for the report and the log @rob0621!
I believe this might be the issue you are encountering: #1954

The easiest workaround at the moment would be to install the python3-virtualenv package using apt, and hopefully that should fix it.

You can also install Mu in a virtual environment and that should work much better.
Alternatively I would personally recommend to use pipx, as it's great for installing Python-based applications: https://pypa.github.io/pipx/
pipx will automatically install Python applications in their own isolated virtual environment, and add the executable to the PATH so that it can be easily launched like any other app.
