### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by JuBohm** [mu-editor/mu#2004]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: de_DE
Platform: Windows 10 10.0.19043 AMD64

```
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\interface\panes.py", line 760, in on_ls_fail
    self.disable()
  File "C:\Users\Administrator\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\interface\panes.py", line 699, in disable
    self.microbit_fs.setDisabled(True)
RuntimeError: wrapped C/C++ object of type MicroPythonDeviceFileList has been deleted

I have the problem to access on files on ESP32-WROOM  with MuEditor in microPython from Windows. When I work with ESP32 from Raspberry then all is okay.
Thanks for hint in advance
Best regards
Jurgen
[mu.log](https://github.com/mu-editor/mu/files/7932403/mu.log)
n

**Comment by JuBohm** [comment]
I have the problem to access on files on ESP32-WROOM  with MuEditor in microPython from Windows. When I work with ESP32 from Raspberry then all is okay.
Thanks for hint in advance
Best regards
Jurgen
