### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by koussayghanmy** [mu-editor/mu#2013]
[Uploading mu.log…]()
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: en_US
Platform: Windows 10 10.0.22000 AMD64

```
alEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using C:\Users\KOUSSAY\AppData\Local\Programs\Mu Editor\Python\pythonw.exe at C:\Users\KOUSSAY\AppData\Local\python\mu\mu_venv-38-20220128-130630
RuntimeError: failed to build image pip because:
Traceback (most recent call last):
  File "C:\Users\KOUSSAY\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 57, in _install
    installer.install(creator.interpreter.version_info)
  File "C:\Users\KOUSSAY\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 35, in install
    self._uninstall_previous_version()
  File "C:\Users\KOUSSAY\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 151, in _uninstall_previous_version
    dist_name = self._dist_info.stem.split("-")[0]
  File "C:\Users\KOUSSAY\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 115, in _dist_info
    raise RuntimeError(msg)  # pragma: no cover
RuntimeError: no .dist-info at C:\Users\KOUSSAY\AppData\Local\pypa\virtualenv\wheel\3.8\image\1\CopyPipInstall\pip-21.3.1-py3-none-any, has pip

```

**Comment by carlosperate** [comment]
Thanks for the report @koussayghanmy, I'll close this one as the log didn't upload correctly and https://github.com/mu-editor/mu/issues/2012 has the contents in the description.
