### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by rivale** [mu-editor/mu#2022]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: en_GB
Platform: Linux 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mu/app.py", line 159, in run
    raise ex
  File "/usr/local/lib/python3.7/dist-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 621, in ensure_and_create
    self.recreate()
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 566, in recreate
    self.create()
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 772, in create
    self.install_baseline_packages()
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 883, in install_baseline_packages
    wheels.download(zipped_wheels_filepath, logger)
  File "/usr/local/lib/python3.7/dist-packages/mu/wheels/__init__.py", line 176, in download
    zip_wheels(zip_filepath, temp_dirpath, logger)
  File "/usr/local/lib/python3.7/dist-packages/mu/wheels/__init__.py", line 147, in zip_wheels
    with zipfile.ZipFile(zip_filepath, "w") as z:
  File "/usr/lib/python3.7/zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/dist-packages/mu/wheels/1.1.0b7.zip'

```

**Comment by rivale** [comment]
using buster on raspberry pi 4.

**Comment by rivale** [comment]
On Fri, 18 Feb 2022 08:19:04 -0800
Carlos Pereira Atencio ***@***.***> wrote:

> Thanks for the report @rivale!
> 
> If you've install Mu in the system Python then I assume you might
> have needed to use `sudo`, would that be correct? In that case Mu
> will need to be launched with `sudo` as well to create the files it
> needs for the first launch.
> 

hi
thanks for your reply.

Im using Buster os on a pi4
the fault appear at the first run.
Im running from the desktop after installing it with the raspberry pi
reccomended software, i have tried running fro the command line as sudo
enclosed log

and get the same error


thanks

**Comment by carlosperate** [comment]
Hi @rivale, thanks for getting back to us.
If you've repied to this GitHub issue via email it doesn't foward the email attachments to GitHub, so we don't have access to the log.

Could you add the file via the GitHub website? -> https://github.com/mu-editor/mu/issues/2022

Thanks!

**Comment by rivale** [comment]
Hi 
Sorry never did think it would not forward the attachment.

enclosed here

2022-02-19 11:53:21,646 - root:269(run) INFO: 

-----------------

Starting Mu 1.1.0b7
2022-02-19 11:53:21,656 - root:270(run) INFO: uname_result(system='Linux', node='raspberrypi', release='5.10.63-v7l+', version='#1496 SMP Wed Dec 1 15:58:56 GMT 2021', machine='armv7l', processor='')
2022-02-19 11:53:21,658 - root:271(run) INFO: Platform: Linux-5.10.63-v7l+-armv7l-with-debian-10.11
2022-02-19 11:53:21,659 - root:272(run) INFO: Python path: ['/usr/local/bin', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/home/pi/.local/lib/python3.7/site-packages', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3/dist-packages/IPython/extensions']
2022-02-19 11:53:21,659 - root:273(run) INFO: Language code: en_GB
2022-02-19 11:53:22,635 - mu.virtual_environment:585(ensure_and_create) INFO: Added log handler.
2022-02-19 11:53:22,733 - mu.virtual_environment:596(ensure_and_create) DEBUG: Checking virtual environment; attempt #1.
2022-02-19 11:53:22,734 - mu.virtual_environment:619(ensure_and_create) WARNING: Venv created by Mu version -no-version-; Current Mu is version 1.1.0b7
2022-02-19 11:53:22,745 - mu.virtual_environment:922(installed_packages) INFO: Discovering installed third party modules in venv.
2022-02-19 11:53:22,762 - mu.virtual_environment:118(run_blocking) INFO: About to run blocking /home/pi/.local/share/mu/mu_venv-37-20220211-090846/bin/pip with args ['list', '--disable-pip-version-check'] and envvars {}
2022-02-19 11:53:25,819 - mu.virtual_environment:168(wait) DEBUG: Finished: True; exitStatus 0; exitCode 0
2022-02-19 11:53:25,820 - mu.virtual_environment:249(run) DEBUG: Process output: Package    Version
---------- -------
pip        21.3.1
setuptools 60.5.0
wheel      0.37.1
2022-02-19 11:53:25,820 - mu.virtual_environment:931(installed_packages) INFO: ['pip', 'setuptools', 'wheel']
2022-02-19 11:53:25,824 - mu.virtual_environment:540(quarantine_venv) INFO: Quarantined /home/pi/.local/share/mu/mu_venv-37-20220211-090846 as /home/pi/.local/share/mu/mu_venv-37-20220211-090846.SUPERSEDED
2022-02-19 11:53:25,842 - mu.virtual_environment:460(relocate) DEBUG: Relocating to /home/pi/.local/share/mu/mu_venv-37-20220219-115325
2022-02-19 11:53:25,842 - mu.virtual_environment:477(relocate) DEBUG: Virtual environment set up mu_venv-37-20220219-115325 at /home/pi/.local/share/mu/mu_venv-37-20220219-115325
2022-02-19 11:53:25,843 - mu.virtual_environment:781(create_venv) INFO: Creating virtualenv: /home/pi/.local/share/mu/mu_venv-37-20220219-115325
2022-02-19 11:53:25,857 - mu.virtual_environment:782(create_venv) INFO: Virtualenv name: mu_venv-37-20220219-115325
2022-02-19 11:53:25,872 - mu.virtual_environment:429(run_subprocess) INFO: Running ('/usr/bin/python3', '-I', '-m', 'virtualenv', '-p', '/usr/bin/python3', '-q', '/home/pi/.local/share/mu/mu_venv-37-20220219-115325') with kwargs {'env': {'USER': 'pi', 'LANGUAGE': 'en_GB', 'XDG_SEAT': 'seat0', 'TEXTDOMAIN': 'Linux-PAM', 'XDG_SESSION_TYPE': 'x11', 'SSH_AGENT_PID': '788', 'HOME': '/home/pi', 'DESKTOP_SESSION': 'LXDE-pi', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'QT_QPA_PLATFORMTHEME': 'qt5ct', 'LOGNAME': 'pi', 'XDG_SESSION_CLASS': 'user', 'XDG_SESSION_ID': '1', 'SAL_USE_VCLPLUGIN': 'gtk3', 'PATH': '/home/pi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/snap/bin', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'XDG_RUNTIME_DIR': '/run/user/1000', 'XDG_MENU_PREFIX': 'lxde-pi-', 'DISPLAY': ':0.0', 'LANG': 'en_GB', 'XDG_SESSION_DESKTOP': 'lightdm-xsession', 'XAUTHORITY': '/home/pi/.Xauthority', 'XDG_CONFIG_HOME': '/home/pi/.config', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm/data/pi', 'SSH_AUTH_SOCK': '/tmp/ssh-wp0moteuxDBF/agent.756', 'SHELL': '/bin/bash', 'GDMSESSION': 'lightdm-xsession', 'NO_AT_BRIDGE': '1', 'GPG_AGENT_INFO': '/run/user/1000/gnupg/S.gpg-agent:0:1', 'XDG_VTNR': '7', 'LC_ALL': 'en_GB', 'PWD': '/home/pi', 'XDG_DATA_DIRS': '/usr/share/fkms:/usr/local/share:/usr/share/raspi-ui-overrides:/usr/share:/usr/share/gdm:/var/lib/menu-xdg', 'XDG_CURRENT_DESKTOP': 'LXDE', '_LXSESSION_PID': '756', 'XDG_CONFIG_DIRS': '/etc/xdg', 'DESKTOP_STARTUP_ID': 'lxpanel-835-raspberrypi-mu-editor-2_TIME387102', 'QT_API': 'pyqt5', 'QT_AUTO_SCREEN_SCALE_FACTOR': '1', 'QT_MAC_WANTS_LAYER': '1'}}
2022-02-19 11:53:28,489 - mu.virtual_environment:444(run_subprocess) DEBUG: Process returned 0; output: 
2022-02-19 11:53:28,490 - mu.virtual_environment:800(create_venv) INFO: Created virtual environment using /usr/bin/python3 at /home/pi/.local/share/mu/mu_venv-37-20220219-115325
2022-02-19 11:53:28,512 - mu.virtual_environment:873(install_baseline_packages) INFO: Installing baseline packages.
2022-02-19 11:53:28,512 - mu.virtual_environment:880(install_baseline_packages) INFO: Expecting zipped wheels at /usr/local/lib/python3.7/dist-packages/mu/wheels/1.1.0b7.zip
2022-02-19 11:53:28,523 - mu.virtual_environment:882(install_baseline_packages) WARNING: No zipped wheels found; downloading...
2022-02-19 11:53:28,524 - mu.virtual_environment:165(download) INFO: Downloading wheels to /usr/local/lib/python3.7/dist-packages/mu/wheels/1.1.0b7.zip
2022-02-19 11:53:28,525 - mu.virtual_environment:67(remove_dist_files) INFO: Removing wheel/sdist files from /usr/local/lib/python3.7/dist-packages/mu/wheels
2022-02-19 11:53:28,562 - mu.virtual_environment:84(pip_download) INFO: Running pip download for pgzero / pgzero>=1.2.1 / []
2022-02-19 11:54:09,164 - mu.virtual_environment:103(pip_download) DEBUG: Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Looking in links: /tmp/tmp1v67blj_
Collecting pgzero>=1.2.1
  Using cached https://files.pythonhosted.org/packages/2c/66/bc46c203802d47fa30a6caa92d13392274bcbebbb9ffcd0c5ed8030b3611/pgzero-1.2.1-py3-none-any.whl
  Saved /tmp/tmp1v67blj_/pgzero-1.2.1-py3-none-any.whl
Collecting numpy (from pgzero>=1.2.1)
  Using cached https://files.pythonhosted.org/packages/c2/a8/a924a09492bdfee8c2ec3094d0a13f2799800b4fdc9c890738aeeb12c72e/numpy-1.21.5.zip
  Saved /tmp/tmp1v67blj_/numpy-1.21.5.zip
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
Collecting pygame~=2.0 (from pgzero>=1.2.1)
  Using cached https://www.piwheels.org/simple/pygame/pygame-2.1.2-cp37-cp37m-linux_armv7l.whl
  Saved /tmp/tmp1v67blj_/pygame-2.1.2-cp37-cp37m-linux_armv7l.whl
Successfully downloaded pgzero numpy pygame
2022-02-19 11:54:09,165 - mu.virtual_environment:84(pip_download) INFO: Running pip download for flask / flask==1.1.2 / []
2022-02-19 11:54:16,792 - mu.virtual_environment:103(pip_download) DEBUG: Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Looking in links: /tmp/tmp1v67blj_
Collecting flask==1.1.2
  Using cached https://files.pythonhosted.org/packages/f2/28/2a03252dfb9ebf377f40fba6a7841b47083260bf8bd8e737b0c6952df83f/Flask-1.1.2-py2.py3-none-any.whl
  Saved /tmp/tmp1v67blj_/Flask-1.1.2-py2.py3-none-any.whl
Collecting itsdangerous>=0.24 (from flask==1.1.2)
  Downloading https://files.pythonhosted.org/packages/53/f8/64d2488f48332f33a6dbfe2f19d7bde7d750d9cb182b4b37c02eadec33d3/itsdangerous-2.1.0-py3-none-any.whl
  Saved /tmp/tmp1v67blj_/itsdangerous-2.1.0-py3-none-any.whl
Collecting Jinja2>=2.10.1 (from flask==1.1.2)
  Using cached https://files.pythonhosted.org/packages/20/9a/e5d9ec41927401e41aea8af6d16e78b5e612bca4699d417f646a9610a076/Jinja2-3.0.3-py3-none-any.whl
  Saved /tmp/tmp1v67blj_/Jinja2-3.0.3-py3-none-any.whl
Collecting Werkzeug>=0.15 (from flask==1.1.2)
  Using cached https://files.pythonhosted.org/packages/f4/f3/22afbdb20cc4654b10c98043414a14057cd27fdba9d4ae61cea596000ba2/Werkzeug-2.0.3-py3-none-any.whl
  Saved /tmp/tmp1v67blj_/Werkzeug-2.0.3-py3-none-any.whl
Collecting click>=5.1 (from flask==1.1.2)
  Downloading https://files.pythonhosted.org/packages/4a/a8/0b2ced25639fb20cc1c9784de90a8c25f9504a7f18cd8b5397bd61696d7d/click-8.0.4-py3-none-any.whl (97kB)
  Saved /tmp/tmp1v67blj_/click-8.0.4-py3-none-any.whl
Collecting MarkupSafe>=2.0 (from Jinja2>=2.10.1->flask==1.1.2)
  Downloading https://www.piwheels.org/simple/markupsafe/MarkupSafe-2.1.0-cp37-cp37m-linux_armv7l.whl
  Saved /tmp/tmp1v67blj_/MarkupSafe-2.1.0-cp37-cp37m-linux_armv7l.whl
Collecting importlib-metadata; python_version < "3.8" (from click>=5.1->flask==1.1.2)
  Downloading https://files.pythonhosted.org/packages/f9/5f/8f5e198c94a04163fc2e1c425d3963197d59b631614db52bc02b11ee4cff/importlib_metadata-4.11.1-py3-none-any.whl
  Saved /tmp/tmp1v67blj_/importlib_metadata-4.11.1-py3-none-any.whl
Collecting typing-extensions>=3.6.4; python_version < "3.8" (from importlib-metadata; python_version < "3.8"->click>=5.1->flask==1.1.2)
  Downloading https://files.pythonhosted.org/packages/45/6b/44f7f8f1e110027cf88956b59f2fad776cca7e1704396d043f89effd3a0e/typing_extensions-4.1.1-py3-none-any.whl
  Saved /tmp/tmp1v67blj_/typing_extensions-4.1.1-py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata; python_version < "3.8"->click>=5.1->flask==1.1.2)
  Using cached https://files.pythonhosted.org/packages/52/c5/df7953fe6065185af5956265e3b16f13c2826c2b1ba23d43154f3af453bc/zipp-3.7.0-py3-none-any.whl
  Saved /tmp/tmp1v67blj_/zipp-3.7.0-py3-none-any.whl
Successfully downloaded flask itsdangerous Jinja2 Werkzeug click MarkupSafe importlib-metadata typing-extensions zipp
2022-02-19 11:54:16,793 - mu.virtual_environment:84(pip_download) INFO: Running pip download for ipykernel / ipykernel>=4.1,<6 / []
2022-02-19 11:54:42,537 - mu.virtual_environment:103(pip_download) DEBUG: Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Looking in links: /tmp/tmp1v67blj_
Collecting ipykernel<6,>=4.1
  Using cached https://files.pythonhosted.org/packages/e9/ad/9101e0ab5e84dd117462bb3a1379d31728a849b6886458452e3d97dc6bba/ipykernel-5.5.6-py3-none-any.whl
  Saved /tmp/tmp1v67blj_/ipykernel-5.5.6-py3-none-any.whl
Collecting tornado>=4.2 (from ipykernel<6,>=4.1)
  Using cached https://www.piwheels.org/simple/tornado/tornado-6.1-cp37-cp37m-linux_armv7l.whl
  Saved /tmp/tmp1v67blj_/tornado-6.1-cp37-cp37m-linux_armv7l.whl
Collecting ipython>=5.0.0 (from ipykernel<6,>=4.1)
  Using cached https://files.pythonhosted.org/packages/b8/b4/4d6c2753effd9c4e0d93fad9a3827760eaecec8331fe550f5d49e22cce89/ipython-7.31.1-py3-none-any.whl
  Saved /tmp/tmp1v67blj_/ipython-7.31.1-py3-none-any.whl
Collecting jupyter-client (from ipykernel<6,>=4.1)
  Using cached https://files.pythonhosted.org/packages/56/a7/f4d3790ce7bb925d3ffe299244501a264f23ee7ec401914f7d788881ea31/jupyter_client-7.1.2-py3-none-any.whl
  Saved /tmp/tmp1v67blj_/jupyter_client-7.1.2-py3-none-any.whl
Collecting ipython-genutils (from ipykernel<6,>=4.1)
  Using cached https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
  Saved /tmp/tmp1v67blj_/ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting traitlets>=4.1.0 (from ipykernel<6,>=4.1)
  Using cached https://files.pythonhosted.org/packages/37/46/be8a3c030bd3673f4800fa7f46eda972dfa2990089a51ec5dd0a26ed33e9/traitlets-5.1.1-py3-none-any.whl
  Saved /tmp/tmp1v67blj_/traitlets-5.1.1-py3-none-any.whl
Collecting pygments (from ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached https://files.pythonhosted.org/packages/1d/17/ed4d2df187995561b28f1073df24137cb750e12f9879d291cc8ab67c65d2/Pygments-2.11.2-py3-none-any.whl
  Saved /tmp/tmp1v67blj_/Pygments-2.11.2-py3-none-any.whl
Collecting decorator (from ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached https://files.pythonhosted.org/packages/d5/50/83c593b07763e1161326b3b8c6686f0f4b0f24d5526546bee538c89837d6/decorator-5.1.1-py3-none-any.whl
  Saved /tmp/tmp1v67blj_/decorator-5.1.1-py3-none-any.whl
Collecting jedi>=0.16 (from ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached https://files.pythonhosted.org/packages/b3/0e/836f12ec50075161e365131f13f5758451645af75c2becf61c6351ecec39/jedi-0.18.1-py2.py3-none-any.whl
  Saved /tmp/tmp1v67blj_/jedi-0.18.1-py2.py3-none-any.whl
Collecting backcall (from ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached https://files.pythonhosted.org/packages/4c/1c/ff6546b6c12603d8dd1070aa3c3d273ad4c07f5771689a7b69a550e8c951/backcall-0.2.0-py2.py3-none-any.whl
  Saved /tmp/tmp1v67blj_/backcall-0.2.0-py2.py3-none-any.whl
Collecting setuptools>=18.5 (from ipython>=5.0.0->ipykernel<6,>=4.1)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/3b/02/8d4d27b1cacaac2d129a27d17a22d92a2a5eedcb7817d4ed8ab0d4daf5c4/setuptools-60.9.3-py3-none-any.whl (1.1MB)
  Saved /tmp/tmp1v67blj_/setuptools-60.9.3-py3-none-any.whl
Collecting pexpect>4.3; sys_platform != "win32" (from ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached https://files.pythonhosted.org/packages/39/7b/88dbb785881c28a102619d46423cb853b46dbccc70d3ac362d99773a78ce/pexpect-4.8.0-py2.py3-none-any.whl
  Saved /tmp/tmp1v67blj_/pexpect-4.8.0-py2.py3-none-any.whl
Collecting matplotlib-inline (from ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached https://files.pythonhosted.org/packages/a6/2d/2230afd570c70074e80fd06857ba2bdc5f10c055bd9125665fe276fadb67/matplotlib_inline-0.1.3-py3-none-any.whl
  Saved /tmp/tmp1v67blj_/matplotlib_inline-0.1.3-py3-none-any.whl
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 (from ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached https://files.pythonhosted.org/packages/00/e4/beb2fad0bec554a011b321d0f6b99981f9171c0b05d03a6948e45ac8a5be/prompt_toolkit-3.0.28-py3-none-any.whl
  Saved /tmp/tmp1v67blj_/prompt_toolkit-3.0.28-py3-none-any.whl
Collecting pickleshare (from ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl
  Saved /tmp/tmp1v67blj_/pickleshare-0.7.5-py2.py3-none-any.whl
Collecting pyzmq>=13 (from jupyter-client->ipykernel<6,>=4.1)
  Using cached https://www.piwheels.org/simple/pyzmq/pyzmq-22.3.0-cp37-cp37m-linux_armv7l.whl
  Saved /tmp/tmp1v67blj_/pyzmq-22.3.0-cp37-cp37m-linux_armv7l.whl
Collecting python-dateutil>=2.1 (from jupyter-client->ipykernel<6,>=4.1)
  Using cached https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl
  Saved /tmp/tmp1v67blj_/python_dateutil-2.8.2-py2.py3-none-any.whl
Collecting entrypoints (from jupyter-client->ipykernel<6,>=4.1)
  Using cached https://files.pythonhosted.org/packages/35/a8/365059bbcd4572cbc41de17fd5b682be5868b218c3c5479071865cab9078/entrypoints-0.4-py3-none-any.whl
  Saved /tmp/tmp1v67blj_/entrypoints-0.4-py3-none-any.whl
Collecting nest-asyncio>=1.5 (from jupyter-client->ipykernel<6,>=4.1)
  Using cached https://files.pythonhosted.org/packages/06/e0/93453ebab12f5ce9a9ceda2ff71648b30e5f2ce5bba19ee3c95cbd0aaa67/nest_asyncio-1.5.4-py3-none-any.whl
  Saved /tmp/tmp1v67blj_/nest_asyncio-1.5.4-py3-none-any.whl
Collecting jupyter-core>=4.6.0 (from jupyter-client->ipykernel<6,>=4.1)
  Downloading https://files.pythonhosted.org/packages/60/7d/bee50351fe3ff6979e949b9c4c00c556a7a9732ba39b547d07d93450de23/jupyter_core-4.9.2-py3-none-any.whl (86kB)
  Saved /tmp/tmp1v67blj_/jupyter_core-4.9.2-py3-none-any.whl
Collecting parso<0.9.0,>=0.8.0 (from jedi>=0.16->ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached https://files.pythonhosted.org/packages/05/63/8011bd08a4111858f79d2b09aad86638490d62fbf881c44e434a6dfca87b/parso-0.8.3-py2.py3-none-any.whl
  Saved /tmp/tmp1v67blj_/parso-0.8.3-py2.py3-none-any.whl
Collecting ptyprocess>=0.5 (from pexpect>4.3; sys_platform != "win32"->ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached https://files.pythonhosted.org/packages/22/a6/858897256d0deac81a172289110f31629fc4cee19b6f01283303e18c8db3/ptyprocess-0.7.0-py2.py3-none-any.whl
  Saved /tmp/tmp1v67blj_/ptyprocess-0.7.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.0.0->ipykernel<6,>=4.1)
  Using cached https://files.pythonhosted.org/packages/59/7c/e39aca596badaf1b78e8f547c807b04dae603a433d3e7a7e04d67f2ef3e5/wcwidth-0.2.5-py2.py3-none-any.whl
  Saved /tmp/tmp1v67blj_/wcwidth-0.2.5-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil>=2.1->jupyter-client->ipykernel<6,>=4.1)
  Using cached https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
  Saved /tmp/tmp1v67blj_/six-1.16.0-py2.py3-none-any.whl
Successfully downloaded ipykernel tornado ipython jupyter-client ipython-genutils traitlets pygments decorator jedi backcall setuptools pexpect matplotlib-inline prompt-toolkit pickleshare pyzmq python-dateutil entrypoints nest-asyncio jupyter-core parso ptyprocess wcwidth six
2022-02-19 11:54:42,538 - mu.virtual_environment:84(pip_download) INFO: Running pip download for ipython_genutils / ipython_genutils>=0.2.0 / []
2022-02-19 11:54:47,207 - mu.virtual_environment:103(pip_download) DEBUG: Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Looking in links: /tmp/tmp1v67blj_
Collecting ipython_genutils>=0.2.0
  File was already downloaded /tmp/tmp1v67blj_/ipython_genutils-0.2.0-py2.py3-none-any.whl
Successfully downloaded ipython-genutils
2022-02-19 11:54:47,207 - mu.virtual_environment:84(pip_download) INFO: Running pip download for esptool / esptool==3.* / []
2022-02-19 11:54:57,518 - mu.virtual_environment:103(pip_download) DEBUG: Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Looking in links: /tmp/tmp1v67blj_
Collecting esptool==3.*
  Using cached https://www.piwheels.org/simple/esptool/esptool-3.2-py3-none-any.whl
  Saved /tmp/tmp1v67blj_/esptool-3.2-py3-none-any.whl
Collecting cryptography>=2.1.4 (from esptool==3.*)
  Using cached https://www.piwheels.org/simple/cryptography/cryptography-36.0.1-cp37-cp37m-linux_armv7l.whl
  Saved /tmp/tmp1v67blj_/cryptography-36.0.1-cp37-cp37m-linux_armv7l.whl
Collecting reedsolo<=1.5.4,>=1.5.3 (from esptool==3.*)
  Using cached https://www.piwheels.org/simple/reedsolo/reedsolo-1.5.4-cp37-cp37m-linux_armv7l.whl
  Saved /tmp/tmp1v67blj_/reedsolo-1.5.4-cp37-cp37m-linux_armv7l.whl
Collecting ecdsa>=0.16.0 (from esptool==3.*)
  Using cached https://files.pythonhosted.org/packages/4a/b6/b678b080967b2696e9a201c096dc076ad756fb35c87dca4e1d1a13496ff7/ecdsa-0.17.0-py2.py3-none-any.whl
  Saved /tmp/tmp1v67blj_/ecdsa-0.17.0-py2.py3-none-any.whl
Collecting pyserial>=3.0 (from esptool==3.*)
  Using cached https://files.pythonhosted.org/packages/07/bc/587a445451b253b285629263eb51c2d8e9bcea4fc97826266d186f96f558/pyserial-3.5-py2.py3-none-any.whl
  Saved /tmp/tmp1v67blj_/pyserial-3.5-py2.py3-none-any.whl
Collecting bitstring>=3.1.6 (from esptool==3.*)
  Using cached https://files.pythonhosted.org/packages/49/fa/ac153ef3c9668a093f33386edf7a20122962e9142b1105fbe2a4a4262785/bitstring-3.1.9-py3-none-any.whl
  Saved /tmp/tmp1v67blj_/bitstring-3.1.9-py3-none-any.whl
Collecting cffi>=1.12 (from cryptography>=2.1.4->esptool==3.*)
  Using cached https://www.piwheels.org/simple/cffi/cffi-1.15.0-cp37-cp37m-linux_armv7l.whl
  Saved /tmp/tmp1v67blj_/cffi-1.15.0-cp37-cp37m-linux_armv7l.whl
Collecting six>=1.9.0 (from ecdsa>=0.16.0->esptool==3.*)
  File was already downloaded /tmp/tmp1v67blj_/six-1.16.0-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.12->cryptography>=2.1.4->esptool==3.*)
  Using cached https://files.pythonhosted.org/packages/62/d5/5f610ebe421e85889f2e55e33b7f9a6795bd982198517d912eb1c76e1a53/pycparser-2.21-py2.py3-none-any.whl
  Saved /tmp/tmp1v67blj_/pycparser-2.21-py2.py3-none-any.whl
Successfully downloaded esptool cryptography reedsolo ecdsa pyserial bitstring cffi six pycparser
2022-02-19 11:54:57,520 - mu.virtual_environment:122(convert_sdists_to_wheels) INFO: Building wheel for /tmp/tmp1v67blj_/numpy-1.21.5.zip
2022-02-19 12:02:53,802 - mu.virtual_environment:137(convert_sdists_to_wheels) DEBUG: Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmp1v67blj_/numpy-1.21.5.zip
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
Building wheels for collected packages: numpy
  Running setup.py bdist_wheel for numpy: started
  Running setup.py bdist_wheel for numpy: still running...
  Running setup.py bdist_wheel for numpy: still running...
  Running setup.py bdist_wheel for numpy: still running...
  Running setup.py bdist_wheel for numpy: still running...
  Running setup.py bdist_wheel for numpy: still running...
  Running setup.py bdist_wheel for numpy: still running...
  Running setup.py bdist_wheel for numpy: still running...
  Running setup.py bdist_wheel for numpy: finished with status 'done'
  Stored in directory: /tmp/tmp1v67blj_
Successfully built numpy
2022-02-19 12:02:53,809 - mu.virtual_environment:146(zip_wheels) INFO: Building zip /usr/local/lib/python3.7/dist-packages/mu/wheels/1.1.0b7.zip from wheels in /tmp/tmp1v67blj_
2022-02-19 12:03:00,899 - root:171(excepthook) ERROR: Unrecoverable error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mu/app.py", line 159, in run
    raise ex
  File "/usr/local/lib/python3.7/dist-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 621, in ensure_and_create
    self.recreate()
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 566, in recreate
    self.create()
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 772, in create
    self.install_baseline_packages()
  File "/usr/local/lib/python3.7/dist-packages/mu/virtual_environment.py", line 883, in install_baseline_packages
    wheels.download(zipped_wheels_filepath, logger)
  File "/usr/local/lib/python3.7/dist-packages/mu/wheels/__init__.py", line 176, in download
    zip_wheels(zip_filepath, temp_dirpath, logger)
  File "/usr/local/lib/python3.7/dist-packages/mu/wheels/__init__.py", line 147, in zip_wheels
    with zipfile.ZipFile(zip_filepath, "w") as z:
  File "/usr/lib/python3.7/zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/dist-packages/mu/wheels/1.1.0b7.zip'
2022-02-19 12:03:06,057 - mu.settings:169(save) DEBUG: Saving to /home/pi/.local/share/mu/session.json
2022-02-19 12:03:06,059 - mu.settings:169(save) DEBUG: Saving to /home/pi/.local/share/mu/venv.json

**Comment by carlosperate** [comment]
Hi @rivale,

Are you sure mu was launched with `sudo` when that log was generated? The main error is not having permissions to right a file into the distribution site packages.

To be fair, it's not recommended to install Mu in the system Python, as that can affect packages used by other applications or the OS.

Could you try uninstalling mu using pip and then installing with the `--user` flag? `pip install mu-editor --user`.

**Comment by rivale** [comment]
Hi 
 Thanks for your reply.

I dont know what is going on, but i have installed bulleye os and mu is installing and working properly v1.03, but it does not seem to work on v2 of the microbit.

I think my version on of buster os  maybe corrupted, will try to reload it and let you know.

Thanks for your help.

 #Valerio
