### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by paddy-onlfait** [mu-editor/mu#2025]
Error launching mu-editor:
The module virtualenv was successfully install with: pip3 install virtualenv
virtualenv==20.13.0

**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: fr_CH
Platform: Linux 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/home/onlfait/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/onlfait/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/onlfait/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/onlfait/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/onlfait/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/onlfait/.local/share/mu/mu_venv-38-20220204-111210
STDERR: /usr/bin/python3: No module named virtualenv

```
[mu.log](https://github.com/mu-editor/mu/files/8001961/mu.log)

**Comment by carlosperate** [comment]
Thanks for the report @paddy-onlfait!

I believe your issue might be this one: https://github.com/mu-editor/mu/issues/1954#issuecomment-1001258055

Current workarounds:
- Install the python3-virtualenv package using apt (or your OS package manager)
- Install Mu in a virtual environment, as that is the recommended way and it should work much better.
- I would also personally recommend to use pipx, as it's great for installing Python-based applications: https://pypa.github.io/pipx/
    - pipx will automatically install Python applications in their own isolated virtual environment, and add the executable to the PATH so that it can be easily launched like any other app.
