### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by mcavnar6** [mu-editor/mu#2031]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: en_US
Platform: Windows 10 10.0.19044 AMD64

```
Traceback (most recent call last):
  File "C:\Users\max\AppData\Local\Programs\Mu Editor\Python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\max\AppData\Local\Programs\Mu Editor\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\max\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\__main__.py", line 9, in <module>
    main()
  File "C:\Users\max\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\__main__.py", line 5, in main
    run()
  File "C:\Users\max\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 349, in run
    editor.setup(setup_modes(editor, editor_window))
  File "C:\Users\max\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\logic.py", line 817, in setup
    os.makedirs(images_path)
  File "C:\Users\max\AppData\Local\Programs\Mu Editor\Python\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\max\\mu_code\\images'

``
[mu.log](https://github.com/mu-editor/mu/files/8044820/mu.log)
`

**Comment by carlosperate** [comment]
Thanks for the report and attaching the logs!

Looking at the logs all entries are duplicated, which makes me believe that there were perhaps 2 instances of Mu running in parallel and racing each other at creating these directories.

If you try to run Mu again, and ensure it is only running once, do you still get this problem?
