### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by cynovg** [mu-editor/mu#2032]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: ru_RU
Platform: Linux 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/cynovg/.local/share/mu/mu_venv-38-20220211-204821
STDERR: /usr/bin/python3: No module named virtualenv

```

**Comment by cynovg** [comment]
2022-02-11 20:48:21,527 - root:269(run) INFO: 

-----------------

Starting Mu 1.1.0b7
2022-02-11 20:48:21,527 - root:270(run) INFO: uname_result(system='Linux', node='ubuntu-desktop', release='5.4.0-99-generic', version='#112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022', machine='x86_64', processor='x86_64')
2022-02-11 20:48:21,538 - root:271(run) INFO: Platform: Linux-5.4.0-99-generic-x86_64-with-glibc2.29
2022-02-11 20:48:21,538 - root:272(run) INFO: Python path: ['/home/cynovg', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/cynovg/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']
2022-02-11 20:48:21,538 - root:273(run) INFO: Language code: ru_RU
2022-02-11 20:48:21,538 - mu.settings:220(load) WARNING: No settings file found at /home/cynovg/.local/share/mu/settings.json; skipping
2022-02-11 20:48:21,538 - mu.settings:220(load) WARNING: No settings file found at /home/cynovg/.local/share/mu/session.json; skipping
2022-02-11 20:48:21,671 - mu.virtual_environment:585(ensure_and_create) INFO: Added log handler.
2022-02-11 20:48:21,672 - mu.virtual_environment:596(ensure_and_create) DEBUG: Checking virtual environment; attempt #1.
2022-02-11 20:48:21,672 - mu.virtual_environment:781(create_venv) INFO: Creating virtualenv: /home/cynovg/.local/share/mu/mu_venv-38-20220211-204820
2022-02-11 20:48:21,672 - mu.virtual_environment:782(create_venv) INFO: Virtualenv name: mu_venv-38-20220211-204820
2022-02-11 20:48:21,672 - mu.virtual_environment:429(run_subprocess) INFO: Running ('/usr/bin/python3', '-I', '-m', 'virtualenv', '-p', '/usr/bin/python3', '-q', '/home/cynovg/.local/share/mu/mu_venv-38-20220211-204820') with kwargs {'env': {'SHELL': '/bin/bash', 'SESSION_MANAGER': 'local/ubuntu-desktop:@/tmp/.ICE-unix/3969,unix/ubuntu-desktop:/tmp/.ICE-unix/3969', 'QT_ACCESSIBILITY': '1', 'COLORTERM': 'truecolor', 'WG_KEY': '8d6d512ab2061e3710acf09114e74661', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/etc/xdg', 'XDG_MENU_PREFIX': 'gnome-', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'LANGUAGE': 'ru:en', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'LC_ADDRESS': 'ru_RU.UTF-8', 'GNOME_SHELL_SESSION_MODE': 'ubuntu', 'LC_NAME': 'ru_RU.UTF-8', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'WGMODE': 'dev', 'XMODIFIERS': '@im=ibus', 'DESKTOP_SESSION': 'ubuntu', 'LC_MONETARY': 'ru_RU.UTF-8', 'SSH_AGENT_PID': '3939', 'GTK_MODULES': 'gail:atk-bridge', 'PWD': '/home/cynovg', 'LOGNAME': 'cynovg', 'XDG_SESSION_DESKTOP': 'ubuntu', 'XDG_SESSION_TYPE': 'x11', 'GPG_AGENT_INFO': '/run/user/1000/gnupg/S.gpg-agent:0:1', 'XAUTHORITY': '/run/user/1000/gdm/Xauthority', 'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG', 'WINDOWPATH': '2', 'HOME': '/home/cynovg', 'USERNAME': 'cynovg', 'IM_CONFIG_PHASE': '1', 'LC_PAPER': 'ru_RU.UTF-8', 'LANG': 'ru_RU.UTF-8', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'XDG_CURRENT_DESKTOP': 'ubuntu:GNOME', 'VTE_VERSION': '6003', 'GNOME_TERMINAL_SCREEN': '/org/gnome/Terminal/screen/4d0f2f85_0ebe_4cfd_8564_c22434884ab6', 'INVOCATION_ID': '3784a8bddd2c453090cfc77f282378ff', 'MANAGERPID': '3767', 'GJS_DEBUG_OUTPUT': 'stderr', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'XDG_SESSION_CLASS': 'user', 'TERM': 'xterm-256color', 'LC_IDENTIFICATION': 'ru_RU.UTF-8', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'LIBVIRT_DEFAULT_URI': 'qemu:///system', 'USER': 'cynovg', 'GNOME_TERMINAL_SERVICE': ':1.81', 'DISPLAY': ':1', 'SHLVL': '1', 'LC_TELEPHONE': 'ru_RU.UTF-8', 'QT_IM_MODULE': 'ibus', 'LC_MEASUREMENT': 'ru_RU.UTF-8', 'PAPERSIZE': 'a4', 'XDG_RUNTIME_DIR': '/run/user/1000', 'LC_TIME': 'ru_RU.UTF-8', 'JOURNAL_STREAM': '9:66090', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop', 'PATH': '/home/cynovg/.cargo/bin:/home/cynovg/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/cynovg/.komodoide/12.0/XRE/state:/home/cynovg/.local/bin:/home/cynovg/.local/bin', 'GDMSESSION': 'ubuntu', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'LC_NUMERIC': 'ru_RU.UTF-8', '_': '/usr/bin/python3', 'QT_API': 'pyqt5', 'QT_AUTO_SCREEN_SCALE_FACTOR': '1', 'QT_MAC_WANTS_LAYER': '1'}}
2022-02-11 20:48:21,695 - mu.virtual_environment:441(run_subprocess) DEBUG: Process returned 1; output: STDERR: /usr/bin/python3: No module named virtualenv
2022-02-11 20:48:21,696 - mu.virtual_environment:643(ensure_and_create) ERROR: Unable to create a virtual environment using /usr/bin/python3 at /home/cynovg/.local/share/mu/mu_venv-38-20220211-204820
STDERR: /usr/bin/python3: No module named virtualenv
2022-02-11 20:48:21,696 - mu.virtual_environment:536(quarantine_venv) ERROR: Unable to quarantine /home/cynovg/.local/share/mu/mu_venv-38-20220211-204820 as /home/cynovg/.local/share/mu/mu_venv-38-20220211-204820.FAILED
Traceback (most recent call last):
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/cynovg/.local/share/mu/mu_venv-38-20220211-204820
STDERR: /usr/bin/python3: No module named virtualenv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 534, in quarantine_venv
    os.rename(self.path, error_dirpath)
FileNotFoundError: [Errno 2] Нет такого файла или каталога: '/home/cynovg/.local/share/mu/mu_venv-38-20220211-204820' -> '/home/cynovg/.local/share/mu/mu_venv-38-20220211-204820.FAILED'
2022-02-11 20:48:21,696 - mu.virtual_environment:460(relocate) DEBUG: Relocating to /home/cynovg/.local/share/mu/mu_venv-38-20220211-204821
2022-02-11 20:48:21,696 - mu.virtual_environment:476(relocate) DEBUG: Virtual environment set up mu_venv-38-20220211-204821 at /home/cynovg/.local/share/mu/mu_venv-38-20220211-204821
2022-02-11 20:48:21,696 - mu.virtual_environment:596(ensure_and_create) DEBUG: Checking virtual environment; attempt #2.
2022-02-11 20:48:21,696 - mu.virtual_environment:781(create_venv) INFO: Creating virtualenv: /home/cynovg/.local/share/mu/mu_venv-38-20220211-204821
2022-02-11 20:48:21,696 - mu.virtual_environment:782(create_venv) INFO: Virtualenv name: mu_venv-38-20220211-204821
2022-02-11 20:48:21,697 - mu.virtual_environment:429(run_subprocess) INFO: Running ('/usr/bin/python3', '-I', '-m', 'virtualenv', '-p', '/usr/bin/python3', '-q', '/home/cynovg/.local/share/mu/mu_venv-38-20220211-204821') with kwargs {'env': {'SHELL': '/bin/bash', 'SESSION_MANAGER': 'local/ubuntu-desktop:@/tmp/.ICE-unix/3969,unix/ubuntu-desktop:/tmp/.ICE-unix/3969', 'QT_ACCESSIBILITY': '1', 'COLORTERM': 'truecolor', 'WG_KEY': '8d6d512ab2061e3710acf09114e74661', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/etc/xdg', 'XDG_MENU_PREFIX': 'gnome-', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'LANGUAGE': 'ru:en', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'LC_ADDRESS': 'ru_RU.UTF-8', 'GNOME_SHELL_SESSION_MODE': 'ubuntu', 'LC_NAME': 'ru_RU.UTF-8', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'WGMODE': 'dev', 'XMODIFIERS': '@im=ibus', 'DESKTOP_SESSION': 'ubuntu', 'LC_MONETARY': 'ru_RU.UTF-8', 'SSH_AGENT_PID': '3939', 'GTK_MODULES': 'gail:atk-bridge', 'PWD': '/home/cynovg', 'LOGNAME': 'cynovg', 'XDG_SESSION_DESKTOP': 'ubuntu', 'XDG_SESSION_TYPE': 'x11', 'GPG_AGENT_INFO': '/run/user/1000/gnupg/S.gpg-agent:0:1', 'XAUTHORITY': '/run/user/1000/gdm/Xauthority', 'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG', 'WINDOWPATH': '2', 'HOME': '/home/cynovg', 'USERNAME': 'cynovg', 'IM_CONFIG_PHASE': '1', 'LC_PAPER': 'ru_RU.UTF-8', 'LANG': 'ru_RU.UTF-8', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'XDG_CURRENT_DESKTOP': 'ubuntu:GNOME', 'VTE_VERSION': '6003', 'GNOME_TERMINAL_SCREEN': '/org/gnome/Terminal/screen/4d0f2f85_0ebe_4cfd_8564_c22434884ab6', 'INVOCATION_ID': '3784a8bddd2c453090cfc77f282378ff', 'MANAGERPID': '3767', 'GJS_DEBUG_OUTPUT': 'stderr', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'XDG_SESSION_CLASS': 'user', 'TERM': 'xterm-256color', 'LC_IDENTIFICATION': 'ru_RU.UTF-8', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'LIBVIRT_DEFAULT_URI': 'qemu:///system', 'USER': 'cynovg', 'GNOME_TERMINAL_SERVICE': ':1.81', 'DISPLAY': ':1', 'SHLVL': '1', 'LC_TELEPHONE': 'ru_RU.UTF-8', 'QT_IM_MODULE': 'ibus', 'LC_MEASUREMENT': 'ru_RU.UTF-8', 'PAPERSIZE': 'a4', 'XDG_RUNTIME_DIR': '/run/user/1000', 'LC_TIME': 'ru_RU.UTF-8', 'JOURNAL_STREAM': '9:66090', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop', 'PATH': '/home/cynovg/.cargo/bin:/home/cynovg/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/cynovg/.komodoide/12.0/XRE/state:/home/cynovg/.local/bin:/home/cynovg/.local/bin', 'GDMSESSION': 'ubuntu', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'LC_NUMERIC': 'ru_RU.UTF-8', '_': '/usr/bin/python3', 'QT_API': 'pyqt5', 'QT_AUTO_SCREEN_SCALE_FACTOR': '1', 'QT_MAC_WANTS_LAYER': '1'}}
2022-02-11 20:48:21,716 - mu.virtual_environment:441(run_subprocess) DEBUG: Process returned 1; output: STDERR: /usr/bin/python3: No module named virtualenv
2022-02-11 20:48:21,716 - mu.virtual_environment:643(ensure_and_create) ERROR: Unable to create a virtual environment using /usr/bin/python3 at /home/cynovg/.local/share/mu/mu_venv-38-20220211-204821
STDERR: /usr/bin/python3: No module named virtualenv
2022-02-11 20:48:21,716 - mu.virtual_environment:536(quarantine_venv) ERROR: Unable to quarantine /home/cynovg/.local/share/mu/mu_venv-38-20220211-204821 as /home/cynovg/.local/share/mu/mu_venv-38-20220211-204821.FAILED
Traceback (most recent call last):
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/cynovg/.local/share/mu/mu_venv-38-20220211-204821
STDERR: /usr/bin/python3: No module named virtualenv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 534, in quarantine_venv
    os.rename(self.path, error_dirpath)
FileNotFoundError: [Errno 2] Нет такого файла или каталога: '/home/cynovg/.local/share/mu/mu_venv-38-20220211-204821' -> '/home/cynovg/.local/share/mu/mu_venv-38-20220211-204821.FAILED'
2022-02-11 20:48:28,724 - root:171(excepthook) ERROR: Unrecoverable error
Traceback (most recent call last):
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/cynovg/.local/share/mu/mu_venv-38-20220211-204821
STDERR: /usr/bin/python3: No module named virtualenv
2022-02-11 20:48:29,021 - mu.settings:169(save) DEBUG: Saving to /home/cynovg/.local/share/mu/session.json
2022-02-11 20:48:29,021 - mu.settings:184(save) ERROR: Unable to write settings to /home/cynovg/.local/share/mu/session.json:
{}
Traceback (most recent call last):
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/settings.py", line 181, in save
    with open(saving_to_filepath, "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] Нет такого файла или каталога: '/home/cynovg/.local/share/mu/session.json'
2022-02-11 20:48:29,022 - mu.settings:169(save) DEBUG: Saving to /home/cynovg/.local/share/mu/venv.json
2022-02-11 20:48:29,022 - mu.settings:184(save) ERROR: Unable to write settings to /home/cynovg/.local/share/mu/venv.json:
{
  "dirpath": "/home/cynovg/.local/share/mu/mu_venv-38-20220211-204821"
}
Traceback (most recent call last):
  File "/home/cynovg/.local/lib/python3.8/site-packages/mu/settings.py", line 181, in save
    with open(saving_to_filepath, "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] Нет такого файла или каталога: '/home/cynovg/.local/share/mu/venv.json'
