### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by parkyc42** [mu-editor/mu#2037]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: en_US
Platform: Windows 10 10.0.19043 AMD64

```
Traceback (most recent call last):
  File "C:\Users\LORIN\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\modes\base.py", line 165, in <lambda>
    remaining_task = lambda commands=remainder: self.execute(commands)
  File "C:\Users\LORIN\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\modes\base.py", line 163, in execute
    self.write(command)
  File "C:\Users\LORIN\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\modes\base.py", line 149, in write
    self.serial.write(data)
AttributeError: 'NoneType' object has no attribute 'write'

# I am new to programing and Github.  It says to attach a log file at the top.  I'm sorry, but I don't know how to do that.
```

**Comment by carlosperate** [comment]
Thanks for the report @parkyc42!
The log file should be located in: `C:\Users\LORIN\AppData\Local\python\mu\Logs\mu.log`
You can drag and drop the file into a response of this GitHub issue thread.
