### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Henderson3** [mu-editor/mu#2048]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.2
Locale: en_US
Platform: Linux 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/home/arthur/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 550, in ensure_key_modules
    subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/arthur/.local/share/mu/mu_venv-38-20220219-181828/bin/python', '-c', 'import pgzero']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arthur/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 441, in ensure_and_create
    self.ensure()
  File "/home/arthur/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 471, in ensure
    self.ensure_key_modules()
  File "/home/arthur/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 559, in ensure_key_modules
    raise VirtualEnvironmentError(message)
mu.virtual_environment.VirtualEnvironmentError: Failed to import: pgzero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arthur/.local/lib/python3.8/site-packages/mu/app.py", line 162, in run
    raise ex
  File "/home/arthur/.local/lib/python3.8/site-packages/mu/app.py", line 149, in run
    venv.ensure_and_create(self.display_text)
  File "/home/arthur/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 449, in ensure_and_create
    self.create()
  File "/home/arthur/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 596, in create
    self.install_baseline_packages()
  File "/home/arthur/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 649, in install_baseline_packages
    wheels.download()
  File "/home/arthur/.local/lib/python3.8/site-packages/mu/wheels/__init__.py", line 82, in download
    process = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'download', '--destination-directory', '/home/arthur/.local/lib/python3.8/site-packages/mu/wheels', 'git+https://github.com/mu-editor/pgzero.git@mu-wheel']' returned non-zero exit status 1.

```

**Comment by carlosperate** [comment]
Hi @Henderson3,

Mu 1.1.0.beta.2 is a very old release, if you update to the latest version this issue should be resolved.
