### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by GarthElliott** [mu-editor/mu#2049]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: en_CA
Platform: Linux 4.16.18-galliumos #1 SMP PREEMPT Sun Jun 23 04:14:45 UTC 2019 x86_64

```
Traceback (most recent call last):
  File "/home/garth/.local/lib/python3.6/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/garth/.local/lib/python3.6/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/garth/.local/lib/python3.6/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/garth/.local/lib/python3.6/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/garth/.local/lib/python3.6/site-packages/mu/virtual_environment.py", line 805, in create_venv
    % (sys.executable, self.path, compact(output))
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/garth/.local/share/mu/mu_venv-36-20220220-174335
STDERR: /usr/bin/python3: No module named virtualenv

```

**Comment by carlosperate** [comment]
Thanks for the report @GarthElliott.

I believe this issue might be https://github.com/mu-editor/mu/issues/1954#issuecomment-1001258055.

Possible workarounds: 
- Install the python3-virtualenv package using apt (or your OS package manager)
- Install Mu in a virtual environment, as that is the recommended way and it should work much better.
- I would also personally recommend to use pipx, as it's great for installing Python-based applications: https://pypa.github.io/pipx/
    - pipx will automatically install Python applications in their own isolated virtual environment, and add the executable to the PATH so that it can be easily launched like any other app.
