### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by 1work1Tester** [mu-editor/mu#2056]
[mu.log](https://github.com/mu-editor/mu/files/8115139/mu.log)
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: en_US
Platform: Linux 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64

```
ckages/mu/app.py", line 159, in run
    raise ex
  File "/home/test/Documents/test_virtualenv/env/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/test/Documents/test_virtualenv/env/lib/python3.8/site-packages/mu/virtual_environment.py", line 627, in ensure_and_create
    self.ensure()
  File "/home/test/Documents/test_virtualenv/env/lib/python3.8/site-packages/mu/virtual_environment.py", line 667, in ensure
    self.ensure_key_modules()
  File "/home/test/Documents/test_virtualenv/env/lib/python3.8/site-packages/mu/virtual_environment.py", line 750, in ensure_key_modules
    raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Failed to import: flask
STDERR: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/test/.local/share/mu/mu_venv-38-20220222-155704/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/home/test/.local/share/mu/mu_venv-38-20220222-155704/lib/python3.8/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/home/test/.local/share/mu/mu_venv-38-20220222-155704/lib/python3.8/site-packages/itsdangerous/__init__.py)

```

**Comment by carlosperate** [comment]
Thanks for the report @1work1Tester, we've identified the issue and created PR https://github.com/mu-editor/mu/pull/2051 to fix it.

Until we release a new version to PyPI you can probably apply the patch manually and then delete the mu/wheels/1.1.0b7.zip to force Mu to download the venv dependencies again.

**Comment by carlosperate** [comment]
A new version with this fix has been released to PyPI 🎉 https://pypi.org/project/mu-editor/1.1.1/

You can be install it via pip and it should now work :)
