### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by salvodnt** [mu-editor/mu#2064]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: it_IT
Platform: Windows 10 10.0.19044 AMD64

```
Traceback (most recent call last):
  File "C:\Users\salva\AppData\Local\Programs\Mu Editor\Python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\salva\AppData\Local\Programs\Mu Editor\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\salva\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\__main__.py", line 9, in <module>
    main()
  File "C:\Users\salva\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\__main__.py", line 5, in main
    run()
  File "C:\Users\salva\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 349, in run
    editor.setup(setup_modes(editor, editor_window))
  File "C:\Users\salva\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\logic.py", line 809, in setup
    os.makedirs(wd)
  File "C:\Users\salva\AppData\Local\Programs\Mu Editor\Python\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Impossibile creare un file, se il file esiste giÃ : 'C:\\Users\\salva\\mu_code'

```

**Comment by carlosperate** [comment]
Thanks for the report @salvodnt!
Would you be able to attach the Mu log to this GitHub Issue as well? It'll be really useful to us for debugging. File should be located in: `C:\Users\salva\AppData\Local\python\mu\Logs\mu.log`
