### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by JohnDH3** [mu-editor/mu#2068]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0b7
Locale: en_US
Platform: Linux 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/home/john/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/john/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/john/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 627, in ensure_and_create
    self.ensure()
  File "/home/john/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 667, in ensure
    self.ensure_key_modules()
  File "/home/john/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 750, in ensure_key_modules
    raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Failed to import: flask
STDERR: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/john/.local/share/mu/mu_venv-38-20220224-214140/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/home/john/.local/share/mu/mu_venv-38-20220224-214140/lib/python3.8/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/home/john/.local/share/mu/mu_venv-38-20220224-214140/lib/python3.8/site-packages/itsdangerous/__init__.py)
/home/john/.cache/mu/log/mu.log
Traceback (most recent call last):
  File "/home/john/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/john/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/john/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 627, in ensure_and_create
    self.ensure()
  File "/home/john/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 667, in ensure
    self.ensure_key_modules()
  File "/home/john/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 750, in ensure_key_modules
    raise VirtualEnvironmentEnsureError(
mu.virtual_environment.VirtualEnvironmentEnsureError: Failed to import: flask
STDERR: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/john/.local/share/mu/mu_venv-38-20220224-214140/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/home/john/.local/share/mu/mu_venv-38-20220224-214140/lib/python3.8/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/home/john/.local/share/mu/mu_venv-38-20220224-214140/lib/python3.8/site-packages/itsdangerous/__init__.py)
```

**Comment by carlosperate** [comment]
Hi @JohnDH3,

Thanks for the report, this issue was resolved in the last release from a couple of days ago. If you update Mu it should work now.
