### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by moof-moof** [mu-editor/mu#2071]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: sv_SE
Platform: Linux 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/home/xneb/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/xneb/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/xneb/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/xneb/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/xneb/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/xneb/.local/share/mu/mu_venv-38-20220225-143322
STDERR: /usr/bin/python3: No module named virtualenv
2022-02-25 14:33:30,056 - mu.settings:169(save) DEBUG: Saving to /home/xneb/.local/share/mu/session.json
2022-02-25 14:33:30,056 - mu.settings:184(save) ERROR: Unable to write settings to /home/xneb/.local/share/mu/session.json:
{}
Traceback (most recent call last):
  File "/home/xneb/.local/lib/python3.8/site-packages/mu/settings.py", line 181, in save
    with open(saving_to_filepath, "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] Filen eller katalogen finns inte: '/home/xneb/.local/share/mu/session.json'
2022-02-25 14:33:30,057 - mu.settings:169(save) DEBUG: Saving to /home/xneb/.local/share/mu/venv.json
2022-02-25 14:33:30,057 - mu.settings:184(save) ERROR: Unable to write settings to /home/xneb/.local/share/mu/venv.json:
{
  "dirpath": "/home/xneb/.local/share/mu/mu_venv-38-20220225-143322"
}
Traceback (most recent call last):
  File "/home/xneb/.local/lib/python3.8/site-packages/mu/settings.py", line 181, in save
    with open(saving_to_filepath, "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] Filen eller katalogen finns inte: '/home/xneb/.local/share/mu/venv.json'

```

**Comment by carlosperate** [comment]
Thanks for the report @moof-moof.

I believe this issue might be https://github.com/mu-editor/mu/issues/1954#issuecomment-1001258055.

Possible workarounds: 
- Install the python3-virtualenv package using apt (or your OS package manager)
- Install Mu in a virtual environment, as that is the recommended way and it should work much better.
- I would also personally recommend to use pipx, as it's great for installing Python-based applications: https://pypa.github.io/pipx/
    - pipx will automatically install Python applications in their own isolated virtual environment, and add the executable to the PATH so that it can be easily launched like any other app.

**Comment by moof-moof** [comment]
No luck installing mu.
First tried a simple `sudo apt-get install mu-editor` which did proceed trying to install but crashed without even showing a window.
Then did `pip3 install mu-editor` which produced the crash log quoted  here.

@carlosperate  Thank you. I'll try your suggestions later.
