### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by XiaoquanTang** [mu-editor/mu#2081]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: zh_CN
Platform: Linux 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/home/xqtang/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/xqtang/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/xqtang/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/xqtang/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/xqtang/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/xqtang/.local/share/mu/mu_venv-38-20220227-114057
STDERR: /usr/bin/python3: No module named virtualenv

```

**Comment by carlosperate** [comment]
Thanks for the report @XiaoquanTang.

I believe this issue might be https://github.com/mu-editor/mu/issues/1954#issuecomment-1001258055.

Possible workarounds: 
- Install the python3-virtualenv package using apt (or your OS package manager)
- Install Mu in a virtual environment, as that is the recommended way and it should work much better.
- I would also personally recommend to use pipx, as it's great for installing Python-based applications: https://pypa.github.io/pipx/
    - pipx will automatically install Python applications in their own isolated virtual environment, and add the executable to the PATH so that it can be easily launched like any other app.
