### ISSUE TITLE
Crash Report - virtualenv not found when python3 invoked with '-I' switch

### ISSUE THREAD

**Issue by travisbgreen** [mu-editor/mu#2085]
Note: commenting out [`-I` in virtual_environment.py](https://github.com/mu-editor/mu/blob/master/mu/virtual_environment.py#L787) caused it to run for me. It seems passing `-I` to python3 causes it to not know where to find virtualenv module. Reference from python3 manpage: `-I     : isolate Python from the user's environment (implies -E and -s)`

Version: 1.1.1
Locale: en_US
Platform: Linux 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/user/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/user/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/user/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/user/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/user/.local/share/mu/mu_venv-38-20220228-174645
STDERR: /usr/bin/python3: No module named virtualenv

```

**Comment by carlosperate** [comment]
Thanks for the report and the investigation @travisbgreen!

We are currently tracking this issue in https://github.com/mu-editor/mu/issues/1954#issuecomment-1001258055.
We need to the `-I` flag to avoid other versions packages not installed as part of Mu being picked up and causing exception and errors. The side effect is that if a user install Mu in the system Python and has the `virtualenv` package installed via package manager it ends up in a different `site-packages` than the rest of the Mu dependencies.

Current options: 
- Install Mu in a virtual environment, as that is the recommended way and it should work much better.
- I would also personally recommend to use pipx, as it's great for installing Python-based applications: https://pypa.github.io/pipx/
    - pipx will automatically install Python applications in their own isolated virtual environment, and add the executable to the PATH so that it can be easily launched like any other app.
