### ISSUE TITLE
Packaged Numpy wheel in macOS installer is only OS X 10.14+ compatible

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#2120]
## Problem

The main Mu dependency restricting macOS compatibility is PyQt5. As we are currently using v5.13, so it should be compatible with macOS Sierra 10.12 and newer: https://doc.qt.io/archives/qt-5.13/macos.html

Currently the Mu installers download a numpy wheel for the user venv as a dependency for pygamezero and qtconsole.

With Python 3.8 in a modern macOS pip will download the latest Numpy which is only compatible wit macOS 10.14 Mojave and newer. So users with older OS versions are seeing errors like this one:

```
2022-03-13 16:03:57,169 - root:171(excepthook) ERROR: Unrecoverable error
Traceback (most recent call last):
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/virtual_environment.py", line 772, in create
    self.install_baseline_packages()
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/virtual_environment.py", line 885, in install_baseline_packages
    self.install_from_zipped_wheels(zipped_wheels_filepath)
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/virtual_environment.py", line 860, in install_from_zipped_wheels
    self.pip.install(wheel, deps=False, index=False)
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/virtual_environment.py", line 270, in install
    return self.run(
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/virtual_environment.py", line 246, in run
    result = self.process.run_blocking(
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/virtual_environment.py", line 122, in run_blocking
    return self.wait(wait_for_s=wait_for_s)
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/virtual_environment.py", line 186, in wait
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Process finished but with error code 1:
ERROR: numpy-1.22.2-cp38-cp38-macosx_10_14_x86_64.whl is not a supported wheel on this platform.
```

## User Workaround

We can delete the packaged wheels included with Mu, which will force Mu to download them again.

To do this run the following command on a terminal (assuming Mu was installed in the Applications folder):

```
rm /Applications/Mu\ Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/wheels/1.1.1.zip
```

Then launch Mu and this time it should work.
If Mu crashes again we would really appreciated if you could submit a new Crash Report letting us know you tried this workaround, as that will help us revole the issue. Thanks!

**Comment by carlosperate** [comment]
Notes:

### Would deleting the wheel zip file inside the Mu installation directory be a possible workaround?

❌

If the wheels zip file is deleted Mu tries to download the latest numpy version from PyPI via pip. As there isn't a wheel available in the latest release it download the source package and tries to build numpy.

### What if we add the `--prefer-binary` flag to the `pip donwload` steps?

❌

Looks like this feature gives wheels preference, going back to older compatible versions with wheels, but if a package doesn't have any wheels, it fails the `pip download` step. So it looks like this flag would never download a source distribution, which currently is needed for Mu build a couple of pure python packages into a wheels.

**Comment by carlosperate** [comment]
Okay, so I think we have two options:
1) make a `requirement.txt`-like full list of pinned dependencies that we know work everywhere
    - This single list could still use environmental markers to adapt some dependencies depending on the platforms
2) Ensure everything installed in the user venv has wheels available and use the `--platform` flag


I think option 1) is a significant change on how the user venv dependencies are picked installed, too much of a change to rush it in the last minute before v1.2.0. Not because the change is large in number of lines, but because it's a different way to specify dependency versions (pinning vs. min version has a lot of pros and cons).

For option 2) the only dependency that has issues with not having wheels in PyPI is `esptool`, and taking in consideration the esptool dependencies have been a headache for a really log time (see https://github.com/mu-editor/mu/issues/1952), I think we can save ourselves some trouble by vendoring the esptool.py script and as part of that reducing the dependency list, which remove some of the most annoying packages to install.


So my proposal is:
- Remove esptool as user venv dependency, pick the single file script from esptool we need and vendor it inside Mu
    - We only use `esptool.py`, which only requires `pyserial`, which is already included
    - All the other dependencies listed for `esptool` are for the other scripts, which we don't need
    - This does change the category of the dependency from being a "user venv dependency" to a "Mu runtime dependency". I think this is okay as esptool is used in the settings window, so it's closer to the "Mu as an app dependency" than "a dependency to run user code"
    - This would also cover: https://github.com/mu-editor/mu/issues/1952
- Add the `--platform` flag to the `pip download` commands from `mu.wheels`
    - We should instrument `mu.wheels` to only add the `--platform` flag when we are packaging Mu, not when the user is running Mu from a pip/pipx/python-source installation

An alternative proposal, which I think it's still worth pursuing, but not for tonight, would be to update Mu so that if installing wheels from the zip file fails, it can try again but this time ignoring the zip file and downloading the wheels again.

**Comment by carlosperate** [comment]
PRs #2352 and #2351 have been created:
- https://github.com/mu-editor/mu/pull/2352
- https://github.com/mu-editor/mu/pull/2351

**Comment by carlosperate** [comment]
This has been fixed with PRs https://github.com/mu-editor/mu/pull/2351 and https://github.com/mu-editor/mu/pull/2352 🎉
