### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by BruceInKonstanz** [mu-editor/mu#2122]
**REMEMBER TO ATTACH YOUR LOG FILE**
Version: 1.1.1
Locale: en_US
Platform: Linux 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64

Installation of mu-editor on Xubuntu 20.04 via "pip3 install mu-editor":
This distro doesn't provide $HOME/.bin or $HOME/.local/bin by default.
After adding $HOME/.local/bin/ to my PATH to let me start mu-editor, I get the crash report shown at bottom.

The file
  /home/bruce1/.local/lib/python3.8/site-packages/mu/virtual_environment.py 
does exist.

Why the VirtualEnvironmentCreateError occurs is not clear.

In any case, 

 $ touch /home/bruce1/.local/share/mu/mu_venv-38-20220315-201448

succeeds.

In case it's relevant, 

 $ dpkg -l | grep libgtk libqt

gives me 
  libgtk-3-0:amd64    3.24.20-0ubuntu1.1
  libqt5core5a:amd64  5.12.8+dfsg-0ubuntu2.1 

```
Traceback (most recent call last):
  File "/home/bruce1/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/bruce1/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/bruce1/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/bruce1/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/bruce1/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/bruce1/.local/share/mu/mu_venv-38-20220315-202826
STDERR: /usr/bin/python3: No module named virtualenv

```

**Comment by carlosperate** [comment]
Thanks for the report @BruceInKonstanz !

I believe this issue might be https://github.com/mu-editor/mu/issues/1954#issuecomment-1001258055.

Possible workarounds: 
- Install the `python3-virtualenv` package using apt (or your OS package manager)
- Install Mu in a virtual environment, as that is the recommended way and it should work much better.
- I would also personally recommend to use pipx, as it's great for installing Python-based applications: https://pypa.github.io/pipx/
    - pipx will automatically install Python applications in their own isolated virtual environment, and add the executable to the PATH so that it can be easily launched like any other app.
