### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by lmcapacho** [mu-editor/mu#2129]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: en_US
Platform: Linux 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/home/lmcapacho/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/lmcapacho/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/lmcapacho/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/lmcapacho/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/lmcapacho/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/lmcapacho/.local/share/mu/mu_venv-38-20220316-172804
STDERR: /usr/bin/python3: No module named virtualenv

```
[mu.log](https://github.com/mu-editor/mu/files/8274886/mu.log)

**Comment by lmcapacho** [comment]
As recommended by @carlosperate in topic #1954, mu-editor works fine on Linux when using pipx to install it. The problem, in this case, is to use an isolated environment with pip.
