### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by adentler1** [mu-editor/mu#2138]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: en_GB
Platform: Linux 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mu/app.py", line 159, in run
    raise ex
  File "/usr/local/lib/python3.8/dist-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/usr/local/lib/python3.8/dist-packages/mu/virtual_environment.py", line 621, in ensure_and_create
    self.recreate()
  File "/usr/local/lib/python3.8/dist-packages/mu/virtual_environment.py", line 566, in recreate
    self.create()
  File "/usr/local/lib/python3.8/dist-packages/mu/virtual_environment.py", line 772, in create
    self.install_baseline_packages()
  File "/usr/local/lib/python3.8/dist-packages/mu/virtual_environment.py", line 883, in install_baseline_packages
    wheels.download(zipped_wheels_filepath, logger)
  File "/usr/local/lib/python3.8/dist-packages/mu/wheels/__init__.py", line 178, in download
    zip_wheels(zip_filepath, temp_dirpath, logger)
  File "/usr/local/lib/python3.8/dist-packages/mu/wheels/__init__.py", line 149, in zip_wheels
    with zipfile.ZipFile(zip_filepath, "w") as z:
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/mu/wheels/1.1.1.zip'

```

**Comment by carlosperate** [comment]
Hi @adentler1, thanks for the report!

Does Mu work if it's launched with `sudo`?
