### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by isaac32767** [mu-editor/mu#2160]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: en_US
Platform: Linux 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/home/isaac/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/isaac/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/isaac/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/isaac/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/isaac/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/isaac/.local/share/mu/mu_venv-38-20220402-173526
STDERR: /usr/bin/python3: No module named virtualenv

```

[mu.log](https://github.com/mu-editor/mu/files/8403586/mu.log)

**Comment by isaac32767** [comment]
OK. Python3 was installed as superuser by apt, while Mu was installed by pip as me. So Mu couldn't find my venv packages. Just needed to install mu as superuser.
