### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by KenMarr** [mu-editor/mu#2171]
**REMEMBER TO ATTACH YOUR LOG FILE**
[mu.log](https://github.com/mu-editor/mu/files/8456963/mu.log)

Version: 1.1.1
Locale: en_US
Platform: Windows 10 10.0.19044 AMD64

```
_zipped_wheels(zipped_wheels_filepath)
  File "C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 860, in install_from_zipped_wheels
    self.pip.install(wheel, deps=False, index=False)
  File "C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 270, in install
    return self.run(
  File "C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 246, in run
    result = self.process.run_blocking(
  File "C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 122, in run_blocking
    return self.wait(wait_for_s=wait_for_s)
  File "C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 186, in wait
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Process finished but with error code 101:
Unable to create process using 'C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Ken Marr\AppData\Local\python\mu\mu_venv-38-20220409-085243\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\Public\Documents\Wondershare\CreatorTemp\tmpdorh6nz2\asttokens-2.0.5-py2.py3-none-any.whl'

```

**Comment by KenMarr** [comment]
[mu.log](https://github.com/mu-editor/mu/files/8456964/mu.log)
-------
2022-04-09 08:52:40,005 - root:269(run) INFO: 

-----------------

Starting Mu 1.1.1
2022-04-09 08:52:40,005 - root:270(run) INFO: uname_result(system='Windows', node='Area-51', release='10', version='10.0.19044', machine='AMD64', processor='Intel64 Family 6 Model 158 Stepping 13, GenuineIntel')
2022-04-09 08:52:40,053 - root:271(run) INFO: Platform: Windows-10-10.0.19044-SP0
2022-04-09 08:52:40,053 - root:272(run) INFO: Python path: ['J:\\_Downloads\\Programming\\Python', 'C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Mu Editor\\Python\\python38.zip', 'C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Mu Editor\\Python\\DLLs', 'C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Mu Editor\\Python\\lib', 'C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Mu Editor\\Python', 'C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Mu Editor\\Python\\lib\\site-packages', 'C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Mu Editor\\Python\\lib\\site-packages\\setuptools-57.4.0-py3.8.egg', 'C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Mu Editor\\Python\\lib\\site-packages\\pip-21.1.3-py3.8.egg', 'C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Mu Editor\\Python\\lib\\site-packages\\win32', 'C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Mu Editor\\Python\\lib\\site-packages\\win32\\lib', 'C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Mu Editor\\Python\\lib\\site-packages\\Pythonwin']
2022-04-09 08:52:40,053 - root:273(run) INFO: Language code: en_US
2022-04-09 08:52:40,053 - mu.settings:220(load) WARNING: No settings file found at C:\Users\Ken Marr\AppData\Local\python\mu\settings.json; skipping
2022-04-09 08:52:40,054 - mu.settings:220(load) WARNING: No settings file found at C:\Users\Ken Marr\AppData\Local\python\mu\session.json; skipping
2022-04-09 08:52:40,388 - mu.virtual_environment:585(ensure_and_create) INFO: Added log handler.
2022-04-09 08:52:40,389 - mu.virtual_environment:596(ensure_and_create) DEBUG: Checking virtual environment; attempt #1.
2022-04-09 08:52:40,610 - mu.virtual_environment:781(create_venv) INFO: Creating virtualenv: C:\Users\Ken Marr\AppData\Local\python\mu\mu_venv-38-20220409-085232
2022-04-09 08:52:40,618 - mu.virtual_environment:782(create_venv) INFO: Virtualenv name: mu_venv-38-20220409-085232
2022-04-09 08:52:40,619 - mu.virtual_environment:429(run_subprocess) INFO: Running ('C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Mu Editor\\Python\\pythonw.exe', '-I', '-m', 'virtualenv', '-p', 'C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Mu Editor\\Python\\pythonw.exe', '-q', 'C:\\Users\\Ken Marr\\AppData\\Local\\python\\mu\\mu_venv-38-20220409-085232') with kwargs {'env': {'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\Ken Marr\\AppData\\Roaming', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'AREA-51', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\Users\\Ken Marr', 'HPSAPRINTERFIRMWARE': '192.168.1.95', 'LOCALAPPDATA': 'C:\\Users\\Ken Marr\\AppData\\Local', 'LOGONSERVER': '\\\\AREA-51', 'NUMBER_OF_PROCESSORS': '16', 'ONEDRIVE': 'C:\\Users\\Ken Marr\\OneDrive', 'ONEDRIVECONSUMER': 'C:\\Users\\Ken Marr\\OneDrive', 'OS': 'Windows_NT', 'PATH': 'C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Mu Editor\\Python\\lib\\site-packages\\PyQt5\\Qt\\bin;C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\;C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Python\\Python39\\;C:\\ActiveTcl\\bin;C:\\Program Files\\Python310\\Scripts\\;C:\\Program Files\\Python310\\;C:\\Program Files\\Eps14\\bin;C:\\texlive\\2019\\bin\\win32;C:\\Python\\;C:\\Python\\Scripts\\;C:\\Program Files\\Perl64\\bin;C:\\Users\\Ken Marr\\AppData\\Roaming\\ActiveState\\bin;C:\\Windows;C:\\Windows\\system32;C:\\Windows\\system32\\wbem;C:\\Windows\\system32\\windowspowershell\\v1.0\\;c:\\windows\\system32\\openssh\\;c:\\program files (x86)\\nvidia corporation\\physx\\common;c:\\program files\\nvidia corporation\\nvidia nvdlisr;c:\\program files\\microsoft vs code\\bin;c:\\program files\\calibre2\\;G:\\texlive\\2019\\bin\\win32;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\dotnet\\;c:\\program files\\microsoft sql server\\client sdk\\odbc\\170\\tools\\binn\\;c:\\program files\\microsoft sql server\\130\\tools\\binn\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\dotnet\\;C:\\Program Files (x86)\\Microsoft SQL Server\\110\\DTS\\Binn\\;C:\\Program Files (x86)\\Windows Kits\\10\\Microsoft Application Virtualization\\Sequencer\\;C:\\Program Files (x86)\\Microsoft SQL Server\\110\\Tools\\Binn\\;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\MinGW\\bin;C:\\Program Files\\Graphviz\\bin;C:\\Program Files\\MiKTeX\\miktex\\bin\\x64\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\MySQL\\MySQL Shell 8.0\\bin\\;C:\\Users\\Ken Marr\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\JetBrains\\PyCharm Professional Edition with Anaconda plugin 2019.3.5\\bin;;C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\MiKTeX\\miktex\\bin\\x64\\;C:\\Program Files\\JetBrains\\PyCharm 2021.3\\bin;', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PL;.WPL;.PY;.PYW', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 158 Stepping 13, GenuineIntel', 'PROCESSOR_LEVEL': '6', 'PROCESSOR_REVISION': '9e0d', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMFILES': 'C:\\Program Files', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROGRAMW6432': 'C:\\Program Files', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files (x86)\\Windows Kits\\10\\Microsoft Application Virtualization\\Sequencer\\AppvPkgConverter;C:\\Program Files (x86)\\Windows Kits\\10\\Microsoft Application Virtualization\\Sequencer\\AppvSequencer;C:\\Program Files (x86)\\Microsoft SQL Server\\110\\Tools\\PowerShell\\Modules\\', 'PUBLIC': 'C:\\Users\\Public', 'PYCHARM': 'C:\\Program Files\\JetBrains\\PyCharm 2021.3\\bin;', 'PYCHARM PROFESSIONAL EDITION WITH ANACONDA PLUGIN': 'C:\\Program Files\\JetBrains\\PyCharm Professional Edition with Anaconda plugin 2019.3.5\\bin;', 'SESSIONNAME': 'Console', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\WINDOWS', 'TEMP': 'C:\\\\TMP', 'TMP': 'C:\\\\TMP', 'TMPDIR': 'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp', 'USERDOMAIN': 'AREA-51', 'USERDOMAIN_ROAMINGPROFILE': 'AREA-51', 'USERNAME': 'Ken Marr', 'USERPROFILE': 'C:\\Users\\Ken Marr', 'VS160COMCOMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools\\', 'WINDIR': 'C:\\WINDOWS', 'ZES_ENABLE_SYSMAN': '1', '__PSLOCKDOWNPOLICY': '0', 'QT_API': 'pyqt5', 'QT_AUTO_SCREEN_SCALE_FACTOR': '1', 'QT_MAC_WANTS_LAYER': '1'}}
2022-04-09 08:52:42,201 - mu.virtual_environment:441(run_subprocess) DEBUG: Process returned 0; output: 
2022-04-09 08:52:42,201 - mu.virtual_environment:797(create_venv) INFO: Created virtual environment using C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\pythonw.exe at C:\Users\Ken Marr\AppData\Local\python\mu\mu_venv-38-20220409-085232
2022-04-09 08:52:42,204 - mu.virtual_environment:873(install_baseline_packages) INFO: Installing baseline packages.
2022-04-09 08:52:42,205 - mu.virtual_environment:880(install_baseline_packages) INFO: Expecting zipped wheels at C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\wheels\1.1.1.zip
2022-04-09 08:52:42,319 - mu.virtual_environment:855(install_from_zipped_wheels) INFO: About to install from wheel: asttokens-2.0.5-py2.py3-none-any.whl
2022-04-09 08:52:42,320 - mu.virtual_environment:114(run_blocking) INFO: About to run blocking C:\Users\Ken Marr\AppData\Local\python\mu\mu_venv-38-20220409-085232\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\tmpkx9xstzb\\asttokens-2.0.5-py2.py3-none-any.whl'] and envvars {}
2022-04-09 08:52:43,931 - mu.virtual_environment:164(wait) DEBUG: Finished: True; exitStatus 0; exitCode 101
2022-04-09 08:52:43,931 - mu.virtual_environment:185(wait) ERROR: Unable to create process using 'C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Ken Marr\AppData\Local\python\mu\mu_venv-38-20220409-085232\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\Public\Documents\Wondershare\CreatorTemp\tmpkx9xstzb\asttokens-2.0.5-py2.py3-none-any.whl'
2022-04-09 08:52:43,946 - mu.virtual_environment:643(ensure_and_create) ERROR: Process finished but with error code 101:
Unable to create process using 'C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Ken Marr\AppData\Local\python\mu\mu_venv-38-20220409-085232\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\Public\Documents\Wondershare\CreatorTemp\tmpkx9xstzb\asttokens-2.0.5-py2.py3-none-any.whl'
2022-04-09 08:52:43,949 - mu.virtual_environment:540(quarantine_venv) INFO: Quarantined C:\Users\Ken Marr\AppData\Local\python\mu\mu_venv-38-20220409-085232 as C:\Users\Ken Marr\AppData\Local\python\mu\mu_venv-38-20220409-085232.FAILED
2022-04-09 08:52:43,951 - mu.virtual_environment:460(relocate) DEBUG: Relocating to C:\Users\Ken Marr\AppData\Local\python\mu\mu_venv-38-20220409-085243
2022-04-09 08:52:43,951 - mu.virtual_environment:476(relocate) DEBUG: Virtual environment set up mu_venv-38-20220409-085243 at C:\Users\Ken Marr\AppData\Local\python\mu\mu_venv-38-20220409-085243
2022-04-09 08:52:43,952 - mu.virtual_environment:596(ensure_and_create) DEBUG: Checking virtual environment; attempt #2.
2022-04-09 08:52:43,952 - mu.virtual_environment:781(create_venv) INFO: Creating virtualenv: C:\Users\Ken Marr\AppData\Local\python\mu\mu_venv-38-20220409-085243
2022-04-09 08:52:43,952 - mu.virtual_environment:782(create_venv) INFO: Virtualenv name: mu_venv-38-20220409-085243
2022-04-09 08:52:43,952 - mu.virtual_environment:429(run_subprocess) INFO: Running ('C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Mu Editor\\Python\\pythonw.exe', '-I', '-m', 'virtualenv', '-p', 'C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Mu Editor\\Python\\pythonw.exe', '-q', 'C:\\Users\\Ken Marr\\AppData\\Local\\python\\mu\\mu_venv-38-20220409-085243') with kwargs {'env': {'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\Ken Marr\\AppData\\Roaming', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'AREA-51', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\Users\\Ken Marr', 'HPSAPRINTERFIRMWARE': '192.168.1.95', 'LOCALAPPDATA': 'C:\\Users\\Ken Marr\\AppData\\Local', 'LOGONSERVER': '\\\\AREA-51', 'NUMBER_OF_PROCESSORS': '16', 'ONEDRIVE': 'C:\\Users\\Ken Marr\\OneDrive', 'ONEDRIVECONSUMER': 'C:\\Users\\Ken Marr\\OneDrive', 'OS': 'Windows_NT', 'PATH': 'C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Mu Editor\\Python\\lib\\site-packages\\PyQt5\\Qt\\bin;C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\;C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\Python\\Python39\\;C:\\ActiveTcl\\bin;C:\\Program Files\\Python310\\Scripts\\;C:\\Program Files\\Python310\\;C:\\Program Files\\Eps14\\bin;C:\\texlive\\2019\\bin\\win32;C:\\Python\\;C:\\Python\\Scripts\\;C:\\Program Files\\Perl64\\bin;C:\\Users\\Ken Marr\\AppData\\Roaming\\ActiveState\\bin;C:\\Windows;C:\\Windows\\system32;C:\\Windows\\system32\\wbem;C:\\Windows\\system32\\windowspowershell\\v1.0\\;c:\\windows\\system32\\openssh\\;c:\\program files (x86)\\nvidia corporation\\physx\\common;c:\\program files\\nvidia corporation\\nvidia nvdlisr;c:\\program files\\microsoft vs code\\bin;c:\\program files\\calibre2\\;G:\\texlive\\2019\\bin\\win32;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\dotnet\\;c:\\program files\\microsoft sql server\\client sdk\\odbc\\170\\tools\\binn\\;c:\\program files\\microsoft sql server\\130\\tools\\binn\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\dotnet\\;C:\\Program Files (x86)\\Microsoft SQL Server\\110\\DTS\\Binn\\;C:\\Program Files (x86)\\Windows Kits\\10\\Microsoft Application Virtualization\\Sequencer\\;C:\\Program Files (x86)\\Microsoft SQL Server\\110\\Tools\\Binn\\;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\MinGW\\bin;C:\\Program Files\\Graphviz\\bin;C:\\Program Files\\MiKTeX\\miktex\\bin\\x64\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\MySQL\\MySQL Shell 8.0\\bin\\;C:\\Users\\Ken Marr\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\JetBrains\\PyCharm Professional Edition with Anaconda plugin 2019.3.5\\bin;;C:\\Users\\Ken Marr\\AppData\\Local\\Programs\\MiKTeX\\miktex\\bin\\x64\\;C:\\Program Files\\JetBrains\\PyCharm 2021.3\\bin;', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PL;.WPL;.PY;.PYW', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 158 Stepping 13, GenuineIntel', 'PROCESSOR_LEVEL': '6', 'PROCESSOR_REVISION': '9e0d', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMFILES': 'C:\\Program Files', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROGRAMW6432': 'C:\\Program Files', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files (x86)\\Windows Kits\\10\\Microsoft Application Virtualization\\Sequencer\\AppvPkgConverter;C:\\Program Files (x86)\\Windows Kits\\10\\Microsoft Application Virtualization\\Sequencer\\AppvSequencer;C:\\Program Files (x86)\\Microsoft SQL Server\\110\\Tools\\PowerShell\\Modules\\', 'PUBLIC': 'C:\\Users\\Public', 'PYCHARM': 'C:\\Program Files\\JetBrains\\PyCharm 2021.3\\bin;', 'PYCHARM PROFESSIONAL EDITION WITH ANACONDA PLUGIN': 'C:\\Program Files\\JetBrains\\PyCharm Professional Edition with Anaconda plugin 2019.3.5\\bin;', 'SESSIONNAME': 'Console', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\WINDOWS', 'TEMP': 'C:\\\\TMP', 'TMP': 'C:\\\\TMP', 'TMPDIR': 'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp', 'USERDOMAIN': 'AREA-51', 'USERDOMAIN_ROAMINGPROFILE': 'AREA-51', 'USERNAME': 'Ken Marr', 'USERPROFILE': 'C:\\Users\\Ken Marr', 'VS160COMCOMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools\\', 'WINDIR': 'C:\\WINDOWS', 'ZES_ENABLE_SYSMAN': '1', '__PSLOCKDOWNPOLICY': '0', 'QT_API': 'pyqt5', 'QT_AUTO_SCREEN_SCALE_FACTOR': '1', 'QT_MAC_WANTS_LAYER': '1'}}
2022-04-09 08:52:44,720 - mu.virtual_environment:441(run_subprocess) DEBUG: Process returned 0; output: 
2022-04-09 08:52:44,720 - mu.virtual_environment:797(create_venv) INFO: Created virtual environment using C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\pythonw.exe at C:\Users\Ken Marr\AppData\Local\python\mu\mu_venv-38-20220409-085243
2022-04-09 08:52:44,720 - mu.virtual_environment:873(install_baseline_packages) INFO: Installing baseline packages.
2022-04-09 08:52:44,721 - mu.virtual_environment:880(install_baseline_packages) INFO: Expecting zipped wheels at C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\wheels\1.1.1.zip
2022-04-09 08:52:44,820 - mu.virtual_environment:855(install_from_zipped_wheels) INFO: About to install from wheel: asttokens-2.0.5-py2.py3-none-any.whl
2022-04-09 08:52:44,820 - mu.virtual_environment:114(run_blocking) INFO: About to run blocking C:\Users\Ken Marr\AppData\Local\python\mu\mu_venv-38-20220409-085243\scripts\pip.exe with args ['install', '--disable-pip-version-check', '--no-deps', '--no-index', 'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\tmpdorh6nz2\\asttokens-2.0.5-py2.py3-none-any.whl'] and envvars {}
2022-04-09 08:52:45,446 - mu.virtual_environment:164(wait) DEBUG: Finished: True; exitStatus 0; exitCode 101
2022-04-09 08:52:45,446 - mu.virtual_environment:185(wait) ERROR: Unable to create process using 'C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Ken Marr\AppData\Local\python\mu\mu_venv-38-20220409-085243\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\Public\Documents\Wondershare\CreatorTemp\tmpdorh6nz2\asttokens-2.0.5-py2.py3-none-any.whl'
2022-04-09 08:52:45,457 - mu.virtual_environment:643(ensure_and_create) ERROR: Process finished but with error code 101:
Unable to create process using 'C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Ken Marr\AppData\Local\python\mu\mu_venv-38-20220409-085243\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\Public\Documents\Wondershare\CreatorTemp\tmpdorh6nz2\asttokens-2.0.5-py2.py3-none-any.whl'
2022-04-09 08:52:45,459 - mu.virtual_environment:540(quarantine_venv) INFO: Quarantined C:\Users\Ken Marr\AppData\Local\python\mu\mu_venv-38-20220409-085243 as C:\Users\Ken Marr\AppData\Local\python\mu\mu_venv-38-20220409-085243.FAILED
2022-04-09 08:52:52,473 - root:171(excepthook) ERROR: Unrecoverable error
Traceback (most recent call last):
  File "C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 159, in run
    raise ex
  File "C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 772, in create
    self.install_baseline_packages()
  File "C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 885, in install_baseline_packages
    self.install_from_zipped_wheels(zipped_wheels_filepath)
  File "C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 860, in install_from_zipped_wheels
    self.pip.install(wheel, deps=False, index=False)
  File "C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 270, in install
    return self.run(
  File "C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 246, in run
    result = self.process.run_blocking(
  File "C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 122, in run_blocking
    return self.wait(wait_for_s=wait_for_s)
  File "C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 186, in wait
    raise VirtualEnvironmentError(
mu.virtual_environment.VirtualEnvironmentError: Process finished but with error code 101:
Unable to create process using 'C:\Users\Ken Marr\AppData\Local\Programs\Mu Editor\Python\python.exe "C:\Users\Ken Marr\AppData\Local\python\mu\mu_venv-38-20220409-085243\scripts\pip.exe" install --disable-pip-version-check --no-deps --no-index C:\Users\Public\Documents\Wondershare\CreatorTemp\tmpdorh6nz2\asttokens-2.0.5-py2.py3-none-any.whl'
2022-04-09 08:52:52,778 - mu.settings:169(save) DEBUG: Saving to C:\Users\Ken Marr\AppData\Local\python\mu\session.json
2022-04-09 08:52:52,778 - mu.settings:169(save) DEBUG: Saving to C:\Users\Ken Marr\AppData\Local\python\mu\venv.json
