### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by dorazioezio** [mu-editor/mu#2173]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.0.beta.5
Locale: fr_BE
Platform: Windows 10 10.0.22000 AMD64

```
Traceback (most recent call last):
  File "C:\Users\Ezio\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 161, in run
    raise ex
  File "C:\Users\Ezio\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\app.py", line 148, in run
    venv.ensure_and_create(self.display_text)
  File "C:\Users\Ezio\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "C:\Users\Ezio\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 767, in create
    self.create_venv()
  File "C:\Users\Ezio\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\virtual_environment.py", line 798, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using C:\Users\Ezio\AppData\Local\Programs\Mu Editor\Python\pythonw.exe at C:\Users\Ezio\AppData\Local\python\mu\mu_venv-38-20220411-182230
AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython2macOsArmFramework'

```

**Comment by carlosperate** [comment]
Hi @dorazioezio, thanks for the report.

Would you be able to attach the Mu log to this GitHub Issue as well? It'll be really useful to us for debugging. File should be located in: `C:\Users\Ezio\AppData\Local\python\mu\Logs\mu.log`

Apart from that, could you run the following commands in a command prompt and paste here the results?

```
"C:\Users\Ezio\AppData\Local\Programs\Mu Editor\Python\python.exe" -m pip list --verbose
```

```
"C:\Users\Ezio\AppData\Local\Programs\Mu Editor\Python\python.exe" -I -m pip list --verbose
```

It'll be really useful to help us diagnose the problem.

Thanks!
