### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by AakeJon49** [mu-editor/mu#2185]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: sv_SE
Platform: Linux 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mu/app.py", line 159, in run
    raise ex
  File "/usr/local/lib/python3.8/dist-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)

  File "/usr/local/lib/python3.8/dist-packages/mu/virtual_environment.py", line 621, in ensure_and_create
    self.recreate()
  File "/usr/local/lib/python3.8/dist-packages/mu/virtual_environment.py", line 566, in recreate
    self.create()
  File "/usr/local/lib/python3.8/dist-packages/mu/virtual_environment.py", line 772, in create
    self.install_baseline_packages()
  File "/usr/local/lib/python3.8/dist-packages/mu/virtual_environment.py", line 883, in install_baseline_packages
    wheels.download(zipped_wheels_filepath, logger)
  File "/usr/local/lib/python3.8/dist-packages/mu/wheels/__init__.py", line 178, in download
    zip_wheels(zip_filepath, temp_dirpath, logger)
  File "/usr/local/lib/python3.8/dist-packages/mu/wheels/__init__.py", line 149, in zip_wheels
    with zipfile.ZipFile(zip_filepath, "w") as z:
  File "/usr/lib/python3.8/zipfile.py", line 1251, 
[mu.log](https://github.com/mu-editor/mu/files/8516250/mu.log)
in __init__
    self.fp = io.open(file, filemode)
PermissionError: [Errno 13] Ãtkomst nekas: '/usr/local/lib/python3.8/dist-packages/mu/wheels/1.1.1.zip'

```

**Comment by carlosperate** [comment]
Hi @AakeJon49, thanks for the report!

Does Mu work if launched with `sudo`?
