### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by rovergeek** [mu-editor/mu#2188]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: en_CA
Platform: Linux 5.4.0-107-generic #121~18.04.1-Ubuntu SMP Thu Mar 24 17:21:33 UTC 2022 x86_64
[mu.log](https://github.com/mu-editor/mu/files/8535114/mu.log)

```
Traceback (most recent call last):
  File "/home/stephen/.local/lib/python3.6/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/stephen/.local/lib/python3.6/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/stephen/.local/lib/python3.6/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/stephen/.local/lib/python3.6/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/stephen/.local/lib/python3.6/site-packages/mu/virtual_environment.py", line 805, in create_venv
    % (sys.executable, self.path, compact(output))
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/stephen/.local/share/mu/mu_venv-36-20220421-132201
STDERR: /usr/bin/python3: No module named virtualenv

```

**Comment by rovergeek** [comment]
[mu.log](https://github.com/mu-editor/mu/files/8535116/mu.log)
