### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by jaumearagay** [mu-editor/mu#2208]
**REMEMBER TO ATTACH YOUR LOG FILE**

Version: 1.1.1
Locale: ca_ES
Platform: Linux 5.13.0-40-generic #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022 x86_64

```
Traceback (most recent call last):
  File "/home/jaume/.local/lib/python3.8/site-packages/mu/app.py", line 159, in run
    raise ex
  File "/home/jaume/.local/lib/python3.8/site-packages/mu/app.py", line 146, in run
    venv.ensure_and_create(self.display_text)
  File "/home/jaume/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 603, in ensure_and_create
    self.create()
  File "/home/jaume/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 771, in create
    self.create_venv()
  File "/home/jaume/.local/lib/python3.8/site-packages/mu/virtual_environment.py", line 803, in create_venv
    raise VirtualEnvironmentCreateError(
mu.virtual_environment.VirtualEnvironmentCreateError: Unable to create a virtual environment using /usr/bin/python3 at /home/jaume/.local/share/mu/mu_venv-38-20220505-202703
STDERR: /usr/bin/python3: No module named virtualenv

```
My log:
[mu.log](https://github.com/mu-editor/mu/files/8633747/mu.log)

**Comment by jaumearagay** [comment]
Solved. See #2214 Crash Report.
