### ISSUE TITLE
Mu Editor Crashes

### ISSUE THREAD

**Issue by Sphe1890** [mu-editor/mu#2254]
### What were you trying to do?

I was trying to open Mu Editor to program something in Python, when it suddenly crashes.

### What steps did you take to trigger the issue?

Honestly I didn't do anything, just one day I turned on the PC and it wouldn't open anymore :(

### What did you expect to happen?

I expected Mu to open

### What actually happened?

I was trying to open Mu Editor to program something in Python, when it suddenly crashes. I still don't understand what the problem is, and strangely when I install it from the Repository another Mu icon called "mu-editor" appears.

### Operating System Version

Pop!_OS 22.04 LTS

### Mu Version

1.0.3

### Other Info

![mu-editor_error](https://user-images.githubusercontent.com/99478642/171001785-3fc6422e-f800-45e7-b5c3-f29004150b1b.png)

### Editor Log

Starting Mu 1.0.3
2022-05-30 15:20:59,969 - root:113(run) INFO: uname_result(system='Linux', node='pop-os-sphe', release='5.17.5-76051705-generic', version='#202204271406~1653440576~22.04~6277a18 SMP PREEMPT Wed May 25 01', machine='x86_64')
2022-05-30 15:20:59,969 - root:114(run) INFO: Python path: ['/usr/share/mu-editor', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/sphe/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3/dist-packages/IPython/extensions']
2022-05-30 15:20:59,969 - root:115(run) INFO: Language code: it_IT
2022-05-30 15:21:00,028 - mu.logic:543(__init__) INFO: Setting up editor.
2022-05-30 15:21:00,028 - mu.logic:562(__init__) INFO: Settings path: /home/sphe/.local/share/mu/settings.json
2022-05-30 15:21:00,029 - mu.logic:563(__init__) INFO: Session path: /home/sphe/.local/share/mu/session.json
2022-05-30 15:21:00,029 - mu.logic:564(__init__) INFO: Log directory: /home/sphe/.cache/mu/log
2022-05-30 15:21:00,029 - mu.logic:565(__init__) INFO: Data directory: /home/sphe/.local/share/mu
2022-05-30 15:21:00,041 - mu.logic:578(setup) INFO: Available modes: python, adafruit, microbit, debugger, pygamezero
2022-05-30 15:21:00,071 - root:95(excepthook) ERROR: Unrecoverable error
Traceback (most recent call last):
  File "/usr/bin/mu-editor", line 33, in <module>
    sys.exit(load_entry_point('mu-editor==1.0.3', 'console_scripts', 'mu-editor')())
  File "/usr/share/mu-editor/mu/app.py", line 148, in run
    editor_window.setup(editor.debug_toggle_breakpoint, editor.theme)
  File "/usr/share/mu-editor/mu/interface/main.py", line 825, in setup
    self.autosize_window()
  File "/usr/share/mu-editor/mu/interface/main.py", line 774, in autosize_window
    self.move((screen.width() - size.width()) / 2,
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'float'
  move(self, int, int): argument 1 has unexpected type 'float'

**Comment by carlosperate** [comment]
Thanks for the report @Sphe1890, I believe the problem you are experiencing is https://github.com/mu-editor/mu/issues/2228.

There is an update to the debian package that should land in the near future. In the meantime, that issue has a couple of workarounds you can try to either fix the code from the packaged Mu, or to install the latest version using pipx.

As we are already tracking this problem in https://github.com/mu-editor/mu/issues/2228 I'll close this one, but please do reopen it if you still have any issues or the workarounds didn't work for you.

Thanks again!
