### ISSUE TITLE
Runtime error: wrapped C/C++ object of type xxx has been deleted

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#2262]
## Issue

Looks like we might have some PyQt5 widgets/objects garbage collected, and then some function schedule in some kind of event tries to access them, raising a runtime error.

This has been been resolved in one ocassion for a QLabel in PR https://github.com/mu-editor/mu/pull/1694 for issue https://github.com/mu-editor/mu/issues/1474 and release in [1.1.0-beta.6](https://github.com/mu-editor/mu/releases/tag/1.1.0-beta.6).

In this case the majority of cases we see now are:

```
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\interface\panes.py", line 760, in on_ls_fail
    self.disable()
  File "C:\Users\xxxx\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\interface\panes.py", line 699, in disable
    self.microbit_fs.setDisabled(True)
RuntimeError: wrapped C/C++ object of type MicroPythonDeviceFileList has been deleted
```

## User workaround

Nothing at the moment, this error happens occasionally, so Mu can be launched again.

**Comment by carlosperate** [comment]
## Possible solution

The simplest thing might be to check if the specific instance (in this case `self.microbit_fs`) is still available before trying to access it.

Hardest thing might be trying to find a reliable way to replicate this, to be able to check the fix.

**Comment by carlosperate** [comment]
Related Crash Reports:
- https://github.com/mu-editor/mu/issues/2245
