### ISSUE TITLE
can't make win64

### ISSUE THREAD

**Issue by jd3096-mpy** [mu-editor/mu#2333]
### What were you trying to do?

try to build installer

### What steps did you take to trigger the issue?

run make win64

### What actually happened?

I pip err: ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
I pip err:
I pip out: Successfully installed PyQt5-5.13.2 PyQt5-sip-12.11.0 PyQtChart-5.13.1 QScintilla-2.11.3 adafruit-board-toolkit-1.1.0 backcall-0.2.0 black-21.12b0 charset-normalizer-2.1.1 click-8.0.4 colorama-0.4.5 decorator-5.1.1 distlib-0.3.5 filelock-3.8.0 flake8-5.0.4 importlib-metadata-4.12.0 ipykernel-5.5.6 ipython-7.34.0 ipython-genutils-0.2.0 jedi-0.18.1 jupyter-client-6.1.12 jupyter-core-4.11.1 matplotlib-inline-0.1.6 mccabe-0.7.0 mu-editor-1.1.1 mypy-extensions-0.4.3 nudatus-0.0.5 packaging-21.3 parso-0.8.3 pathspec-0.9.0 pickleshare-0.7.5 platformdirs-2.5.2 prompt-toolkit-3.0.30 pycodestyle-2.9.1 pyflakes-2.5.0 pygments-2.13.0 pyparsing-3.0.9 pyserial-3.5 python-dateutil-2.8.2 pywin32-304 pyzmq-23.2.1 qtconsole-4.7.7 qtpy-2.2.0 requests-2.28.1 semver-2.13.0 six-1.16.0 tomli-1.2.3 tornado-6.2 traitlets-5.3.0 typed-ast-1.5.4 typing-extensions-4.3.0 urllib3-1.26.11 virtualenv-20.16.3 wcwidth-0.2.5 wheel-0.37.1 zipp-3.8.1
I pip err: We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
I pip err:
I pip err: flake8 5.0.4 requires importlib-metadata<4.3,>=1.1.0; python_version < "3.8", but you'll have importlib-metadata 4.12.0 which is incompatible.
I Step 'pup.pip-install': completed.
I Step 'pup.install-cleanup': starting.
I Deleting 'E:\\mu\\build\\pup\\Mu Editor 1.1.1\\Python\\include'...
I Deleting 'E:\\mu\\build\\pup\\Mu Editor 1.1.1\\Python\\libs'...
I Deleting 'E:\\mu\\build\\pup\\Mu Editor 1.1.1\\Python\\share'...
I Deleting '*.lib' files...
I Deleting '*.pdb' files...
I Deleting '*.a' files...
I Compiling the Standard Library and site-packages...
I Step 'pup.install-cleanup': completed.
I Step 'win.sign-binaries': starting.
E cannot sign: environment variable 'PUP_SIGNING_IDENTITY' not defined.
I Step 'win.sign-binaries': completed.
I Step 'win.create-msi': starting.
C Execution failure: [WinError 2] 系统找不到指定的文件。
C Traceback below:
Traceback (most recent call last):
  File "E:\mu\venv-pup\lib\site-packages\pup\__main__.py", line 31, in wrapper
    exit_code = command_function(*args, **kw)
  File "E:\mu\venv-pup\lib\site-packages\pup\__main__.py", line 90, in package
    license_path=license_path,
  File "E:\mu\venv-pup\lib\site-packages\pup\api.py", line 64, in package
    dsp.run_pluggable_step(step)
  File "E:\mu\venv-pup\lib\site-packages\pup\dispatcher.py", line 79, in run_pluggable_step
    return self._invoke_plugin(name)
  File "E:\mu\venv-pup\lib\site-packages\pup\dispatcher.py", line 68, in _invoke_plugin
    return plugin(self._ctx, self, **kwargs)
  File "E:\mu\venv-pup\lib\site-packages\pup\plugins\win\create_msi.py", line 55, in __call__
    self._create_wix_manifest(ctx, dsp, wix_root, manifest_path)
  File "E:\mu\venv-pup\lib\site-packages\pup\plugins\win\create_msi.py", line 287, in _create_wix_manifest
    err_callable=lambda line: _log.info('wix heat err: %s', line),
  File "E:\mu\venv-pup\lib\site-packages\pup\dispatcher.py", line 99, in spawn
    return spawn.spawn(command, out_callable, err_callable, encoding, env=env)
  File "E:\mu\venv-pup\lib\site-packages\pup\spawn.py", line 37, in spawn
    env=env,
  File "C:\Users\jd3096\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\jd3096\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
I pup 1.0.0a17 - done
Traceback (most recent call last):
  File "make.py", line 501, in <module>
    sys.exit(main(*sys.argv[1:]))
  File "make.py", line 497, in main
    return function(*args)
  File "make.py", line 453, in win64
    _build_windows_msi(bitness=64)
  File "make.py", line 439, in _build_windows_msi
    subprocess.check_call(cmd)
  File "C:\Users\jd3096\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['./venv-pup/Scripts/pup.exe', 'package', '--launch-module=mu', '--nice-name=Mu Editor', '--icon-path=./package/icons/win_icon.ico', '--license-path=./LICENSE', '.']' returned non-zero exit status 4294967295.

### Operating System Version

win10

### Mu Version

1.1.1

**Comment by carlosperate** [comment]
Thanks for the report @jd3096-mpy.

Mu uses pup to create the installers, you can find more info in: https://github.com/mu-editor/pup

Do you have WiX installed?
