### ISSUE TITLE
Moving window error, provided "float" values should be "int".

### ISSUE THREAD

**Issue by acjackman86** [mu-editor/mu#2337]
### What were you trying to do?

Start the application.

### What steps did you take to trigger the issue?

Starting the application never happened due to this issue.

### What did you expect to happen?

For the application to start.

### What actually happened?

It never started. I got an error while trying to run it in the terminal, returning a type error that the window's move function was receiving float values instead of integers. The problem was solved by replacing lines 774 and 775 in mu/interface/main.py with these values:

self.move(int((screen.width() - size.width()) / 2),
                 int((screen.height() - size.height()) / 2))

After saving main.py, the Mu Editor I was using functioned as normal.

### Operating System Version

Ubuntu 22.04

### Mu Version

1.0.3

### Other Info

Just the small edit in the mu/interface/main.py file made everything run smoothly.

### Editor Log
-----------------

Starting Mu 1.0.3
2022-09-06 19:52:29,846 - root:113(run) INFO: uname_result(system='Linux', node='lil-mate-top', release='5.15.0-47-generic', version='#51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022', machine='x86_64')
2022-09-06 19:52:29,846 - root:114(run) INFO: Python path: ['/usr/share/mu-editor', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/ajay/.local/lib/python3.10/site-packages', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3/dist-packages/IPython/extensions']
2022-09-06 19:52:29,846 - root:115(run) INFO: Language code: en_US
2022-09-06 19:52:30,213 - mu.logic:543(__init__) INFO: Setting up editor.
2022-09-06 19:52:30,213 - mu.logic:562(__init__) INFO: Settings path: /home/ajay/.local/share/mu/settings.json
2022-09-06 19:52:30,214 - mu.logic:563(__init__) INFO: Session path: /home/ajay/.local/share/mu/session.json
2022-09-06 19:52:30,214 - mu.logic:564(__init__) INFO: Log directory: /home/ajay/.cache/mu/log
2022-09-06 19:52:30,214 - mu.logic:565(__init__) INFO: Data directory: /home/ajay/.local/share/mu
2022-09-06 19:52:30,282 - mu.logic:578(setup) INFO: Available modes: python, adafruit, microbit, debugger, pygamezero
2022-09-06 19:52:30,454 - root:95(excepthook) ERROR: Unrecoverable error
Traceback (most recent call last):
  File "/usr/bin/mu-editor", line 33, in <module>
    sys.exit(load_entry_point('mu-editor==1.0.3', 'console_scripts', 'mu-editor')())
  File "/usr/share/mu-editor/mu/app.py", line 148, in run
    editor_window.setup(editor.debug_toggle_breakpoint, editor.theme)
  File "/usr/share/mu-editor/mu/interface/main.py", line 825, in setup
    self.autosize_window()
  File "/usr/share/mu-editor/mu/interface/main.py", line 774, in autosize_window
    self.move((screen.width() - size.width()) / 2,
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'float'
  move(self, int, int): argument 1 has unexpected type 'float'
2022-09-06 20:03:25,816 - root:112(run) INFO:

**Comment by superpotato9** [comment]
thanks you saved me so much time with this

**Comment by carlosperate** [comment]
Thanks for the report @acjackman86!
This is covered in https://github.com/mu-editor/mu/issues/2228 already, so I'll close this to keep things organises in a single ticket 👍
