### ISSUE TITLE
error accessing files in ESP32

### ISSUE THREAD

**Issue by javixeneize** [mu-editor/mu#2360]
### What were you trying to do?

getting files from the device

### What steps did you take to trigger the issue?

hit the files button in the app

### What did you expect to happen?

retrieve files

### What actually happened?

An error happened - There was a problem getting the list of files on the device. 

The log shows this error: 

OSError: Could not enter raw REPL.

 Other tools as thonny retrieve the files correctly

### Operating System Version

esp32-20220618-v1.19.1

### Mu Version

1.2.0

### Editor Log

2022-11-28 16:34:13,859 - mu.modes.esp:220(toggle_files) INFO: Toggle filesystem on.
2022-11-28 16:34:16,589 - mu.modes.base:693(ls) ERROR: Could not enter raw REPL.
Traceback (most recent call last):
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/modes/base.py", line 690, in ls
    result = tuple(microfs.ls(self.serial))
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/contrib/microfs.py", line 185, in ls
    out, err = execute(["import os", "print(os.listdir())"], serial)
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/contrib/microfs.py", line 139, in execute
    raw_on(serial)
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/contrib/microfs.py", line 91, in raw_on
    flush_to_msg(serial, raw_repl_msg)
  File "/Applications/Mu Editor.app/Contents/Resources/Python/lib/python3.8/site-packages/mu/contrib/microfs.py", line 72, in flush_to_msg
    raise IOError("Could not enter raw REPL.")
OSError: Could not enter raw REPL.

**Comment by gschaden** [comment]
have the same problem and added a retries to the function
