### ISSUE TITLE
Test Failed in Windows build

### ISSUE THREAD

**Issue by roboticsware** [mu-editor/mu#2472]
### What were you trying to do?

make win64

### What steps did you take to trigger the issue?

When starting a build by this command, "make win64"

### What did you expect to happen?

No build error

### What actually happened?

Test filed by text encoding issue

### Operating System Version

Windows 10 + Korean language pack

### Mu Version

1.2

### Editor Log

=============================================== short test summary info ===============================================
FAILED tests/test_logic.py::test_read_encoding_default - UnicodeEncodeError: 'cp949' codec can't encode character '\xa0' in position 96: illegal multibyte sequence
========================== 1 failed, 1119 passed, 20 skipped, 7 warnings in 63.80s (0:01:03) ==========================
Traceback (most recent call last):
  File "make.py", line 501, in <module>
    sys.exit(main(*sys.argv[1:]))
  File "make.py", line 497, in main
    return function(*args)
  File "make.py", line 453, in win64
    _build_windows_msi(bitness=64)
  File "make.py", line 416, in _build_windows_msi
    raise RuntimeError("Check failed")
RuntimeError: Check failed

**Comment by shivansh4123** [comment]
i found out how to solve this , in the wheels module (wheels/init.py), locate the pip_download function. The line that raises the the error is: "Pip was unable to download %s" % pip_identifiers and Modify it to ensure proper string formatting: "Pip was unable to download {}".format(pip_identifiers)
