### ISSUE TITLE
Mu crashed when debugger started for the first time

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#286]
Windows 10 64 bits
Python 3.5.2

```
$ pip freeze
alabaster==0.7.9
Babel==2.3.4
colorama==0.3.7
coverage==4.2
cycler==0.10.0
decorator==4.1.2
docutils==0.12
imagesize==0.7.1
ipykernel==4.6.1
ipython==6.2.0
ipython-genutils==0.2.0
jedi==0.10.2
Jinja2==2.8
jupyter-client==5.1.0
jupyter-core==4.3.0
MarkupSafe==0.23
matplotlib==2.0.2
numpy==1.13.1
pickleshare==0.7.4
prompt-toolkit==1.0.15
py==1.4.31
pycodestyle==2.0.0
pyFirmata==1.0.3
pyflakes==1.3.0
Pygments==2.1.3
pyparsing==2.2.0
PyQt5==5.7
pyserial==3.1.1
pytest==3.0.2
pytest-cov==2.3.1
python-dateutil==2.6.1
pytz==2016.6.1
pyzmq==16.0.2
QScintilla==2.9.3
qtconsole==4.3.1
simplegeneric==0.8.1
sip==4.18.1
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.4.6
tornado==4.5.2
traitlets==4.3.2
wcwidth==0.1.7
win-unicode-console==0.5
```

Exception:

```
Traceback (most recent call last):
  File "C:\workspace\microbit-mine\mu\mu\logic.py", line 732, in debug_toggle_breakpoint
    self.modes['debugger'].toggle_breakpoint(line, tab)
  File "C:\workspace\microbit-mine\mu\mu\modes\debugger.py", line 201, in toggle_breakpoint
    bps = self.debugger.breakpoints(tab.path)
  File "C:\workspace\microbit-mine\mu\mu\debugger\client.py", line 227, in breakpoints
    return self.bp_index.get(filename, {})
AttributeError: 'Debugger' object has no attribute 'bp_index'
```

[mu.log.txt](https://github.com/mu-editor/mu/files/1324661/mu.log.txt)

Finding it hard to get exact steps to replicate, but will give it another go once I have some time.

**Comment by ntoll** [comment]
I've never had this, does it still happen when you use the version of Mu via the Windows installer..? It works for me. Please feel free to re-open.
