### ISSUE TITLE
Raspberry pi - development build

### ISSUE THREAD

**Issue by martinohanlon** [mu-editor/mu#329]
I am trying to install Mu from source on a Raspberry Pi following the instructions on [https://mu.readthedocs.io/en/latest/setup.html#raspberry-pi](https://mu.readthedocs.io/en/latest/setup.html#raspberry-pi)

The following runs successfully:

```
sudo apt-get install python3-pyqt5 python3-pyqt5.qsci python3-pyqt5.qtserialport python3-dev
sudo pip3 install -r requirements_pi.txt
```

When I try and run mu I receive the following error:

```
python3 run.py
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from mu.app import run
  File "/home/pi/mu/mu/app.py", line 49, in <module>
    from mu.interface import Window
  File "/home/pi/mu/mu/interface/__init__.py", line 1, in <module>
    from .main import Window
  File "/home/pi/mu/mu/interface/main.py", line 32, in <module>
    from mu.interface.panes import (DebugInspector, PythonProcessPane,
  File "/home/pi/mu/mu/interface/panes.py", line 34, in <module>
    from qtconsole.rich_jupyter_widget import RichJupyterWidget
  File "/usr/local/lib/python3.5/dist-packages/qtconsole/rich_jupyter_widget.py", line 9, in <module>
    from qtconsole.qt import QtCore, QtGui
  File "/usr/local/lib/python3.5/dist-packages/qtconsole/qt.py", line 23, in <module>
    QtCore, QtGui, QtSvg, QT_API = load_qt(api_opts)
  File "/usr/local/lib/python3.5/dist-packages/qtconsole/qt_loaders.py", line 386, in load_qt
    api_options))
ImportError: 
    Could not load requested Qt binding. Please ensure that
    PyQt4 >= 4.7, PyQt5, PySide >= 1.0.3 or PySide2 is available,
    and only one is imported per session.

    Currently-imported Qt library:   'pyqt5'
    PyQt4 installed:                 False
    PyQt5 installed:                 False
    PySide >= 1.0.3 installed:       False
    PySide2 installed:               False
    Tried to load:                   ['pyqt5']
```

**Comment by ntoll** [comment]
You've not allowed for site packages to be available in your virtualenv. ;-) (See step two here: https://mu.readthedocs.io/en/latest/setup.html#raspberry-pi)

**Comment by martinohanlon** [comment]
I'm not using a virtual environment. Do I need too?

**Comment by ntoll** [comment]
Of course..! :-) That's what the instructions say...! :-P

**Comment by carlosperate** [comment]
This is likely to be related to https://github.com/mu-editor/mu/pull/312.
Try installing python3-pyqt5.qtsvg as well.

**Comment by martinohanlon** [comment]
This issue was a result of problems with the Raspberry Pi setup and a missing dependency `python3-pyqt5.qtsvg` 

PR #331 submitted.

**Comment by martinohanlon** [comment]
Resolved.
