### ISSUE TITLE
Removing a breakpoint in the debugger causes an exception

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#428]
Might be related to issue https://github.com/mu-editor/mu/issues/403 - Adding a breakpoint in the debugger causes an exception.

This happened in beta 15 on a Raspberry Pi (the one that apt-get currently installs). I was adding a breakpoint and the application closed when I clicked on it again to remove it.

The log is quite large as I was doing a lot of different stuff in Mu for quite a while, and it also contains bits that can't really be shared publicly (API keys), so I'll copy the relevant part here:
```
2018-04-07 13:08:56,968 - mu.modes.python3:183(debug) INFO: Starting debug mode.
2018-04-07 13:08:57,059 - mu.logic:712(change_mode) INFO: Workspace directory: /home/pi/mu_code
2018-04-07 13:08:57,060 - mu.modes.debugger:112(start) DEBUG: from twython import TwythonStreamer
from sense_hat import SenseHat
from colorzero import Color
from auth import (
    consumer_key,
    consumer_secret,
    access_token,
    access_token_secret
)

sense = SenseHat()
hashtag = '#cheerlights'

class MyStreamer(TwythonStreamer):
    def on_success(self, data):
        if 'text' in data:
            tweet = data['text']
            tweet = tweet.replace(hashtag, '')
            color_text = tweet.strip()
            try:
                color = Color(color_text)
                sense.clear(color.rgb_bytes)
            except ValueError:
                print('Failed: {}'.format(color_text))
stream = MyStreamer(
    consumer_key,
    consumer_secret,
    access_token,
    access_token_secret
)
stream.statuses.filter(track=hashtag)

2018-04-07 13:08:57,067 - mu.interface.panes:602(start_process) INFO: Running script:/home/pi/cheerlights/cheerlights.py
2018-04-07 13:08:57,068 - mu.interface.panes:607(start_process) INFO: Command args: []
2018-04-07 13:08:57,068 - mu.interface.panes:613(start_process) INFO: Working directory: /home/pi/mu_code
2018-04-07 13:08:57,069 - mu.interface.panes:618(start_process) INFO: Python path: ['/usr/bin', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-arm-linux-gnueabihf', '/usr/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.5/dist-packages/IPython/extensions']
2018-04-07 13:09:01,733 - mu.debugger.client:146(worker) DEBUG: ["bootstrap", {"breakpoints": []}]
2018-04-07 13:09:01,738 - mu.debugger.client:146(worker) DEBUG: ["stack", {"stack": [[1, {"current": true, "builtins": {"FutureWarning": "<class 'FutureWarning'>", "NotImplementedError": "<class 'NotImplementedError'>", "slice": "<class 'slice'>", "iter": "<built-in function iter>", "str": "<class 'str'>", "hex": "<built-in function hex>", "help": "Type help() for interactive help, or help(object) for help about object.", "tuple": "<class 'tuple'>", "Exception": "<class 'Exception'>", "__doc__": "\"Built-in functions, exceptions, and other objects.\\n\\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.\"", "FileNotFoundError": "<class 'FileNotFoundError'>", "locals": "<built-in function locals>", "any": "<built-in function any>", "ArithmeticError": "<class 'ArithmeticError'>", "round": "<built-in function round>", "complex": "<class 'complex'>", "filter": "<class 'filter'>", "__name__": "'builtins'", "ord": "<built-in function ord>", "hash": "<built-in function hash>", "_": "<bound method NullTranslations.gettext of <gettext.NullTranslations object at 0x7637e250>>", "callable": "<built-in function callable>", "__import__": "<built-in function __import__>", "RuntimeWarning": "<class 'RuntimeWarning'>", "quit": "Use quit() or Ctrl-D (i.e. EOF) to exit", "InterruptedError": "<class 'InterruptedError'>", "BlockingIOError": "<class 'BlockingIOError'>", "all": "<built-in function all>", "__debug__": "True", "UnicodeWarning": "<class 'UnicodeWarning'>", "MemoryError": "<class 'MemoryError'>", "BrokenPipeError": "<class 'BrokenPipeError'>", "globals": "<built-in function globals>", "TypeError": "<class 'TypeError'>", "list": "<class 'list'>", "UnboundLocalError": "<class 'UnboundLocalError'>", "IsADirectoryError": "<class 'IsADirectoryError'>", "AttributeError": "<class 'AttributeError'>", "super": "<class 'super'>", "chr": "<built-in function chr>", "SystemError": "<class 'SystemError'>", "repr": "<built-in function repr>", "delattr": "<built-in function delattr>", "SyntaxError": "<class 'SyntaxError'>", "TimeoutError": "<class 'TimeoutError'>", "bytes": "<class 'bytes'>", "hasattr": "<built-in function hasattr>", "UnicodeTranslateError": "<class 'UnicodeTranslateError'>", "max": "<built-in function max>", "RecursionError": "<class 'RecursionError'>", "id": "<built-in function id>", "staticmethod": "<class 'staticmethod'>", "ZeroDivisionError": "<class 'ZeroDivisionError'>", "vars": "<built-in function vars>", "divmod": "<built-in function divmod>", "zip": "<class 'zip'>", "GeneratorExit": "<class 'GeneratorExit'>", "int": "<class 'int'>", "KeyError": "<class 'KeyError'>", "UnicodeDecodeError": "<class 'UnicodeDecodeError'>", "IndexError": "<class 'IndexError'>", "UnicodeEncodeError": "<class 'UnicodeEncodeError'>", "ConnectionRefusedError": "<class 'ConnectionRefusedError'>", "abs": "<built-in function abs>", "AssertionError": "<class 'AssertionError'>", "OSError": "<class 'OSError'>", "IndentationError": "<class 'IndentationError'>", "object": "<class 'object'>", "credits": "    Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands\n    for supporting Python development.  See www.python.org for more information.", "ValueError": "<class 'ValueError'>", "FloatingPointError": "<class 'FloatingPointError'>", "oct": "<built-in function oct>", "ConnectionResetError": "<class 'ConnectionResetError'>", "EOFError": "<class 'EOFError'>", "len": "<built-in function len>", "Warning": "<class 'Warning'>", "bool": "<class 'bool'>", "reversed": "<class 'reversed'>", "sum": "<built-in function sum>", "compile": "<built-in function compile>", "NameError": "<class 'NameError'>", "LookupError": "<class 'LookupError'>", "KeyboardInterrupt": "<class 'KeyboardInterrupt'>", "ProcessLookupError": "<class 'ProcessLookupError'>", "UserWarning": "<class 'UserWarning'>", "PendingDeprecationWarning": "<class 'PendingDeprecationWarning'>", "ascii": "<built-in function ascii>", "set": "<class 'set'>", "None": "None", "license": "Type license() to see the full license text", "EnvironmentError": "<class 'OSError'>", "frozenset": "<class 'frozenset'>", "print": "<built-in function print>", "Ellipsis": "Ellipsis", "OverflowError": "<class 'OverflowError'>", "RuntimeError": "<class 'RuntimeError'>", "BufferError": "<class 'BufferError'>", "open": "<built-in function open>", "exec": "<built-in function exec>", "range": "<class 'range'>", "memoryview": "<class 'memoryview'>", "classmethod": "<class 'classmethod'>", "bin": "<built-in function bin>", "SystemExit": "<class 'SystemExit'>", "property": "<class 'property'>", "UnicodeError": "<class 'UnicodeError'>", "issubclass": "<built-in function issubclass>", "False": "False", "sorted": "<built-in function sorted>", "dict": "<class 'dict'>", "ResourceWarning": "<class 'ResourceWarning'>", "enumerate": "<class 'enumerate'>", "ReferenceError": "<class 'ReferenceError'>", "setattr": "<built-in function setattr>", "copyright": "Copyright (c) 2001-2017 Python Software Foundation.\nAll Rights Reserved.\n\nCopyright (c) 2000 BeOpen.com.\nAll Rights Reserved.\n\nCopyright (c) 1995-2001 Corporation for National Research Initiatives.\nAll Rights Reserved.\n\nCopyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.\nAll Rights Reserved.", "input": "<built-in function input>", "TabError": "<class 'TabError'>", "format": "<built-in function format>", "True": "True", "getattr": "<built-in function getattr>", "exit": "Use exit() or Ctrl-D (i.e. EOF) to exit", "isinstance": "<built-in function isinstance>", "__build_class__": "<built-in function __build_class__>", "NotImplemented": "NotImplemented", "__loader__": "<class '_frozen_importlib.BuiltinImporter'>", "map": "<class 'map'>", "eval": "<built-in function eval>", "__package__": "''", "ImportWarning": "<class 'ImportWarning'>", "next": "<built-in function next>", "StopIteration": "<class 'StopIteration'>", "FileExistsError": "<class 'FileExistsError'>", "__spec__": "ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>)", "ConnectionAbortedError": "<class 'ConnectionAbortedError'>", "StopAsyncIteration": "<class 'StopAsyncIteration'>", "PermissionError": "<class 'PermissionError'>", "dir": "<built-in function dir>", "BytesWarning": "<class 'BytesWarning'>", "NotADirectoryError": "<class 'NotADirectoryError'>", "type": "<class 'type'>", "min": "<built-in function min>", "float": "<class 'float'>", "DeprecationWarning": "<class 'DeprecationWarning'>", "ChildProcessError": "<class 'ChildProcessError'>", "BaseException": "<class 'BaseException'>", "ConnectionError": "<class 'ConnectionError'>", "SyntaxWarning": "<class 'SyntaxWarning'>", "pow": "<built-in function pow>", "IOError": "<class 'OSError'>", "bytearray": "<class 'bytearray'>", "ImportError": "<class 'ImportError'>"}, "exc_value": "''", "locals": {"__name__": "'__main__'", "__builtins__": "{'FutureWarning': <class 'FutureWarning'>, 'NotImplementedError': <class 'NotImplementedError'>, 'range': <class 'range'>, 'compile': <built-in function compile>, 'iter': <built-in function iter>, 'str': <class 'str'>, 'RuntimeWarning': <class 'RuntimeWarning'>, 'help': Type help() for interactive help, or help(object) for help about object., 'tuple': <class 'tuple'>, '__doc__': \"Built-in functions, exceptions, and other objects.\\n\\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.\", 'FileNotFoundError': <class 'FileNotFoundError'>, 'sum': <built-in function sum>, 'any': <built-in function any>, 'ArithmeticError': <class 'ArithmeticError'>, 'round': <built-in function round>, 'complex': <class 'complex'>, 'filter': <class 'filter'>, '__name__': 'builtins', 'ValueError': <class 'ValueError'>, 'ord': <built-in function ord>, 'hash': <built-in function hash>, 'len': <built-in function len>, 'ProcessLookupError': <class 'ProcessLookupError'>, 'callable': <built-in function callable>, 'Warning': <class 'Warning'>, 'hex': <built-in function hex>, 'quit': Use quit() or Ctrl-D (i.e. EOF) to exit, 'InterruptedError': <class 'InterruptedError'>, '__debug__': True, 'all': <built-in function all>, 'BlockingIOError': <class 'BlockingIOError'>, 'UnicodeWarning': <class 'UnicodeWarning'>, 'MemoryError': <class 'MemoryError'>, 'BrokenPipeError': <class 'BrokenPipeError'>, 'globals': <built-in function globals>, 'TypeError': <class 'TypeError'>, 'list': <class 'list'>, 'IsADirectoryError': <class 'IsADirectoryError'>, 'AttributeError': <class 'AttributeError'>, 'super': <class 'super'>, 'False': False, 'SystemError': <class 'SystemError'>, 'repr': <built-in function repr>, 'delattr': <built-in function delattr>, 'next': <built-in function next>, 'TimeoutError': <class 'TimeoutError'>, 'bytes': <class 'bytes'>, 'hasattr': <built-in function hasattr>, 'ImportWarning': <class 'ImportWarning'>, 'UnicodeTranslateError': <class 'UnicodeTranslateError'>, 'sorted': <built-in function sorted>, 'RecursionError': <class 'RecursionError'>, 'id': <built-in function id>, 'staticmethod': <class 'staticmethod'>, 'ZeroDivisionError': <class 'ZeroDivisionError'>, 'vars': <built-in function vars>, 'zip': <class 'zip'>, 'GeneratorExit': <class 'GeneratorExit'>, 'IndexError': <class 'IndexError'>, 'KeyError': <class 'KeyError'>, 'UnicodeDecodeError': <class 'UnicodeDecodeError'>, 'UnicodeEncodeError': <class 'UnicodeEncodeError'>, 'ConnectionRefusedError': <class 'ConnectionRefusedError'>, 'AssertionError': <class 'AssertionError'>, 'OSError': <class 'OSError'>, 'IndentationError': <class 'IndentationError'>, 'object': <class 'object'>, 'credits':     Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands\n    for supporting Python development.  See www.python.org for more information., 'PermissionError': <class 'PermissionError'>, 'ascii': <built-in function ascii>, 'FloatingPointError': <class 'FloatingPointError'>, 'oct': <built-in function oct>, 'SyntaxError': <class 'SyntaxError'>, 'ConnectionResetError': <class 'ConnectionResetError'>, 'EOFError': <class 'EOFError'>, 'isinstance': <built-in function isinstance>, '__import__': <built-in function __import__>, 'bool': <class 'bool'>, 'reversed': <class 'reversed'>, 'locals': <built-in function locals>, 'abs': <built-in function abs>, 'NameError': <class 'NameError'>, '_': <bound method NullTranslations.gettext of <gettext.NullTranslations object at 0x7637e250>>, 'KeyboardInterrupt': <class 'KeyboardInterrupt'>, 'int': <class 'int'>, 'UserWarning': <class 'UserWarning'>, 'PendingDeprecationWarning': <class 'PendingDeprecationWarning'>, 'divmod': <built-in function divmod>, 'RuntimeError': <class 'RuntimeError'>, 'set': <class 'set'>, 'EnvironmentError': <class 'OSError'>, 'license': Type license() to see the full license text, 'None': None, 'frozenset': <class 'frozenset'>, 'print': <built-in function print>, 'Ellipsis': Ellipsis, 'OverflowError': <class 'OverflowError'>, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, 'BufferError': <class 'BufferError'>, 'open': <built-in function open>, 'exec': <built-in function exec>, 'slice': <class 'slice'>, 'memoryview': <class 'memoryview'>, 'bin': <built-in function bin>, 'SystemExit': <class 'SystemExit'>, 'property': <class 'property'>, 'UnicodeError': <class 'UnicodeError'>, 'issubclass': <built-in function issubclass>, 'chr': <built-in function chr>, 'max': <built-in function max>, 'dict': <class 'dict'>, 'ResourceWarning': <class 'ResourceWarning'>, 'NotImplemented': NotImplemented, 'ReferenceError': <class 'ReferenceError'>, 'setattr': <built-in function setattr>, 'copyright': Copyright (c) 2001-2017 Python Software Foundation.\nAll Rights Reserved.\n\nCopyright (c) 2000 BeOpen.com.\nAll Rights Reserved.\n\nCopyright (c) 1995-2001 Corporation for National Research Initiatives.\nAll Rights Reserved.\n\nCopyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.\nAll Rights Reserved., 'input': <built-in function input>, 'TabError': <class 'TabError'>, 'True': True, 'getattr': <built-in function getattr>, 'exit': Use exit() or Ctrl-D (i.e. EOF) to exit, '__build_class__': <built-in function __build_class__>, 'Exception': <class 'Exception'>, '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>), 'map': <class 'map'>, 'eval': <built-in function eval>, 'FileExistsError': <class 'FileExistsError'>, '__package__': '', 'LookupError': <class 'LookupError'>, 'enumerate': <class 'enumerate'>, 'StopIteration': <class 'StopIteration'>, 'SyntaxWarning': <class 'SyntaxWarning'>, 'dir': <built-in function dir>, 'ConnectionAbortedError': <class 'ConnectionAbortedError'>, 'StopAsyncIteration': <class 'StopAsyncIteration'>, 'pow': <built-in function pow>, 'UnboundLocalError': <class 'UnboundLocalError'>, 'BytesWarning': <class 'BytesWarning'>, 'NotADirectoryError': <class 'NotADirectoryError'>, 'type': <class 'type'>, 'min': <built-in function min>, 'float': <class 'float'>, 'DeprecationWarning': <class 'DeprecationWarning'>, 'ChildProcessError': <class 'ChildProcessError'>, 'BaseException': <class 'BaseException'>, 'ConnectionError': <class 'ConnectionError'>, 'ImportError': <class 'ImportError'>, 'classmethod': <class 'classmethod'>, 'IOError': <class 'OSError'>, 'bytearray': <class 'bytearray'>, 'format': <built-in function format>}", "__file__": "'/home/pi/cheerlights/cheerlights.py'", "__debug_code__": "<code object <module> at 0x713f0610, file \"/home/pi/cheerlights/cheerlights.py\", line 1>", "__debug_script__": "<_io.BufferedReader name='/home/pi/cheerlights/cheerlights.py'>"}, "lasti": "0", "exc_traceback": "''", "exc_type": "''", "globals": {"__name__": "'__main__'", "__builtins__": "{'FutureWarning': <class 'FutureWarning'>, 'NotImplementedError': <class 'NotImplementedError'>, 'range': <class 'range'>, 'compile': <built-in function compile>, 'iter': <built-in function iter>, 'str': <class 'str'>, 'RuntimeWarning': <class 'RuntimeWarning'>, 'help': Type help() for interactive help, or help(object) for help about object., 'tuple': <class 'tuple'>, '__doc__': \"Built-in functions, exceptions, and other objects.\\n\\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.\", 'FileNotFoundError': <class 'FileNotFoundError'>, 'sum': <built-in function sum>, 'any': <built-in function any>, 'ArithmeticError': <class 'ArithmeticError'>, 'round': <built-in function round>, 'complex': <class 'complex'>, 'filter': <class 'filter'>, '__name__': 'builtins', 'ValueError': <class 'ValueError'>, 'ord': <built-in function ord>, 'hash': <built-in function hash>, 'len': <built-in function len>, 'ProcessLookupError': <class 'ProcessLookupError'>, 'callable': <built-in function callable>, 'Warning': <class 'Warning'>, 'hex': <built-in function hex>, 'quit': Use quit() or Ctrl-D (i.e. EOF) to exit, 'InterruptedError': <class 'InterruptedError'>, '__debug__': True, 'all': <built-in function all>, 'BlockingIOError': <class 'BlockingIOError'>, 'UnicodeWarning': <class 'UnicodeWarning'>, 'MemoryError': <class 'MemoryError'>, 'BrokenPipeError': <class 'BrokenPipeError'>, 'globals': <built-in function globals>, 'TypeError': <class 'TypeError'>, 'list': <class 'list'>, 'IsADirectoryError': <class 'IsADirectoryError'>, 'AttributeError': <class 'AttributeError'>, 'super': <class 'super'>, 'False': False, 'SystemError': <class 'SystemError'>, 'repr': <built-in function repr>, 'delattr': <built-in function delattr>, 'next': <built-in function next>, 'TimeoutError': <class 'TimeoutError'>, 'bytes': <class 'bytes'>, 'hasattr': <built-in function hasattr>, 'ImportWarning': <class 'ImportWarning'>, 'UnicodeTranslateError': <class 'UnicodeTranslateError'>, 'sorted': <built-in function sorted>, 'RecursionError': <class 'RecursionError'>, 'id': <built-in function id>, 'staticmethod': <class 'staticmethod'>, 'ZeroDivisionError': <class 'ZeroDivisionError'>, 'vars': <built-in function vars>, 'zip': <class 'zip'>, 'GeneratorExit': <class 'GeneratorExit'>, 'IndexError': <class 'IndexError'>, 'KeyError': <class 'KeyError'>, 'UnicodeDecodeError': <class 'UnicodeDecodeError'>, 'UnicodeEncodeError': <class 'UnicodeEncodeError'>, 'ConnectionRefusedError': <class 'ConnectionRefusedError'>, 'AssertionError': <class 'AssertionError'>, 'OSError': <class 'OSError'>, 'IndentationError': <class 'IndentationError'>, 'object': <class 'object'>, 'credits':     Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands\n    for supporting Python development.  See www.python.org for more information., 'PermissionError': <class 'PermissionError'>, 'ascii': <built-in function ascii>, 'FloatingPointError': <class 'FloatingPointError'>, 'oct': <built-in function oct>, 'SyntaxError': <class 'SyntaxError'>, 'ConnectionResetError': <class 'ConnectionResetError'>, 'EOFError': <class 'EOFError'>, 'isinstance': <built-in function isinstance>, '__import__': <built-in function __import__>, 'bool': <class 'bool'>, 'reversed': <class 'reversed'>, 'locals': <built-in function locals>, 'abs': <built-in function abs>, 'NameError': <class 'NameError'>, '_': <bound method NullTranslations.gettext of <gettext.NullTranslations object at 0x7637e250>>, 'KeyboardInterrupt': <class 'KeyboardInterrupt'>, 'int': <class 'int'>, 'UserWarning': <class 'UserWarning'>, 'PendingDeprecationWarning': <class 'PendingDeprecationWarning'>, 'divmod': <built-in function divmod>, 'RuntimeError': <class 'RuntimeError'>, 'set': <class 'set'>, 'EnvironmentError': <class 'OSError'>, 'license': Type license() to see the full license text, 'None': None, 'frozenset': <class 'frozenset'>, 'print': <built-in function print>, 'Ellipsis': Ellipsis, 'OverflowError': <class 'OverflowError'>, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, 'BufferError': <class 'BufferError'>, 'open': <built-in function open>, 'exec': <built-in function exec>, 'slice': <class 'slice'>, 'memoryview': <class 'memoryview'>, 'bin': <built-in function bin>, 'SystemExit': <class 'SystemExit'>, 'property': <class 'property'>, 'UnicodeError': <class 'UnicodeError'>, 'issubclass': <built-in function issubclass>, 'chr': <built-in function chr>, 'max': <built-in function max>, 'dict': <class 'dict'>, 'ResourceWarning': <class 'ResourceWarning'>, 'NotImplemented': NotImplemented, 'ReferenceError': <class 'ReferenceError'>, 'setattr': <built-in function setattr>, 'copyright': Copyright (c) 2001-2017 Python Software Foundation.\nAll Rights Reserved.\n\nCopyright (c) 2000 BeOpen.com.\nAll Rights Reserved.\n\nCopyright (c) 1995-2001 Corporation for National Research Initiatives.\nAll Rights Reserved.\n\nCopyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.\nAll Rights Reserved., 'input': <built-in function input>, 'TabError': <class 'TabError'>, 'True': True, 'getattr': <built-in function getattr>, 'exit': Use exit() or Ctrl-D (i.e. EOF) to exit, '__build_class__': <built-in function __build_class__>, 'Exception': <class 'Exception'>, '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>), 'map': <class 'map'>, 'eval': <built-in function eval>, 'FileExistsError': <class 'FileExistsError'>, '__package__': '', 'LookupError': <class 'LookupError'>, 'enumerate': <class 'enumerate'>, 'StopIteration': <class 'StopIteration'>, 'SyntaxWarning': <class 'SyntaxWarning'>, 'dir': <built-in function dir>, 'ConnectionAbortedError': <class 'ConnectionAbortedError'>, 'StopAsyncIteration': <class 'StopAsyncIteration'>, 'pow': <built-in function pow>, 'UnboundLocalError': <class 'UnboundLocalError'>, 'BytesWarning': <class 'BytesWarning'>, 'NotADirectoryError': <class 'NotADirectoryError'>, 'type': <class 'type'>, 'min': <built-in function min>, 'float': <class 'float'>, 'DeprecationWarning': <class 'DeprecationWarning'>, 'ChildProcessError': <class 'ChildProcessError'>, 'BaseException': <class 'BaseException'>, 'ConnectionError': <class 'ConnectionError'>, 'ImportError': <class 'ImportError'>, 'classmethod': <class 'classmethod'>, 'IOError': <class 'OSError'>, 'bytearray': <class 'bytearray'>, 'format': <built-in function format>}", "__file__": "'/home/pi/cheerlights/cheerlights.py'", "__debug_code__": "<code object <module> at 0x713f0610, file \"/home/pi/cheerlights/cheerlights.py\", line 1>", "__debug_script__": "<_io.BufferedReader name='/home/pi/cheerlights/cheerlights.py'>"}, "filename": "/home/pi/cheerlights/cheerlights.py", "restricted": ""}]]}]
2018-04-07 13:09:14,455 - root:101(excepthook) ERROR: Unrecoverable error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mu/logic.py", line 775, in debug_toggle_breakpoint
    self.modes['debugger'].toggle_breakpoint(line, tab)
  File "/usr/lib/python3/dist-packages/mu/modes/debugger.py", line 199, in toggle_breakpoint
    self.debugger.disable_breakpoint(bps[line + 1])
KeyError: 15
2018-04-07 13:11:47,112 - root:112(run) INFO: 

-----------------
```

It's possible the debugger was about to display an exception thrown by the running code (as the script was doing that sometimes after a time out), but it closed before anything was printed to the editor panel, so I'm not sure.

**Comment by ntoll** [comment]
Fixed by 07b160bedb9609a1f4d37a0022e3f283243d6dc8
