### ISSUE TITLE
If I start mu-editor on macOS with my Adafruit Gemma connected, I get an IOError

### ISSUE THREAD

**Issue by offbyone** [mu-editor/mu#469]
If you are reporting a bug, we would like to know:

* What you were trying to do,

   Trying to start mu-editor on OSX, connected to an Adafruit Gemma wearable board.

* What steps you took to make this happen,

   `$ mu`

* What you expected to happen,

    The editor to open :)

* What actually happened,

```
Logging to /Users/offby1/Library/Logs/mu/mu.log
Traceback (most recent call last):
  File "/usr/local/bin/mu", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/mu/app.py", line 121, in run
    editor.setup(setup_modes(editor, editor_window))
  File "/usr/local/lib/python3.6/site-packages/mu/logic.py", line 396, in setup
    os.path.join(sounds_path, 'eep.wav'))
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
OSError: [Errno 28] No space left on device
```

* Why this difference is problematic (it may not be a bug!),

    Well, I can't run the editor. :)

* Technical details like the version of Mu you're using, your OS version and
  other aspects of the context in which Mu was running. 

I'm running `mu` on macOS 10.13.3 (17D47). `mu` was installed from homebrew, and is using the brew Python 3.6 interpreter.

The thing is, if I wait a while, `mu` will run fine. 

## Logs

```
-----------------

Starting Mu 1.0.0.beta.15
2018-05-17 16:16:19,799 - root:113(run) INFO: uname_result(system='Darwin', node='void.local', release='17.4.0', version='Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64', machine='x86_64', processor='i386')
2018-05-17 16:16:19,799 - root:114(run) INFO: Python path: ['/usr/local/bin', '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python36.zip', '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6', '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/site-packages/IPython/extensions']
2018-05-17 16:16:20,022 - mu.logic:355(__init__) INFO: Setting up editor.
2018-05-17 16:16:20,022 - mu.logic:366(__init__) INFO: Settings path: /Users/offby1/Library/Application Support/mu/settings.json
2018-05-17 16:16:20,023 - mu.logic:367(__init__) INFO: Log directory: /Users/offby1/Library/Logs/mu
2018-05-17 16:16:20,023 - mu.logic:368(__init__) INFO: Data directory: /Users/offby1/Library/Application Support/mu
2018-05-17 16:16:20,055 - mu.logic:376(setup) INFO: Available modes: python, adafruit, microbit, debugger, pygamezero
2018-05-17 16:16:20,056 - mu.logic:393(setup) DEBUG: Creating directory: /Volumes/CIRCUITPY/sounds
2018-05-17 16:16:20,057 - root:101(excepthook) ERROR: Unrecoverable error
Traceback (most recent call last):
  File "/usr/local/bin/mu", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/mu/app.py", line 121, in run
    editor.setup(setup_modes(editor, editor_window))
  File "/usr/local/lib/python3.6/site-packages/mu/logic.py", line 396, in setup
    os.path.join(sounds_path, 'eep.wav'))
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
OSError: [Errno 28] No space left on device
2018-05-17 16:22:48,689 - root:112(run) INFO: 

-----------------

Starting Mu 1.0.0.beta.15
2018-05-17 16:22:48,689 - root:113(run) INFO: uname_result(system='Darwin', node='void.local', release='17.4.0', version='Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64', machine='x86_64', processor='i386')
2018-05-17 16:22:48,689 - root:114(run) INFO: Python path: ['/usr/local/bin', '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python36.zip', '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6', '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/site-packages/IPython/extensions']
2018-05-17 16:22:48,898 - mu.logic:355(__init__) INFO: Setting up editor.
2018-05-17 16:22:48,898 - mu.logic:366(__init__) INFO: Settings path: /Users/offby1/Library/Application Support/mu/settings.json
2018-05-17 16:22:48,898 - mu.logic:367(__init__) INFO: Log directory: /Users/offby1/Library/Logs/mu
2018-05-17 16:22:48,898 - mu.logic:368(__init__) INFO: Data directory: /Users/offby1/Library/Application Support/mu
2018-05-17 16:22:48,930 - mu.logic:376(setup) INFO: Available modes: python, adafruit, microbit, debugger, pygamezero
2018-05-17 16:22:49,138 - mu.logic:712(change_mode) INFO: Workspace directory: /Volumes/CIRCUITPY
2018-05-17 16:22:49,138 - mu.logic:415(restore_session) INFO: Restoring session from: /Users/offby1/Library/Application Support/mu/settings.json
2018-05-17 16:22:49,138 - mu.logic:416(restore_session) DEBUG: {'theme': 'day', 'mode': 'adafruit', 'paths': ['/Volumes/CIRCUITPY/code.py'], 'workspace': '/Volumes/CIRCUITPY', 'microbit_runtime_hex': None}
2018-05-17 16:22:49,138 - mu.logic:470(_load) INFO: Loading script from: /Volumes/CIRCUITPY/code.py
2018-05-17 16:22:49,139 - mu.logic:496(_load) WARNING: could not load /Volumes/CIRCUITPY/code.py
2018-05-17 16:22:49,139 - mu.logic:435(restore_session) INFO: Loaded files.
2018-05-17 16:22:49,139 - mu.logic:439(restore_session) INFO: Passed-in filename: --version
2018-05-17 16:22:49,139 - mu.logic:470(_load) INFO: Loading script from: --version
2018-05-17 16:22:49,139 - mu.logic:496(_load) WARNING: could not load --version
2018-05-17 16:22:49,182 - mu.logic:444(restore_session) INFO: Starting with blank file.
2018-05-17 16:22:49,212 - mu.logic:712(change_mode) INFO: Workspace directory: /Volumes/CIRCUITPY
2018-05-17 16:22:49,984 - mu.modes.base:127(find_device) INFO: Found device on port: cu.usbmodem1411
2018-05-17 16:22:51,006 - mu.modes.base:127(find_device) INFO: Found device on port: cu.usbmodem1411
2018-05-17 16:22:52,006 - mu.modes.base:127(find_device) INFO: Found device on port: cu.usbmodem1411
2018-05-17 16:22:53,006 - mu.modes.base:127(find_device) INFO: Found device on port: cu.usbmodem1411
2018-05-17 16:22:54,006 - mu.modes.base:127(find_device) INFO: Found device on port: cu.usbmodem1411
2018-05-17 16:22:55,007 - mu.modes.base:127(find_device) INFO: Found device on port: cu.usbmodem1411
2018-05-17 16:22:56,007 - mu.modes.base:127(find_device) INFO: Found device on port: cu.usbmodem1411
2018-05-17 16:22:57,007 - mu.modes.base:127(find_device) INFO: Found device on port: cu.usbmodem1411
2018-05-17 16:22:58,006 - mu.modes.base:127(find_device) INFO: Found device on port: cu.usbmodem1411
2018-05-17 16:22:58,360 - mu.logic:657(quit) DEBUG: Session: {'theme': 'day', 'mode': 'adafruit', 'paths': [], 'workspace': '/Volumes/CIRCUITPY', 'microbit_runtime_hex': None}
2018-05-17 16:22:58,360 - mu.logic:658(quit) DEBUG: Saving session to: /Users/offby1/Library/Application Support/mu/settings.json
2018-05-17 16:22:58,360 - mu.logic:660(quit) INFO: Quitting.


2018-05-17 16:23:01,987 - root:112(run) INFO: 
```

That is the first unsuccessful and the one after it that succeeded.

**Comment by ntoll** [comment]
Hi @offbyone -- sorry to hear you encountered this problem too. It's a known bug in `beta-15` which has been fixed on `master`. The fix will be in the next release.
