### ISSUE TITLE
Betat 17 - QT error on Linix

### ISSUE THREAD

**Issue by jerryneedell** [mu-editor/mu#538]
I am having the same problem as in a closed issue  with Beta17
It installs fine via pip3 but gives the error below
same result using the virtual env.

``` 
Traceback (most recent call last):
  File "mu_venv/bin/mu-editor", line 7, in <module>
    from mu.app import run
  File "/home/jerryneedell/mu_venv/lib/python3.5/site-packages/mu/app.py", line 29, in <module>
    from PyQt5.QtCore import QTimer, Qt
ImportError: /home/jerryneedell/mu_venv/lib/python3.5/site-packages/PyQt5/QtCore.so: undefined symbol: PySlice_AdjustIndices
```

I see the reference to a new QT release, but it is not clear id there is recommended workaround.
I am on an Ubuntu 16.04 system
Thanks

**Comment by ntoll** [comment]
OK... when on Linux, you should follow the advice in the instructions (https://codewith.mu/en/howto/install_with_python) and use a virtualenv (until such time as we manage to get Mu accepted as a Debian package -- which is work that's ongoing).

This sort of error happens when different versions of Qt are found on the same computer. A virtualenv isolates your Python apps.

The simple instructions are:

* Ensure virtualenv and Python 3 are installed.
* In a new folder somewhere safe (e.g. in `~/virtualenvs`) type: `virtualenv --python=/usr/bin/python3 muvenv` (this creates a new virtualenv called `muenv` and uses Python3.
* Activate the new virtualenv like this: `source muvenv/bin/activate` (you'll see the name of the virtualenv prepended to your shell prompt, indicating the virtualenv is active)
* With the virtualenv active, type: `pip install mu-editor`.
* Once installed, and still with the virtualenv active, start mu: `mu-editor`

It should just work :tm:. ;-)

Please do let me know how you get on.

**Comment by ntoll** [comment]
OK... I'm on Ubuntu 17.10 and, following my instructions above, Mu installed fine. I'm not sure what more to suggest. :-/ Please do keep me posted.

**Comment by jerryneedell** [comment]
tried on Ubuntu 16.04
```
jerryneedell@Ubuntu-Macmini:~/mu_venv$ virtualenv --python=/usr/bin/python3 muvenv
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/jerryneedell/mu_venv/muvenv/bin/python3
Also creating executable in /home/jerryneedell/mu_venv/muvenv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
jerryneedell@Ubuntu-Macmini:~/mu_venv$ source muvenv/bin/activate
(muvenv) jerryneedell@Ubuntu-Macmini:~/mu_venv$ pip install mu-editor
Collecting mu-editor
  Using cached https://files.pythonhosted.org/packages/99/70/d63467c6d94cace750085e9891bc348642d6f07a12f6e3849c11d8d40f7d/mu_editor-1.0.0b17-py3-none-any.whl
Collecting pyqt5==5.11.2 (from mu-editor)
  Using cached https://files.pythonhosted.org/packages/3a/c7/4a9bec78c864051051b41b4cc76672ecc232e6dc7dbb91a5f8ff6f20ff64/PyQt5-5.11.2-5.11.1-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl
Collecting qtconsole==4.3.1 (from mu-editor)
  Using cached https://files.pythonhosted.org/packages/90/ff/047e0dca2627b162866920e7aa93f04523c0ae81e5c67060eec85701992d/qtconsole-4.3.1-py2.py3-none-any.whl
Collecting pyserial==3.4 (from mu-editor)
  Using cached https://files.pythonhosted.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl
Collecting gpiozero>=1.4.1 (from mu-editor)
  Using cached https://files.pythonhosted.org/packages/8f/df/2f22cea78f4539032e091579d6f32d9ebe360c04534838d151d37a667f2d/gpiozero-1.4.1-py2.py3-none-any.whl
Collecting pyflakes==2.0.0 (from mu-editor)
  Using cached https://files.pythonhosted.org/packages/44/98/af7a72c9a543b1487d92813c648cb9b9adfbc96faef5455d60f4439aa99b/pyflakes-2.0.0-py2.py3-none-any.whl
Collecting pigpio>=1.40.post1 (from mu-editor)
  Using cached https://files.pythonhosted.org/packages/76/38/f8cc5307ce65e79fab59385a56338716ab721fb27e4c116fdfc4226b000e/pigpio-1.40.post1-py2.py3-none-any.whl
Collecting pycodestyle==2.4.0 (from mu-editor)
  Using cached https://files.pythonhosted.org/packages/e5/c6/ce130213489969aa58610042dff1d908c25c731c9575af6935c2dfad03aa/pycodestyle-2.4.0-py2.py3-none-any.whl
Collecting matplotlib==2.2.2 (from mu-editor)
  Using cached https://files.pythonhosted.org/packages/81/31/4e261379e0cd4e9bbacfc96b124ebac0706b44374bd1d34ef899796f741b/matplotlib-2.2.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting appdirs>=1.4.3 (from mu-editor)
  Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting qscintilla==2.10.7 (from mu-editor)
  Using cached https://files.pythonhosted.org/packages/a6/d2/c13ab35d1747d7836d9ebdaad3bec1e7a6ce7681461f6db4765d691e2474/QScintilla-2.10.7-5.11.1-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl
Collecting guizero>=0.5.2 (from mu-editor)
  Using cached https://files.pythonhosted.org/packages/87/19/e8d1831fedc1328c39dacf9a9c5342ceed0315cf301aa2284cd09fc91e9e/guizero-0.5.2-py3-none-any.whl
Collecting pgzero==1.2 (from mu-editor)
  Using cached https://files.pythonhosted.org/packages/48/e5/e5f14292373cb5fc7539aa01307b184c1e3c954d68945d8c44778669dd82/pgzero-1.2-py3-none-any.whl
Collecting PyQtChart==5.11.2 (from mu-editor)
  Using cached https://files.pythonhosted.org/packages/77/b6/ed090be2ecef15fe8a2767a42ca66b884c2ef5777e081f0ac2e7b6e4eeed/PyQtChart-5.11.2-5.11.1-cp35.cp36.cp37.cp38-abi3-manylinux1_x86_64.whl
Collecting semver>=2.8.0 (from mu-editor)
  Using cached https://files.pythonhosted.org/packages/21/18/a0de8cda637ba3efee1b3617ded00601507ce15bd70a39399740e0fd415f/semver-2.8.1-py2.py3-none-any.whl
Collecting requests>=2.19.1 (from mu-editor)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting Pillow>=5.2.0 (from mu-editor)
  Using cached https://files.pythonhosted.org/packages/3d/9e/b8a10bec874d2f6f2668b0d71ddf0d0a69ed9307d2ef111607adf81fdc1c/Pillow-5.2.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting PyQt5_sip<4.20,>=4.19.11 (from pyqt5==5.11.2->mu-editor)
  Using cached https://files.pythonhosted.org/packages/1f/73/a097e063ea84f9c0d5641bd45fd0147d7e88ad0e92c86638fa7ada14f436/PyQt5_sip-4.19.12-cp35-cp35m-manylinux1_x86_64.whl
Collecting pygments (from qtconsole==4.3.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/02/ee/b6e02dc6529e82b75bb06823ff7d005b141037cb1416b10c6f00fc419dca/Pygments-2.2.0-py2.py3-none-any.whl
Collecting jupyter-client>=4.1 (from qtconsole==4.3.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/94/dd/fe6c4d683b09eb05342bd2816b7779663f71762b4fa9c2d5203d35d17354/jupyter_client-5.2.3-py2.py3-none-any.whl
Collecting jupyter-core (from qtconsole==4.3.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/1d/44/065d2d7bae7bebc06f1dd70d23c36da8c50c0f08b4236716743d706762a8/jupyter_core-4.4.0-py2.py3-none-any.whl
Collecting ipykernel>=4.1 (from qtconsole==4.3.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/ab/3f/cd624c835aa3336a9110d0a99e15070f343b881b7d651ab1375ef226a3ac/ipykernel-4.8.2-py3-none-any.whl
Collecting traitlets (from qtconsole==4.3.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl
Collecting ipython-genutils (from qtconsole==4.3.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting numpy>=1.7.1 (from matplotlib==2.2.2->mu-editor)
  Using cached https://files.pythonhosted.org/packages/43/17/cd9fa14492dbef2aaf22622db79dba087c10f125473e730cda2f2019c40b/numpy-1.14.5-cp35-cp35m-manylinux1_x86_64.whl
Collecting cycler>=0.10 (from matplotlib==2.2.2->mu-editor)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting pytz (from matplotlib==2.2.2->mu-editor)
  Using cached https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib==2.2.2->mu-editor)
  Using cached https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib==2.2.2->mu-editor)
  Using cached https://files.pythonhosted.org/packages/7e/31/d6fedd4fb2c94755cd101191e581af30e1650ccce7a35bddb7930fed6574/kiwisolver-1.0.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting six>=1.10 (from matplotlib==2.2.2->mu-editor)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting python-dateutil>=2.1 (from matplotlib==2.2.2->mu-editor)
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting pygame<2.0,>=1.9.2 (from pgzero==1.2->mu-editor)
  Using cached https://files.pythonhosted.org/packages/92/dd/a4931cd7aab2652d4b1342c39c1db67a1744359e2137c897d552f4fe7d0e/pygame-1.9.3-cp35-cp35m-manylinux1_x86_64.whl
Collecting urllib3<1.24,>=1.21.1 (from requests>=2.19.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.19.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.19.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests>=2.19.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting tornado>=4.1 (from jupyter-client>=4.1->qtconsole==4.3.1->mu-editor)
Collecting pyzmq>=13 (from jupyter-client>=4.1->qtconsole==4.3.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/4a/9c/c736101a42da5947985ff297c2837795f55a1c016cebcc3b49f31ce75c67/pyzmq-17.0.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting ipython>=4.0.0 (from ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/b1/7f/91d50f28af3e3a24342561983a7857e399ce24093876e6970b986a0b6677/ipython-6.4.0-py3-none-any.whl
Collecting decorator (from traitlets->qtconsole==4.3.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/bc/bb/a24838832ba35baf52f32ab1a49b906b5f82fb7c76b2f6a7e35e140bac30/decorator-4.3.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./muvenv/lib/python3.5/site-packages (from kiwisolver>=1.0.1->matplotlib==2.2.2->mu-editor) (40.0.0)
Collecting backcall (from ipython>=4.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
Collecting pickleshare (from ipython>=4.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/9f/17/daa142fc9be6b76f26f24eeeb9a138940671490b91cb5587393f297c8317/pickleshare-0.7.4-py2.py3-none-any.whl
Collecting prompt-toolkit<2.0.0,>=1.0.15 (from ipython>=4.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/04/d1/c6616dd03701e7e2073f06d5c3b41b012256e42b72561f16a7bd86dd7b43/prompt_toolkit-1.0.15-py3-none-any.whl
Collecting pexpect; sys_platform != "win32" (from ipython>=4.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/89/e6/b5a1de8b0cc4e07ca1b305a4fcc3f9806025c1b651ea302646341222f88b/pexpect-4.6.0-py2.py3-none-any.whl
Collecting simplegeneric>0.8 (from ipython>=4.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
Collecting jedi>=0.10 (from ipython>=4.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/3d/68/8bbf0ef969095a13ba0d4c77c1945bd86e9811960d052510551d29a2f23b/jedi-0.12.1-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.15->ipython>=4.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython>=4.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
Collecting parso>=0.3.0 (from jedi>=0.10->ipython>=4.0.0->ipykernel>=4.1->qtconsole==4.3.1->mu-editor)
  Using cached https://files.pythonhosted.org/packages/09/51/9c48a46334be50c13d25a3afe55fa05c445699304c5ad32619de953a2305/parso-0.3.1-py2.py3-none-any.whl
Installing collected packages: PyQt5-sip, pyqt5, pygments, tornado, six, python-dateutil, pyzmq, decorator, ipython-genutils, traitlets, jupyter-core, jupyter-client, backcall, pickleshare, wcwidth, prompt-toolkit, ptyprocess, pexpect, simplegeneric, parso, jedi, ipython, ipykernel, qtconsole, pyserial, gpiozero, pyflakes, pigpio, pycodestyle, numpy, cycler, pytz, pyparsing, kiwisolver, matplotlib, appdirs, qscintilla, Pillow, guizero, pygame, pgzero, PyQtChart, semver, urllib3, chardet, certifi, idna, requests, mu-editor
Successfully installed Pillow-5.2.0 PyQt5-sip-4.19.12 PyQtChart-5.11.2 appdirs-1.4.3 backcall-0.1.0 certifi-2018.4.16 chardet-3.0.4 cycler-0.10.0 decorator-4.3.0 gpiozero-1.4.1 guizero-0.5.2 idna-2.7 ipykernel-4.8.2 ipython-6.4.0 ipython-genutils-0.2.0 jedi-0.12.1 jupyter-client-5.2.3 jupyter-core-4.4.0 kiwisolver-1.0.1 matplotlib-2.2.2 mu-editor-1.0.0b17 numpy-1.14.5 parso-0.3.1 pexpect-4.6.0 pgzero-1.2 pickleshare-0.7.4 pigpio-1.40.post1 prompt-toolkit-1.0.15 ptyprocess-0.6.0 pycodestyle-2.4.0 pyflakes-2.0.0 pygame-1.9.3 pygments-2.2.0 pyparsing-2.2.0 pyqt5-5.11.2 pyserial-3.4 python-dateutil-2.7.3 pytz-2018.5 pyzmq-17.0.0 qscintilla-2.10.7 qtconsole-4.3.1 requests-2.19.1 semver-2.8.1 simplegeneric-0.8.1 six-1.11.0 tornado-5.0.2 traitlets-4.3.2 urllib3-1.23 wcwidth-0.1.7
(muvenv) jerryneedell@Ubuntu-Macmini:~/mu_venv$ mu-editor 
Traceback (most recent call last):
  File "/home/jerryneedell/mu_venv/muvenv/bin/mu-editor", line 7, in <module>
    from mu.app import run
  File "/home/jerryneedell/mu_venv/muvenv/lib/python3.5/site-packages/mu/app.py", line 29, in <module>
    from PyQt5.QtCore import QTimer, Qt
ImportError: /home/jerryneedell/mu_venv/muvenv/lib/python3.5/site-packages/PyQt5/QtCore.so: undefined symbol: PySlice_AdjustIndices
(muvenv) jerryneedell@Ubuntu-Macmini:~/mu_venv$ 
```

**Comment by jerryneedell** [comment]
tried on  Ubuntu 18.04
```
jerryneedell@Ubuntu18:~/mu_venv$ virtualenv --python=/usr/bin/python3 muvenv
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/jerryneedell/mu_venv/muvenv/bin/python3
Also creating executable in /home/jerryneedell/mu_venv/muvenv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
jerryneedell@Ubuntu18:~/mu_venv$ pip install mu-editor
Collecting mu-editor
  Downloading https://files.pythonhosted.org/packages/c4/88/8ac7af11af5cb3d8825eb3a660087801af333e80b70eb8fb923bd3871f54/mu-editor-1.0.0b17.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 769kB/s 
Collecting Pillow>=5.2.0 (from mu-editor)
  Downloading https://files.pythonhosted.org/packages/6e/27/709a8493071ec649a56d5a3194f648ec7cd792189e994bbd2ef5d285670d/Pillow-5.2.0-cp27-cp27mu-manylinux1_x86_64.whl (2.0MB)
    100% |████████████████████████████████| 2.0MB 536kB/s 
Collecting PyQtChart==5.11.2 (from mu-editor)
  Could not find a version that satisfies the requirement PyQtChart==5.11.2 (from mu-editor) (from versions: )
No matching distribution found for PyQtChart==5.11.2 (from mu-editor)
jerryneedell@Ubuntu18:~/mu_venv$ 
```

**Comment by tjguk** [comment]
Chipping in rather late: the error message in the OP refers to a Python API that was only added in 3.6.1. Since the venv is using Python 3.5 it appears that Qt have offered a wheel fo 3.5 which uses code only available in 3.6

**Comment by ntoll** [comment]
Aha... so Mu will now only work with Python 3.6+ as a result, right..?

**Comment by ZanderBrown** [comment]
Sounds like a Qt bug rather than anything else

**Comment by jerryneedell** [comment]
@ntoll FYI -- I was finally able to get mu running on Ubuntu 16.04 after installing python3.6 then using "sudo pip3.6 install mu-editor"
Congratulations on the 1.0.0 release!

**Comment by ntoll** [comment]
Good to hear. Thank you.
