### ISSUE TITLE
REPL data crashed Mu

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/mu#701]
Was using Mu as a micro:bit REPL with upstream MicroPython and after executing a few lines of code Mu crashed.

Relevant part of the log:
```
2018-11-11 22:49:18,089 - mu.modes.base:217(find_device) INFO: Found device on port: cu.usbmodem141202
2018-11-11 22:49:18,089 - mu.modes.base:218(find_device) INFO: Serial number: 9900023436424e45004c30150000004f00000000cb8928bd
2018-11-11 22:49:18,103 - mu.modes.base:268(add_repl) INFO: Started REPL on port: /dev/cu.usbmodem141202
2018-11-11 22:49:18,104 - mu.modes.base:249(toggle_repl) INFO: Toggle REPL on.
2018-11-11 22:50:48,272 - root:95(excepthook) ERROR: Unrecoverable error
Traceback (most recent call last):
  File "/Users/microbit-carlos/Downloads/micropython/mu-editor-1.0.1.app/Contents/Resources/app/mu/interface/panes.py", line 231, in process_bytes
    elif len(data) > 1 and data[i] == 27 and data[i + 1] == 91:
IndexError: index out of range
2018-11-11 22:50:51,161 - root:112(run) INFO: 

-----------------
```

Offending line: 

https://github.com/mu-editor/mu/blob/f89fc697ca67df9f71447b7f75aae521e4882fff/mu/interface/panes.py#L231

Bigger code block for context:

https://github.com/mu-editor/mu/blob/f89fc697ca67df9f71447b7f75aae521e4882fff/mu/interface/panes.py#L225-L235

That line should probably be:

```python
elif len(data) > i + 1 and data[i] == 27 and data[i + 1] == 91:
```

**Comment by carlosperate** [comment]
I just had the same issue running the REPL with a micro:bit with micro:bit MicroPython v0.9:

```
2018-12-14 11:53:58,452 - mu.modes.base:249(toggle_repl) INFO: Toggle REPL on.
2018-12-14 11:56:11,361 - root:95(excepthook) ERROR: Unrecoverable error
Traceback (most recent call last):
  File "/Users/microbit-carlos/Downloads/micropython/mu-editor-1.0.1.app/Contents/Resources/app/mu/interface/panes.py", line 231, in process_bytes
    elif len(data) > 1 and data[i] == 27 and data[i + 1] == 91:
IndexError: index out of range
2018-12-14 11:56:20,498 - root:112(run) INFO: 

-----------------
```
