### ISSUE TITLE
pgzero mode error shows truncated stack trace

### ISSUE THREAD

**Issue by bennuttall** [mu-editor/mu#706]
The pgzero mode seems to truncate the stack trace when outputting errors which lie within pgzero.

The following one-line example is enough to demonstrate:

```python
actor = Actor('alien')
```

This will work fine if `images/alien.png` exists. If there's no `images` directory, then `pgzrun` from the terminal will give a meaningful error message:

```python
ben@gunter:~/Projects/bennuttall/pgz-campug {master} $ pgzrun game.py 
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "/usr/local/bin/pgzrun", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pgzero/runner.py", line 92, in main
    exec(code, mod.__dict__)
  File "game.py", line 4, in <module>
    alien = Actor('alien')
  File "/usr/local/lib/python3.6/dist-packages/pgzero/actor.py", line 88, in __init__
    self.image = image
  File "/usr/local/lib/python3.6/dist-packages/pgzero/actor.py", line 103, in __setattr__
    return object.__setattr__(self, attr, value)
  File "/usr/local/lib/python3.6/dist-packages/pgzero/actor.py", line 218, in image
    self._orig_surf = self._surf = loaders.images.load(image)
  File "/usr/local/lib/python3.6/dist-packages/pgzero/loaders.py", line 120, in load
    self.validate_root(name)
  File "/usr/local/lib/python3.6/dist-packages/pgzero/loaders.py", line 102, in validate_root
    subpath=self.subpath, type=self.TYPE, name=name
KeyError: "No 'images' directory found to load image 'alien'."
```

However, Mu gives a truncated stack trace which contains no useful information for the user:

```python
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/pgzero/__main__.py", lin

---------- FINISHED ----------
exit code: 1 status: 0
```

![screenshot from 2018-11-14 11-04-48](https://user-images.githubusercontent.com/1609725/48478860-6f9b7000-e7fd-11e8-8758-9376709c26c4.png)

It would be great Mu could show the error alone, without the track trace. And to be honest if pgzero could too, that would be great. ping @lordmauve

**Comment by carlosperate** [comment]
I can confirm the truncated error text also happens in macOS with Mu v1.0.1 from the installer.
